### ISSUE TITLE
"Implementing a New Environment" tutorial is outdated

### ISSUE THREAD

**Issue by chuanzhengtmac24** [rlworkgroup/garage#1003]
Has any one tried the tutorial on Document for the point environment. I run the trpo_point file and it shows like this. Does anyone come up with the same issue? Thanks a lot anyways.
<img width="1177" alt="Screen Shot 2019-11-05 at 5 52 33 PM" src="https://user-images.githubusercontent.com/39918901/68255283-d57a9c00-fffa-11e9-98a6-9d8e93b1d5fe.png">

**Comment by ryanjulian** [comment]
@chuanzhengtmac24 It looks like that part of the documentation is out-of-date, and doesn't use the correct API for running an algorithm.

Please refer to the updated [examples](https://github.com/rlworkgroup/garage/tree/master/examples) for how to run an algorithm. Your code lacks usage of the `LocalRunner` interface, which is now required to run the examples.

I'll also caution that we haven't reviewed the Environment tutorial in a while, and it might contain some inaccuracies. You can find the latest example of PointEnv [here](https://github.com/rlworkgroup/garage/blob/master/src/garage/envs/point_env.py). 

If you find inconsistencies in the documentation, please feel free to send a PR updating it. We always love improvements to the toolkit.

**Comment by chuanzhengtmac24** [comment]
Hi,
Thanks for the reply. I used the latest example form of trpo and the latest PointEnv from the link above, but still get the same bug. Is there any hint for this? Thanks
<img width="1688" alt="Screen Shot 2019-11-05 at 8 27 47 PM" src="https://user-images.githubusercontent.com/39918901/68260509-39a55c00-000b-11ea-9204-a38af5dc9f5e.png">

**Comment by ryanjulian** [comment]
You need to wrap your example in `TfEnv` in order for it to be trainable with garage.

See https://github.com/rlworkgroup/garage/blob/master/examples/tf/ppo_pendulum.py#L28

**Comment by chuanzhengtmac24** [comment]
Thank you so much and now it works.
