### ISSUE TITLE
Question: Is Actor-Critic related algorithms being added any time in the near future?

### ISSUE THREAD

**Issue by kishanpb** [rlworkgroup/garage#1007]

**Comment by ryanjulian** [comment]
@kishanpb We implement DDPG in both TensorFlow and PyTorch, which is an actor-critic method. We will also be adding SAC in PyTorch shortly.

If you are referring to the A2C/A3C/ACKTR/ACER family of algorithms, we don't have anyone working on those right now. If you'd like to contribute an implementation(s), we'd love to review it.
