### ISSUE TITLE
Log success rate from all algorithms (or samplers)

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1015]
We usually focus on AverageDiscountedReturn, but many RL environments use an arbitrary shaped reward (which means ADR doesn't help much) and are better measured using success rate.

Success rate is simple to calculate. If I have a batch of `paths`, then the success rate is just:
```python
success_rate = np.mean([np.any(p['dones']) for p in paths])
```
i.e. it's just the portion of paths which actually experienced a termination condition before being the end of the episode.

**Comment by naeioi** [comment]
Success rate is useful to reason about the process of experiment, I wonder if it is also useful in training policy. 

Is this issue a priority? Currently, only DDPG logs success rate. I see this more of a problem of code consistency.

**Comment by ryanjulian** [comment]
Fairly high-priority, since it's needed to run metaworld benchmarks. I think this can be covered by @zequnyu 's work on #1091 . Perhaps if you want to help tackle it you can help him finish that issue? It might require multiple PRs.

**Comment by naeioi** [comment]
@gitanshu recently reached out to me on this issue. Do you feel like working on this?

**Comment by ryanjulian** [comment]
@krzentner @zequnyu is this fixed? for *all* algorithms?

**Comment by zequnyu** [comment]
This is covered by #1116 and #1142.
