### ISSUE TITLE
Runner should log total environment steps (and other vital stats)

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1021]
This will make it easier to compute algorithm performance consistently.

**Comment by zequnyu** [comment]
Is this what you are looking for?
https://github.com/rlworkgroup/garage/blob/169c822573d3899911590988450e2466767f2451/src/garage/tf/algos/batch_polopt.py#L94

**Comment by ryanjulian** [comment]
Yes. I think this is basically a duplicate of the evaluation PRs you are working on.

**Comment by zequnyu** [comment]
Closed by #1017.
