### ISSUE TITLE
Local runner doesn't allow truncate paths when obtains samples

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#1028]
OnPolicyVectorizedSampler has an argument `whole_paths` which allows us to truncate paths if number of samples generated exceeds the given size. However, such argument doesn't exist in LocanRunner thus cannot be populated to the sampler when training.

**Comment by ryanjulian** [comment]
I thought that we're planning on deleting the `whole_paths` option?

**Comment by ahtsan** [comment]
I see, then this issue can be closed.
