### ISSUE TITLE
LocalRunner opens *many* plotter windows

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1034]
Steps to reproduce:
* Open `examples/tf/trpo_cartpole.py`
* Set `plot=True` on both `runner.train` and `run_experiment`
* Run the example
* Watch as a new plotter window open after each episode. The inactive windows also appear to be orphan processes.

**Comment by zequnyu** [comment]
I'll look into it.

**Comment by ryanjulian** [comment]
can you also look at #354 while you're at it?
