### ISSUE TITLE
Define TrajectoryBatch and SampleBatch data structures

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1057]

**Comment by naeioi** [comment]
Any background on SampleBatch? @ryanjulian @krzentner

**Comment by ryanjulian** [comment]
It's a batch of Sample objects. I'm not sure it needs to exist. 

It is used when you wanted to access the fields a batch of samples collectively. For instance, if you want a tensor (numpy array) of all the sampled actions to feed to a neural network

You can actually already see this happening in PathBuffer, but it's not a well-defined data structure:
https://github.com/rlworkgroup/garage/blob/master/src/garage/replay_buffer/path_buffer.py#L92
https://github.com/rlworkgroup/garage/blob/master/src/garage/torch/algos/ddpg.py#L181
https://github.com/rlworkgroup/garage/blob/master/src/garage/torch/algos/ddpg.py#L223

After we define this, `optimize_policy` in DDPG above can accept `samples_data: garage.SampleBatch` instead of `samples_data: Dict[str, np.ndarray]`

```python
BATCH_SIZE = 1024
sb = replay_buffer.sample(1024)
print(sb.actions)  # -> np.ndarry with shape (1024, *env.action_space.low.shape)
```

**Comment by ryanjulian** [comment]
Basically this would take what's already happening and attach a type to it, so the code is more clear and the correct keys are guaranteed to exist.

It can also define helper functions, e.g. `.to()` in the case of torch, to help reduce the proliferation of helper functions. Most of "utils" and "tensor_utils" modules just provide different views on the same data, or do things like convert data to torch.Tensor, etc.

**Comment by naeioi** [comment]
Can I say that BatchSampler is the data structure of path buffer? It provides utility methods for off-policy algorithms (e.g. sample a subset of data).

As for TrajectoryBatch, it is already in _dtype. What do we need to do with it in this issue?

**Comment by ryanjulian** [comment]
`TrajectoryBatch` is already defined. It needs to replace `paths` throughout the codebase, but that's a different issue (#1110 )

`SampleBatch` is the analogous data structure to `TrajectoryBatch`, but for sample-oriented (e.g. off-policy) algorithms. It defines a dtype for the interface between replay buffers and algorithms.

PathBuffer is just one implementation of a ReplayBuffer, whose API we need to define ( #1468 ), but the API will basically look like `PathBuffer`.

What needs to be done here is for someone to add the `SampleBatch` dtype and tests for it.

**Comment by AiRuiChen** [comment]
I have a few questions:

1.  Should `SampleBatch` only be the interface _between_ `PathBuffer` and algorithms? If so, then [`sample_transitions`](https://github.com/rlworkgroup/garage/blob/master/src/garage/replay_buffer/path_buffer.py#L92) will fetch data from `self._buffer`, convert to a `SampleBatch` object and return it.
Another possibility is to replace `PathBuffer.self._buffer = {}` with `PathBuffer.self._buffer = SampleBatch`, so we avoid ambiguity (e.g. what are the keys, etc.) _inside_ PathBuffer buffer as well. 
The key difference (I think) here is: if `SampleBatch` is an intermediate _interface_, it should only allow read. If it is stored as an _internal object_, then it should allow read and write. 

2. What are the keys of each path? Should all paths contain all these keys? As far as I can tell from [here](https://github.com/rlworkgroup/garage/blob/master/src/garage/torch/algos/sac.py#L190), the keys are `observation`, `action`, `reward`, `next_observation`, `terminal`. Am I missing anything? (Can't find any documentation lol)

**Comment by AiRuiChen** [comment]
> I have a few questions:
> 
> 1. Should `SampleBatch` only be the interface _between_ `PathBuffer` and algorithms? If so, then [`sample_transitions`](https://github.com/rlworkgroup/garage/blob/master/src/garage/replay_buffer/path_buffer.py#L92) will fetch data from `self._buffer`, convert to a `SampleBatch` object and return it.
>    Another possibility is to replace `PathBuffer.self._buffer = {}` with `PathBuffer.self._buffer = SampleBatch`, so we avoid ambiguity (e.g. what are the keys, etc.) _inside_ PathBuffer buffer as well.
>    The key difference (I think) here is: if `SampleBatch` is an intermediate _interface_, it should only allow read. If it is stored as an _internal object_, then it should allow read and write.
> 2. What are the keys of each path? Should all paths contain all these keys? As far as I can tell from [here](https://github.com/rlworkgroup/garage/blob/master/src/garage/torch/algos/sac.py#L190), the keys are `observation`, `action`, `reward`, `next_observation`, `terminal`. Am I missing anything? (Can't find any documentation lol)

@maliesa96 @krzentner Any thoughts on question 2?

**Comment by maliesa96** [comment]
1. About making it read only vs r/w, personally I think it should be read only. Seeing a `SampleBatch` object should imply that this object will be processed by the algorithm at some point, so I don't think `self._buffer` needs to be a `SampleBatch`. Making it r/w seems redundant because then it starts to resemble a replay buffer.

2. The keys are plural (`actions`, `observations`, etc.). As far as the keys that are stored in the replay buffer, those are it. There are certain environments that return a nested dict observation (to be used with the HER buffer) that looks like this: 
```
observation: {achieved_goal: [1,1],
              desired_goal: [1,0],
              observation: [1,1,1]}
```

But these are flattened by `PathBuffer` so that the resulting data in `PathBuffer._buffer` does not contain any dicts, which means `SampleBatch` shouldn't have to handle the logic for this.
