### ISSUE TITLE
Calculation

### ISSUE THREAD

**Issue by surbhi1944** [rlworkgroup/garage#1071]
How can i estimate total time steps when do training. As in this repository we are passing number of epochs.
runner.train(n_epochs=500,n_epoch_cycle=1000)

But most of the research papers reflects training results in time steps.

Also if i want to train a model for say 5 million time steps. Then how can i set different variables this?

**Comment by ryanjulian** [comment]
Thanks for the question. We are working on making this simpler in garage (e.g. you can track #998). 

We would love your help making the logging more consistent, if you're interested.

You can always examine the `TotalEnvSteps` variable in logs (e.g. in `data/local/my_experiment/progress.csv` or TensorBoard). Currently TensorBoard logs use `n_epochs` as the x-axis, but we're working on changing that (i.e. see #1069)

The exact relationship between `n_epochs`, `n_epoch_cycles` and `TotalEnvSteps` is an algorithm-specific quantity. For an on-policy algorithm, the total number of environment steps is usually just `n_epochs * batch_size`. For an off-policy algorithm, this may instead by `n_epochs * n_epoch_cycles * batch_size` (e.g. see https://github.com/rlworkgroup/garage/blob/master/src/garage/np/algos/off_policy_rl_algorithm.py#L93).

@naeioi @zequnyu 

I'm going to close this issue. Let us know if you find any flaws in garage we can help with, or if you'd like to contribute some code.
