### ISSUE TITLE
Add support for evaluation sampling

### ISSUE THREAD

**Issue by avnishn** [rlworkgroup/garage#1084]
Currently, garage does evaluations for off-policy algorithms based on previously collected samples (what @ryanjulian calls the ring buffer I believe) however, this doesn't allow for deterministic evaluation of policies. I propose we have a **deterministic** evaluation sampler that runs in parallel to our off-policy experiments in order to optimize for speed while still allowing for the most accurate updates on training performance.

I believe @krzentner also had some ideas/thoughts about this and that @zequnyu would know best about how to go about incorporating an evaluation sampler into the runner while having minimal performance impacts.

**Comment by ryanjulian** [comment]
Logging with the ring buffer is perfectly deterministic (assuming you don't use an exploration policy), but it will report lagging peformance indicators.

**Comment by avnishn** [comment]
Does garage have an option to make rollouts deterministic? I haven't seen one. Perhaps we should add this if it does not exist

**Comment by ryanjulian** [comment]
Yes. Look at the `rollout` function.

**Comment by avnishn** [comment]
I'm thinking of taking the rollout function and using it to build a generator styled single step sampler . 

Also, rollout has a deterministic option, however the samplers we provide don't have an option to collect samples of deterministic actions. Doesn't that mean that the samples we currently do evaluation are based on actions that were sampled from a random distribution. Wouldn't that be the wrong thing to communicate, as opposed to samples that are based on actions that are the mean of the distributions produced by the policy?

**Comment by ryanjulian** [comment]
If a policy is distributional, then to assess its performance you must sample from the distribution. The policies are not "random" distributions, they are very carefully chosen distributions.

Sometimes people just use the means of Gaussian policies to generate smoother movements or to execute on real robots, this is a convenient hack, but it's not how RL algorithms are assessed.

Note that not all distributions have means. What is the mean of a categorical distribution? What about the mean of an arbitrary distribution represented by a histogram?

**Comment by ryanjulian** [comment]
Anyway -- I think that this could be implemented 2 ways without impacting training time:

1) Implement an evaluator worker, much like the plotter is now.
1) Make it a feature of the sampler to run one (or more) of its workers as evaluators
1) Use the sampler "Worker" abstractions to create an "Evalulator" which is in the same family as "Sampler" and "Plotter" (basically they are all just a collection of workers which receive policy/env updates and produce zero-or-more data periodically)

I think 2 and 3 are more promising because I think that the plotter could also benefit from using the sampler's infrastructure.

**Comment by avnishn** [comment]
@krzentner I thought we solved this with the evaluation logging interface?

**Comment by avnishn** [comment]
I believe that this issue is close by src/garage/np/algos/off_policy_rla.py::_obtain_evaluation_samples
