### ISSUE TITLE
Add a performance evaluation interface to the RLAlgorithm base class

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1091]
Right now, performance of each algorithm is calculated within that algorithm. This means each algorithm may use different logger keys, math implementations, or metrics entirely to report its performance, and makes comparing results challenging.

I chatted with @krzentner and believe we can solve this in a fairly simple way, with a 2-part process

1. Define a performance evaluation API in the RLAlgorithm base class. This calculates and logs the performance of *any* algorithm using a batch of samples from the algorithm.
2. Each algorithm defines for itself how to generate the evaluation batch, and calls the evaluation API with the relevant frequency (e.g. once per epoch). For on-policy algorithms, the evaluation batch can just be the most recent batch of samples. Off-policy algorithms might need to do something more complicated, such as asking the replay buffer for the most recent `n` complete paths, or running some rollouts themselves (some on-policy algorithms add noise to their actions during sampling, but not during evaluation). Some algorithms might need to do something even more different (even having a whole other sampler for evaluation), but *how* they get the evaluation samples doesn't matter as long as they pass the batch to the API.

```python

class RLAlgorithm:
    
    @classmethod
    def evaluate_performance(evaluation_batch):
    """Evaluate the performance of the algorithm using a batch of trajectories.

    Args:
        evaluation_batch (TrajectoryBatch): A :obj:`TrajectoryBatch` of evaluation
            trajectories, representing the best current performance of the
            algorithm.
    """

Most of this code already exists in multiple places, e.g.
https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/algos/batch_polopt.py#L257
https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/algos/ddpg.py#L288
https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/algos/dqn.py#L215
https://github.com/rlworkgroup/garage/blob/master/src/garage/np/algos/batch_polopt.py#L134
https://github.com/rlworkgroup/garage/blob/master/src/garage/np/algos/off_policy_rl_algorithm.py#L132

refs:
https://github.com/rlworkgroup/garage/issues/1084
https://github.com/rlworkgroup/garage/issues/1077
https://github.com/rlworkgroup/garage/issues/1015
https://github.com/rlworkgroup/garage/blob/master/src/garage/_dtypes.py#L7

**Comment by avnishn** [comment]
https://github.com/openai/spinningup/blob/b6965d89f5b713f6ad2a5fbef8f4db4fe4013250/spinup/algos/sac/sac.py#L220

this function seems like a useful resource.

**Comment by ryanjulian** [comment]
@krzentner @zequnyu is this done?

**Comment by zequnyu** [comment]
This is done.
