### ISSUE TITLE
Algorithms should use SamplesBatch

### ISSUE THREAD

**Issue by avnishn** [rlworkgroup/garage#1113]

**Comment by ryanjulian** [comment]
Which PR closed this?

**Comment by ryanjulian** [comment]
It doesn't seem like algorithms use the new dtype yet?

**Comment by avnishn** [comment]
We moved forward with not having a samples Batch dtype. We now have the `TrajectoryBatch` dtype and the `TimeStep` dtype. Therefore, the issue is no longer applicable. I will open another issue that suggests that we use the new `TimeStep` dtype for off policy algos.
