### ISSUE TITLE
tf.compat.v1.get_default_session() returns NoneType

### ISSUE THREAD

**Issue by JialouWang** [rlworkgroup/garage#1135]
```
File "/garage/src/garage/tf/models/base.py", line 202, in build 
 tf.compat.v1.get_default_session().run(
AttributeError: 'NoneType' object has no attribute 'run'
```
When I try to build a GaussianMLP model, this tf.compat.v1.get_default_session() gives me a NoneType. Where is this default session being initialized? or should i create one by my self?
Sorry if this is a dumb question

More detailed log:
```
  File "//garage/src/garage/tf/policies/gaussian_mlp_policy.py", line 116, in __init__
    self._initialize()
  File "//garage/src/garage/tf/policies/gaussian_mlp_policy.py", line 126, in _initialize
    self.model.build(state_input)
  File "//garage/src/garage/tf/models/base.py", line 202, in build
    tf.compat.v1.get_default_session().run(
AttributeError: 'NoneType' object has no attribute 'run'
```

**Comment by ryanjulian** [comment]
@JialouWang Can you post a code snippet which will lead us to this error?

**Comment by JialouWang** [comment]
```
from gym_art.quadrotor.quadrotor_modular import QuadrotorEnv
 param1 = {'hidden_sizes': [64, 64]}
 param2 = {'raw_control': True, 'tf_control': False, 'thrust_noise_ratio': 0.01, 'dim_mode': '3D'}
 env1 = TfEnv(QuadrotorEnv(**param2))
 policy1 = GaussianMLPPolicy(env1.spec,**param1)
```
This should be able to reproduce the issue

**Comment by ryanjulian** [comment]
The TensorFlow `GaussianMLPPolicy` can only be constructed from within a valid TensorFlow v1 session. This is handled for you when using the `LocalRunner` context manager to run an algorithm (see the TF [examples](https://github.com/rlworkgroup/garage/tree/master/examples/tf) for usage). If you would like to use `GaussianMLPPolicy` directly, you would need to construct and enter a TensorFlow v1 session yourself.
