### ISSUE TITLE
Some examples tests are flaky

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1147]
This causes segfaults on most builds.

* `test_ppo_memorize_digits`
* `test_trpo_cubecrash`

**Comment by lywong92** [comment]
@ryanjulian @gitanshu How can I reproduce the bug? I ran it locally on my machine, and it seems fine.

**Comment by ryanjulian** [comment]
You can run the tests several times on your machine manually and see if they fail. Make sure you use the docker container to run them. You will have to remove the flaky marker on the test definition (it skips the test).

**Comment by lywong92** [comment]
I used docker to run `test_ppo_memorize_digits` and `test_trpo_cubecrash` individually for about 10 times. I also ran the whole integration test script 5 times. I still cannot reproduce the bug. Can someone else try it out?
