### ISSUE TITLE
TensorFlow 2.x support

### ISSUE THREAD

**Issue by npowell88** [rlworkgroup/garage#1151]
Is Garage compatible with model architectures built with the new Tensorflow 2.x interface? If not are there plans to integrate?

**Comment by ryanjulian** [comment]
@npowell88 tl;dr: No support yet. No timelime for integration (other than eventually), but it probably won't be seen until the latter half of the year (maybe `v2020.06` or `v2020.10`).

This is a wishlist item, but the core developers are focusing on what we believe are more impactful enhancements (namely better support for PyTorch, meta-/multi-task RL, and better documentation). I'm also a fan of waiting a couple of point releases after a major API change for the new API to stabilize.

I think that most TF users will find that `garage.tf.Model` solves most of the paint points of TF1. We designed this interface with a transition to TF2 in mind.

We have a rapidly-growing PyTorch tree which already has hard-to-find algorithms (such as MAML and TRPO). SAC and PEARL will land there soon.

IMO, most users who consider autograph a killer feature have already fled to PyTorch. 

What's your motivation for wanting TF2? I'm curious to hear from users like you.
