### ISSUE TITLE
Use tf.name_scope() in TensorBoardOutput

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#117]
Use a name_scope in TensorBoardOutput so that tf objects created by TensorBoard do not pollute the computation graph.

**Comment by CatherineSue** [comment]
Does this happen when using record_histogram?

**Comment by ryanjulian** [comment]
Yes.

![image](https://user-images.githubusercontent.com/1376219/42108034-395ab6bc-7b8e-11e8-9fe8-18aefcd65808.png)

**Comment by ryanjulian** [comment]
![image](https://user-images.githubusercontent.com/1376219/42247988-3e8d3158-7ed8-11e8-9bf5-03125570567b.png)

This seems to have messed up the key space for calls to `logger.record_histogram()`. `logger.record_histogram_by_type()` is unaffected.

**Comment by CatherineSue** [comment]
<img width="718" alt="screen shot 2018-07-03 at 5 04 59 pm" src="https://user-images.githubusercontent.com/8605658/42250015-51c6c788-7ee3-11e8-8171-63e413a72f69.png">

```
logger.record_histogram("Embedding/samples/i_0", k_val)
logger.record_histogram("Embedding/samples/i_1", k_val)
logger.dump_tensorboard(step=i)
```
Does this look correct?
I'm not sure how you created i_0 and i_1.

**Comment by ryanjulian** [comment]
That looks correct

Code generating the plot:
```python
        # samples
        num_traj = self.batch_size // self.max_path_length
        latents = samples_data["latents"][:num_traj, 0]
        for i in range(self.policy.latent_space.flat_dim):
            logger.record_histogram("Embedding/samples/i={}".format(i),
                                    latents[:, i])
```
