### ISSUE TITLE
Version error in setup.py with atari-py

### ISSUE THREAD

**Issue by parachutel** [rlworkgroup/garage#1177]
In `setup.py`, it requires:
` 'atari-py<0.2.0'` and `'gym[atari,box2d,classic_control]' + GYM_VERSION` with `GYM_VERSION = '==0.15.4'`.

But in `gym-0.15.4` setup.py requires:
`'atari': ['atari_py~=0.2.0', 'Pillow', 'opencv-python']`

There is a version conflict for `atari-py`.

**Comment by ryanjulian** [comment]
@gitanshu is this fixed?

**Comment by gitanshu** [comment]
closed by #1194
