### ISSUE TITLE
Query about TRPO algorithm

### ISSUE THREAD

**Issue by ghx-0228** [rlworkgroup/garage#1179]
I walked through the script of TRPO, I have a question about 'LossBefore, LossAfter and dloss'

From your script, I treat LossBefore as Loss before update, and LossAfter as Loss after update.
 
But in my opinion, for each iteration, we compute the 'Loss' using the collected data and then update the policy for the next iteration. Therefore, we should compute LossAfter using the samples from the next generation.

I am confused about the LossAfter. Could you help me remove my confusion?

**Comment by krzentner** [comment]
Basically we're just logging the change in loss from that single optimization step, by logging the loss before and after (as well as `dloss` itself). If we want to compare the loss between epochs (i.e. after gathering new experience), then we just look at the next epoch's `LossBefore`. However, that value is usually very noisy.
