### ISSUE TITLE
Unify env_infos of multi- and meta-ML environment

### ISSUE THREAD

**Issue by naeioi** [rlworkgroup/garage#1198]
Multi- and meta-ML environment needs a way to report the task name of an environment step. Usually, this information is saved in the `env_infos` of an action return. Unfortunately, there is not (yet) a standard for the field (and definition) of such information. In garage, we currently use try-catch to handle different cases we have encountered so far. See https://github.com/rlworkgroup/garage/blob/a0905c23fc005d0bbdc7917210b5685e027605b2/src/garage/_functions.py#L33-L40

We better unify this interface.

**Comment by nicolengsy** [comment]
@naeioi @ryanjulian Is this still an issue? It seems to me that `task_name` and `task_id` are consistently being put in in both meta and multi envs, and the try/catches for them are no longer existing.
