### ISSUE TITLE
Metaworld examples for RL2

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1205]

**Comment by ahtsan** [comment]
Does that mean we need to make Metaworld a required dependency?

**Comment by ryanjulian** [comment]
Maybe not. We can print an error if someone tries to run an example without installing metaworld.

**Comment by ryanjulian** [comment]
i.e. we can make it optional instead

**Comment by ryanjulian** [comment]
@ahtsan is this done yet?

**Comment by ahtsan** [comment]
Just merged
