### ISSUE TITLE
Change shape of Independent object in Gaussian MLP Module

### ISSUE THREAD

**Issue by yonghyuc** [rlworkgroup/garage#1229]
Currently, the log likelihood from the GaussianMLPModule is single value that sum every log likelihood from each observation and action. However, for PPO and VPG, each individual log likelihood value is needed to calculate advantage value.

This is shape of log likelihood that we need for PPO and VPG

![image (1)](https://user-images.githubusercontent.com/43084978/76919035-f4c8e600-6884-11ea-8e0e-0f93a9847925.png)

But currently, the output of log likelihood is single value.

![image](https://user-images.githubusercontent.com/43084978/76919044-f98d9a00-6884-11ea-9468-eae57478b40b.png)

**Comment by ryanjulian** [comment]
It seems to me this could be a mix-up of how batches/broadcasting is handled?

If I send a batch of samples to log_prob I should get a batch of LLs. This should apply not just to LL, but any other feedforward properties of the policy (e.g. entropy)

**Comment by avnishn** [comment]
Closed by #1235
