### ISSUE TITLE
Remove enclosing_scope and use tf.name_scope()

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#123]
The feature we attempted to implement with enclosing_scope() is properly implemented with the utility tf.name_scope(). Furthermore, enclosing_scope() is implemented with tf.variable_scope(), which can actually create unexpected side effects when defining neural networks (i.e. it makes every primitive and function call have its own set of variables, but in reality we often want shared variables).

**Comment by ryanjulian** [comment]
See branch no_enclosing for a start on this PR

**Comment by gonzaiva** [comment]
Working on it.

**Comment by gonzaiva** [comment]
Closed with #194
