### ISSUE TITLE
Installing garage in conda fails due to MPI linker errors

### ISSUE THREAD

**Issue by gitanshu** [rlworkgroup/garage#1230]
e.g. https://travis-ci.com/github/rlworkgroup/garage/jobs/296858607

Related issue of mpi4py's issue tracker: https://bitbucket.org/mpi4py/mpi4py/issues/143/build-failure-with-python-installed-from

Copy of #1200

**Comment by krzentner** [comment]
Gitanshu discovered the easiest way to fix this is to update baselines, which should only require a few API updates in benchmark tests.

**Comment by krzentner** [comment]
This is fixed in master, but very difficult to backport. I think the right solution is just to say that `garage[dev]` for the 2019.10 release cannot be installed in conda. If you want that, manually install the garage dev dependencies besides baselines (which is what's causing us to install mpi).
