### ISSUE TITLE
Investigate tests in test_examples.py

### ISSUE THREAD

**Issue by lywong92** [rlworkgroup/garage#1240]
Several tests marked as flaky in `tests/integration_tests/test_examples.py` are showing `OSError: [Errno 12] Cannot allocate memory` when running Normal tests through Travis CI.

**Comment by avnishn** [comment]
@lywong92 can you include a link to a travis build where this happened?

**Comment by lywong92** [comment]
https://travis-ci.com/github/rlworkgroup/garage/jobs/300487437
