### ISSUE TITLE
deterministic.set_seed does not guarantee full determinism in TensorFlow

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#1260]
Determinism in TensorFlow depends on two seeds: Graph seed and op seed. Currently `deterministic.set_seed()` only set the graph seed, which makes the random sequences generated by all ops be repeatable across sessions, but not when sequences of ops changed.

Setting both graph_seed and op_seed will guarantee full determinism, i.e. calling 
[https://www.tensorflow.org/api_docs/python/tf/compat/v1/set_random_seed](set_random_seed) and applying a seed when calling any tf.ops (e.g. `tf.random.uniform([1], seed=1`).

**Comment by ryanjulian** [comment]
@ahtsan can you estimate how big a change we would need to fix this?

**Comment by ahtsan** [comment]
Basically providing a seed to all tf.op -- shouldn't take long
