### ISSUE TITLE
Beta distribution policies

### ISSUE THREAD

**Issue by eric-heiden** [rlworkgroup/garage#128]
The current Gaussian policies don't adhere to the action space limits (Normal distribution samples are in [-inf, inf]). The [Beta distribution](https://www.ri.cmu.edu/wp-content/uploads/2017/06/thesis-Chou.pdf) is bounded in [0,1], so it can be easily scaled to match the action limits and makes policies applicable to the real robot without clipping or other tricks (that mess up the training).

**Comment by ryanjulian** [comment]
http://proceedings.mlr.press/v70/chou17a/chou17a.pdf
