### ISSUE TITLE
Batch size stuck on a large number

### ISSUE THREAD

**Issue by C-monC** [rlworkgroup/garage#1295]
Hello,
I have made a custom env to train a 2 finger gripper. The env has an observation image that is single channel. I've flattened the observation array to (84480) from (352,240).

The error: `MemoryError: Unable to allocate 315. GiB for an array with shape (10000, 100, 84480) and data type float32`. The RL algorithm I am trying is tf_ddpg_pendulum. I still get that error even with ` runner.train(n_epochs=1, batch_size=1)`.

Should the env return the batch size or where else could it be defined? 

Thanks for reading,
Simon

**Comment by krzentner** [comment]
Hello Simon,
The above error probably comes from allocating the replay buffer for your environment. The size of the replay buffer isn't affected by the batch size. The first two numbers come from the arguments you've passed to your replay buffer (probably `SimpleReplayBuffer`). Specifically, the `size_in_transitions` parameter determines the total memory usage of the buffer. If you decrease that parameter enough, your memory issue should go away.

It's worth noting that the replay buffer allocates memory lazily, so the `MemoryError` will only occur once the algorithm starts filling the buffer. I'm going to close this issue, but feel free to continue messaging if the fix above doesn't work.

Cheers,
K.R.

**Comment by C-monC** [comment]
Hi Krzentner,
Thanks for the help that worked and it is training now. Can I just ask how do you evaluate the model after training? The only resource I could find that tests after training is the Jupyter Notebook but no where do they open a model file.

I'll make a new issue if this isn't a quick thing to do.
