### ISSUE TITLE
ImportError: cannot import name 'TRPO' from 'garage.torch.algos

### ISSUE THREAD

**Issue by deepakraina99** [rlworkgroup/garage#1301]
Why I am getting this error with TRPO? Though I am able to import DDPG.
ImportError: cannot import name 'TRPO' from 'garage.torch.algos

**Comment by krzentner** [comment]
Are you installing garage from latest release or from the git repo's master branch? The pytorch TRPO implementation was added after our last release, so that may be why you can't import it.

**Comment by deepakraina99** [comment]
I am installing using _pip install garage_. Should I install using git repo?

**Comment by ryanjulian** [comment]
@deepakraina99 you can install the latest pre-release with `pip install garage==2020.2.0rc2` which should include TRPO on PyTorch.

We are putting finishing touches on 2020.04 and should release it this week. It will - include everything you see in the repo.

**Comment by ryanjulian** [comment]
@deepakraina99 I'm closing this issue for now. Let us know if you have more questions or issues by re-opening or opening a new issue.
