### ISSUE TITLE
pixel observation with continuous action space

### ISSUE THREAD

**Issue by C-monC** [rlworkgroup/garage#1302]
Hello,
Is there anyway to attach a CNN on top of one of the algorithms that work with continuous action spaces? 

My gym environment has an observation space that is a single channel image and the action space is 3 continuous values. 

Is the only option to discretise the action space?

Thanks for reading,
Simon

**Comment by ahtsan** [comment]
Hi Simon! Thank you for your interest in using Garage.

Indeed we are currently working on adding CNN support for one of the algorithms that support continuous action space -- DDPG. Before the patch is done, discretizing the action space would be a good way to do that. @ryanjulian @krzentner Do you have anything to add?

**Comment by ryanjulian** [comment]
@C-monC is there a particular algorithm you're interested in using CNNs with? Are you interested in PyTorch or TensorFlow support in particular?

If you are interested in taking this on, it should not be a very large PR. Essentially, you'd need to add ContinuousCNNQFunction (very similar to current Q-functions) and ensure that it works correctly with algorithms supporting continuous action spaces.

**Comment by C-monC** [comment]
Hi @ryanjulian and @ahtsan,

Thanks for the quick replies. In the mean time I've found stable baselines to work quite well as they already support CNN policies.

It's for my final year mech engineering project. The plan is to compare several agents like PPO, DDPG and HER on a pybullet gripper environment and then a real gripper. I've only just setup my env and starting training with the stable baselines package.

I've never contributed to github project before but I'd like to give it a shot. After this coming Monday (progress report due) I'll submit a pull request.
