### ISSUE TITLE
How to save and load the Tensorflow models/Policy trained with the garage?

### ISSUE THREAD

**Issue by mdalvi** [rlworkgroup/garage#1308]
How to save and load the TensorFlow models/Policy trained with the garage?

I could see an example to resume_training [here](https://github.com/rlworkgroup/garage/blob/master/examples/resume_training.py) but I more interested to persist the model itself and later use it outside environment in non-simulation/production settings!

**Comment by ryanjulian** [comment]
Hi @mdalvi, thanks for trying out garage!

Models and other data are saved in the experiment directory, typically in `./data/local` where `.` is the working directory you execute your launcher script or example from.

The models are saved `.pkl` files, which should be loadable from the same python environment you ran training in.

See examples which load pre-trained models:
https://github.com/rlworkgroup/garage/blob/master/examples/resume_training.py
https://github.com/rlworkgroup/garage/blob/master/examples/sim_policy.py

**Comment by ryanjulian** [comment]
I'm closing this issue for now. Feel free to re-open or open another one later.
