### ISSUE TITLE
How to resume training 'Pearl'?

### ISSUE THREAD

**Issue by HyeongYeolRyu** [rlworkgroup/garage#1314]
Hello! I ran a example code: examples/torch/pearl_ml1_push.py and got a log data.
Then I wrote a resume code like this:
```
def` resume_task(snapshot_config, *_):
    runner = LocalRunner(snapshot_config=snapshot_config)
    runner.restore(from_dir='dir')
    runner.resume()

run_experiment(
    resume_task,
    log_dir='dir',
    snapshot_mode='last',
    seed=1,
)
```

but this doesn't work. The errors are the following:
![image](https://user-images.githubusercontent.com/36123202/79548676-bff0be80-80d0-11ea-8c2e-a655dc8b461d.png)

How can I fix this problem?

**Comment by ryanjulian** [comment]
@HyeongYeolRyu thanks for trying garage!

@lywong92 @naeioi  can you take a look here?

**Comment by naeioi** [comment]
@HyeongYeolRyu Thanks for your report. I checked and found that Pearl does not properly implement resuming. I will make a fix, hopefully by the end of today.
