### ISSUE TITLE
Reproducing MetaWorld Results

### ISSUE THREAD

**Issue by sonajeswani** [rlworkgroup/garage#1333]
Hello! We are currently working on reproducing the RL2 ML1 PickPlace results shown in Figure 7 of the [MetaWorld paper](https://arxiv.org/pdf/1910.10897.pdf). We are using the hyperparameters given in table E.9.

We are using this garage [RL2 script](https://github.com/rlworkgroup/garage/blob/master/examples/tf/rl2_ppo_ml1.py) that was committed a few weeks ago, but we are not getting the same results as the paper. We did the following:

1. Changed push-v1 to pick-place-v1
2. Changed GaussianGRUPolicy to GaussianLSTMPolicy
3. Increased n_epochs
4. Changed the meta_batch_size, policy entropy coefficient, etc. according to the hyper parameters given by the paper.

A few weeks ago, we also tried running the ML1 experiments using the ProMP repo, but still were not able to reproduce the paper’s results. We are getting the results below:
![image](https://user-images.githubusercontent.com/15059219/79910450-9c30bf80-83d3-11ea-891d-75756d379453.png)

Is there something we are missing? We have spent a while on this and would really appreciate any help! It would be great is @ahtsan could weigh in too, since he committed the scripts. I'm also tagging @zhanpenghe, one of the authors of MetaWorld.

Thank you!

**Comment by ryanjulian** [comment]
@ahtsan can help here

**Comment by ryanjulian** [comment]
@ahtsan it's not valid to set `random_init=True` on ML1 -- the benchmark specifically specifies `random_init=False` for ML1 ([here](https://github.com/rlworkgroup/metaworld/blob/master/metaworld/benchmarks/ml1.py#L20)). That is, if you set `random_init=True`, you aren't running ML1, and shouldn't report your results at ML1 results.

@sonajeswani I wouldn't focus on the AverageReturn metric, which isn't very meaningful in MTRL anyway. The most important metric is SuccessRate, and we're able to reproduce the MetaWorld SuccessRate results (e.g. Fig. 4).

Please email me at my USC address and I can provide additional details.

Note that I believe that there's a typo in Fig. 8 plots for environment samples, and you may need to run RL2 out to 120M samples to get to near 50% success rate on ML10 and 35% on ML45.

**Comment by sonajeswani** [comment]
Thanks for the information -- I sent you an email! If possible though, it would be great to post the information required to reproduce figure 8 here for anyone else trying to reproduce the results.

**Comment by abdulhaim** [comment]
Hi @sonajeswani, were you eventually able to reproduce results for ML1? What parameters did you use? 

@ryanjulian I'm having trouble reproducing SAC results in Figure 6, did you achieve these results with random_init as True or False?

**Comment by ryanjulian** [comment]
@abdulhaim Figure 6 always uses a fixed configuration. We for SAC we used [softlearning](https://github.com/rail-berkeley/softlearning)

We recently changed the API and eliminated `random_init` to make it much easier for you to control when the environment configuration changes. Please take a look at the README for more info. The results from Figure 6 would correspond to calling `set_task` only once.
