### ISSUE TITLE
Move population of replay buffer out of OffPolicyVectorizedSampler

### ISSUE THREAD

**Issue by krzentner** [rlworkgroup/garage#1336]

**Comment by ryanjulian** [comment]
@krzentner What do you think of moving this into workers?

**Comment by maliesa96** [comment]
@ryanjulian @krzentner so what's the verdict here? Move this into `VecWorker`?

**Comment by ryanjulian** [comment]
my comment was a much larger proposal (the workers have access to ReplayBuffer and add to it directly). Probably not in-scope for this issue. For now, it would be an improvement to just move replay buffer population into the algorithms themselves.

**Comment by maliesa96** [comment]
closed via #1353
