### ISSUE TITLE
Testing RL2 takes too long

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1346]
10 of the 36-38 minutes it takes to run the MuJoCo test job are spent testing RL2. This hardly seems necessary to unit-test the algorithm.

Please find a way to test RL2 without spending 10 minutes.

See test log https://travis-ci.com/github/rlworkgroup/garage/jobs/322798959#L1723

**Comment by ahtsan** [comment]
Can we just not test ML10 on RL2? If so I will remove that.

**Comment by ryanjulian** [comment]
I think that's fine, as long as it doesn't drop your coverage. There is a tested example, right?
