### ISSUE TITLE
Unfortunate defaultes in click.command() in pearl_ml10.py, pearl_ml45.py

### ISSUE THREAD

**Issue by bordeauxred** [rlworkgroup/garage#1364]
Hi there, 

the line @click.option('--num_train_tasks', default=50) in the examples  pearl_ml10.py and pearl_ml45.py causes in env_sampler.sample(num_train_tasks) a value error (compare line 196 in task_sampler.py) and should be instead adapted to the number of train tasks.

**Comment by ryanjulian** [comment]
hi @bordeauxred 

Thanks for the bug report!

@naeioi can you take a look and confirm this bug?

**Comment by ryanjulian** [comment]
Verified with `make run-headless RUN_CMD="python examples/torch/pearl_ml10.py"`

@krzentner what is the right fix here?
