### ISSUE TITLE
HalfCheetahMetaEnv doesn't pickle task correctly

### ISSUE THREAD

**Issue by RicardoLunaG** [rlworkgroup/garage#1375]
Hi there,

I'm trainning a GaussianMLPPolicy with PPO using LinearFeatureBaseline as Baseline, in the HalfCheetahVelEnv environment. In the final epoch of trainning I get:

Evaluation/AverageReturn: -45.9052
Evaluation/CompletionRate: 1
Evaluation/Iteration: 1014
Evaluation/MaxReturn: -44.1065
Evaluation/MinReturn : -48.0772
Evaluation/NumTrajs: 12
Evaluation/StdReturn: 1.31797
Extras/EpisodeRewardMean: -45.6498

However, if I use the trained policy to evaluate the model in the task by calling policy.get_action(obs) as shown in https://github.com/rlworkgroup/garage/blob/master/examples/jupyter/trpo_gym_tf_cartpole.ipynb I get an episodic average return of -246.58. Do you have any idea of what could be happening?

**Comment by krzentner** [comment]
Hi Ricardo,

The `HalfCheetahVelEnv` is actually a meta-learning environment, where the target velocity is randomly selected. It's quite likely that the target velocity you trained PPO on is different than the target velocity you evaluated it on, which usually results on very low reward. If you want to solve `HalfCheetahVelEnv`, I'd recommend using a meta-learning algorithm such as `garage.tf.algos.RL2PPO` or `garage.torch.algos.MAMLTRPO` (MAMLPPO doesn't work as well).

If you just want to measure how well PPO works, I'd recommend using a single-task environment, such as `gym.envs.mujoco.HalfCheetahEnv`.

Does that answer your question?

**Comment by RicardoLunaG** [comment]
Hi krzentner,

Thanks for your answer. If I initialize the environment with {'velocity': 1.} and I use the same for the evaluation, the target velocity would be the same on both task, isn't it? Or does it randomly changes after each reset?

**Comment by RicardoLunaG** [comment]
Hi, 

I think I have found the issue, for some reason even if you specify the task `{velocity : 1.}` in the initialization of the HalfCheetahVelEnv enviroment, the target velocity gets set to 0 when the sampler creates the workers by `envs = [pickle.loads(pickle.dumps(self.env)) for _ in range(n_envs)]`, so the trainning target velocity is always 0.

**Comment by krzentner** [comment]
That definitely sounds like a bug in `HalfCheetahVelEnv`'s pickling logic. Thanks for finding it. I'll look into fixing it.
