### ISSUE TITLE
off policy evaluation needs an option to set the number of evaluation samples collected per evaluation trajectory

### ISSUE THREAD

**Issue by avnishn** [rlworkgroup/garage#1381]
Currently, the function `_obtain_evaluation_samples` does not take as a parameter the number of evaluation samples that need to be collected per trajectory. Instead evaluation trajectories are of length `algo.max_path_length`. This is bad because SOTA algorithms don't always use the the algorithm's max path length to determine the number of evaluation samples that need to be collected.

**Comment by ryanjulian** [comment]
This is not a bug. It's invalid to train on on max_path_length, then evaluate on a different max_path_length. Those are two different MDPs.

It's also impossible to calculate a true return without a full trajectory (i.e. it either has a terminal or max_path_length), so it's not possible for the API to accept a precise number of time steps to use for evaluation.

**Comment by avnishn** [comment]
Closed by #1384
