### ISSUE TITLE
Skip the test_pearl_ml45 due to the out of the memory

### ISSUE THREAD

**Issue by yonghyuc** [rlworkgroup/garage#1390]
Due to the out of the memory error (return code -9) skip the testcase `test_pearl_ml45` in the `test_example.py`

**Comment by yonghyuc** [comment]
![image](https://user-images.githubusercontent.com/43084978/81191210-9effe880-8f6d-11ea-9e0d-4e26811c67f1.png)

**Comment by ryanjulian** [comment]
I don't see this problem in the CI, so I'm closing it for now.
