### ISSUE TITLE
Cannot install garage on Windows 10

### ISSUE THREAD

**Issue by cversteeg** [rlworkgroup/garage#1427]
I am trying to run some of the sample code to get a handle on another project, and I am encountering issues where at least one of the dependencies (ray, in my case) is not compatible with windows. Are there any workarounds or plans to get Windows compatibility in the future?

**Comment by ryanjulian** [comment]
Hi @cversteeg 

As noted in the README, we don't officially support Windows (i.e. we don't test it) and as you have found, it's very likely there are some dependencies which don't even run on Windows.

Your best-supported options for running on Windows are Docker (see the dockerfiles in docker/) and WSL (which we've received reports that WSL works just fine).

We don't have any plans to spend a lot of time on Windows compatibility (either natively or with WSL), but we welcome pull requests adding fixes, setup scripts, and test support for Win10 and/or WSL.

**Comment by cversteeg** [comment]
Good to know! Definitely a sensible choice, given how many packages are available linux only.
Just a note, the reason I asked was because I was unable to find any explicit mention of OS compatibility in the readme. Perhaps it can be added.

**Comment by ryanjulian** [comment]
Ah, thanks for reporting that! We used to have a section on platform support, and it accidentally got deleted when the README was rewritten.
