### ISSUE TITLE
Error when running the headless docker image

### ISSUE THREAD

**Issue by stwerner97** [rlworkgroup/garage#1434]
I am trying to run a minimial garage example using your headless docker image on a fresh Ubuntu 18.04 installation, however encountered some issues. First, I followed the provided instructions and successfully built the headless image. Subsequently running `docker run -it --rm rlworkgroup/garage-headless python examples/tf/trpo_cartpole.py`  gives me the following error: `W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).` Any ideas what might cause the issue? Thanks in advance!

**Comment by ryanjulian** [comment]
Hi @stwerner97 -- thanks for trying garage!

This message is from pulseaudio (audio subsystem) running inside the headless container, and can be safely ignored. It's unrelated to any success/failure you might be encountering.

We recommend you use the `Makefile` to run the docker containers. You can type `make` inside the repository to see brief documentation, or read `docker/README.md` and the `Makefile` itself for a more extended guide.

Let us know if you have any more trouble or questions.
