### ISSUE TITLE
Setup doctests

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1439]
This will help keep the documentation up-to-date

**Comment by ryanjulian** [comment]
This should apply to both docstrings and sphinx. I believe there's a sphinx plugin for doctests.

**Comment by ziyiwu9494** [comment]
@ryanjulian Do you know which files have testable docstrings and sphinx docs?

**Comment by ryanjulian** [comment]
Hmm no I'm not sure -- it might be best to create some examples for yourself for easy testing.

I think LocalRunner has some examples in its docstrings.

In sphinx, i think the `Running Experiments` guide has some examples.
