### ISSUE TITLE
Don't double check pre-commits in the CI

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#144]
Some pre-commit checks are also standalone CI checks. We shouldn't check them twice.

We can either
* Remove the individual scripts and use pre-commit for duplicative checks (preferred, if it works for all cases)
* Turn off the duplicative checks when we use pre-commit

**Comment by ryanjulian** [comment]
Also, it looks to me like the check_precommit script should be using the `--source` and `--origin` args, as documented here https://pre-commit.com/#pre-commit-run

**Comment by ryanjulian** [comment]
Why have more code when you can have less?

**Comment by jonashen** [comment]
It will take me more time to learn how to write the less code :(
