### ISSUE TITLE
Failed building wheel for dm-tree

### ISSUE THREAD

**Issue by haydenshively** [rlworkgroup/garage#1442]
Installing garage dependencies into a fresh conda environment (Python 3.8) via `pip install --no-cache -e ."[mujoco,dm_control]"` yields the following errors related to dm-tree. These may or may not be specific to my computer/macOS, but they are reproducible in every fresh conda env that I make. If instead I try to install from PyPI (`pip install --no-cache -e garage"[mujoco,dm_control]"`), it says `Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI` since dm_control is from deepmind's repo.

> ERROR: Command errored out with exit status 1:
   command: /Users/haydenshively/anaconda3/envs/Garage/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hz/1l2dtvyj4dv35mys1v9y2nd40000gn/T/pip-install-mk32dmoe/dm-tree/setup.py'"'"'; __file__='"'"'/private/var/folders/hz/1l2dtvyj4dv35mys1v9y2nd40000gn/T/pip-install-mk32dmoe/dm-tree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/hz/1l2dtvyj4dv35mys1v9y2nd40000gn/T/pip-wheel-5hwif72_
       cwd: /private/var/folders/hz/1l2dtvyj4dv35mys1v9y2nd40000gn/T/pip-install-mk32dmoe/dm-tree/
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/tree
  copying tree/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/tree
  copying tree/tree_test.py -> build/lib.macosx-10.9-x86_64-3.8/tree
  copying tree/tree_benchmark.py -> build/lib.macosx-10.9-x86_64-3.8/tree
  running build_ext
  bazel build //tree:_tree --symlink_prefix=build/temp.macosx-10.9-x86_64-3.8/bazel- --compilation_mode=opt
  unable to execute 'bazel': No such file or directory
  error: command 'bazel' failed with exit status 1
-----
>ERROR: Command errored out with exit status 1:
     command: /Users/haydenshively/anaconda3/envs/Garage/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hz/1l2dtvyj4dv35mys1v9y2nd40000gn/T/pip-install-mk32dmoe/dm-tree/setup.py'"'"'; __file__='"'"'/private/var/folders/hz/1l2dtvyj4dv35mys1v9y2nd40000gn/T/pip-install-mk32dmoe/dm-tree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hz/1l2dtvyj4dv35mys1v9y2nd40000gn/T/pip-record-bgk0rzmx/install-record.txt --single-version-externally-managed --compile --install-headers /Users/haydenshively/anaconda3/envs/Garage/include/python3.8/dm-tree
         cwd: /private/var/folders/hz/1l2dtvyj4dv35mys1v9y2nd40000gn/T/pip-install-mk32dmoe/dm-tree/
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/tree
    copying tree/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/tree
    copying tree/tree_test.py -> build/lib.macosx-10.9-x86_64-3.8/tree
    copying tree/tree_benchmark.py -> build/lib.macosx-10.9-x86_64-3.8/tree
    running build_ext
    bazel build //tree:_tree --symlink_prefix=build/temp.macosx-10.9-x86_64-3.8/bazel- --compilation_mode=opt
    unable to execute 'bazel': No such file or directory
    error: command 'bazel' failed with exit status 1

**Comment by haydenshively** [comment]
It seems that dm-tree is not compatible with Python 3.8: https://github.com/deepmind/dm_control/issues/135
We should probably specify compatible Python versions in the installation instructions.

**Comment by ryanjulian** [comment]
Great catch! The best way for us to specify this is to updated setup.py

In particular, you'll want `python_requires='>=3.5,<3.8`

why don't you give it a shot?

**Comment by ryanjulian** [comment]
(you should also leave a comment explaining 3.8 is unsupported, with a link to the issue you found)

**Comment by gitanshu** [comment]
The issue is that compiling dm-tree from source requires installing bazel. So it's not that we are not compatible with python 3.8, but that on 3.8, we have an extra system dependency. Do you think we should still restrict our supported range of python versions for that?

**Comment by haydenshively** [comment]
I’m happy to modify the setup.py either way. It’s be great to support 3.8 by adding the bazel dependency, but on the other hand we already have a lot of dependencies, and the bazel binary is rather large (~120mb). Let me know which way to go.

**Comment by ryanjulian** [comment]
The root of the problem is not bazel, but DeepMind failing to upload a pre-compiled wheel for Python 3.8 to PyPI, causing pip to revert to trying to compile some native extensions from source code (which requires bazel).

We should probably just wait for them to upload the wheel.

Until then, we should at least properly declare that not all configurations support Python 3.8.

**Comment by ryanjulian** [comment]
This should be fixed -- check again?

**Comment by haydenshively** [comment]
Yep. Looks like it's working now

**Comment by Asriel31** [comment]
Not for me despite I'm using anaconda3-2019.03 Python 3.7.3
I've performed conda install -c conda-forge dm-tree 

Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/tree
  copying tree/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/tree
  copying tree/tree_test.py -> build/lib.macosx-10.9-x86_64-3.7/tree
  copying tree/tree_benchmark.py -> build/lib.macosx-10.9-x86_64-3.7/tree
  running build_ext
  bazel build //tree:_tree --symlink_prefix=build/temp.macosx-10.9-x86_64-3.7/bazel- --compilation_mode=opt
  unable to execute 'bazel': No such file or directory
  error: command 'bazel' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for dm-tree

Another thing that I don't understand my macosx version is 10.13.6 x86_64 High Sierra and here above the build is performed toward macosx 10.9 x86_64

**Comment by xwy0303** [comment]
Hello. I have the same problem with you, but The version of python on my computer is 3.6. Do you know why? Thanks!
![image](https://github.com/rlworkgroup/garage/assets/143583396/db8e73a8-acf6-4d3a-a341-a061e7016521)

**Comment by mi-heinsch** [comment]
Hey, I have the same issue with Python 3.6.9.. Anyone has a fix already?

**Comment by aymen5507** [comment]
any update?

**Comment by shikharmittal04** [comment]
Same issue here. I have Python 3.6.8

**Comment by rauki34** [comment]
oh,damn. same problem in 3.12 when I use pip install keras. Where is the solution?

**Comment by shikharmittal04** [comment]
Upgrading to Python 3.11.5 solved the problem for me.

**Comment by rauki34** [comment]
> Upgrading to Python 3.11.5 solved the problem for me.

success right now amazingly while I still do not know what problem it happened.
