### ISSUE TITLE
Regressor should pass model to optimizer instead of self

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#1452]
Passing self is error-prone -- there's a high chance when calling `self.get_params()`, it will include irrelvant tensors, while only tensors inside it's model should be included.
This could be done after `garage.tf.model` get merged with `garage.tf.module`.

**Comment by ahtsan** [comment]
Example: 
https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/regressors/gaussian_mlp_regressor.py#L190

**Comment by ryanjulian** [comment]
Great catch -- probably the best way to deal with this is to just eliminate regressors and make the Baselines into ValueFunctions (i.e. algo is responsible for optimization).

ref: #1004

**Comment by ryanjulian** [comment]
I think this will be handled by the ValueFunction refactor, so I'm going to close it
