### ISSUE TITLE
Pipenv install broken on pipenv v2020.5.28

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1453]
This broke the CI

**Comment by ryanjulian** [comment]
Not clear that #1423 is the root cause, because 2019.10 is also broken in a similar way https://travis-ci.com/github/rlworkgroup/garage/jobs/340842638

**Comment by gitanshu** [comment]
Pipenv cut a new final release finally. That broke it :laughing: Will investigate the cause tomorrow

**Comment by gitanshu** [comment]
#1458

**Comment by gitanshu** [comment]
Closed by #1460
