### ISSUE TITLE
tar --auto-compress flag doesn't work on MacOS

### ISSUE THREAD

**Issue by AiRuiChen** [rlworkgroup/garage#1455]
I get a `tar option not found error` when running examples calling experiment.py on MacOS:
`python garage/examples/tf/trpo_cartpole.py`
`tar: Option --auto-compress is not supported`

Found that linux has `tar` as `gnu tar`, whereas MacOS has `tar` as `bsdtar`, which by default doesn't support `--auto-compress`. 

Suggested fixes [here](https://github.com/rlworkgroup/garage/blob/master/src/garage/experiment/experiment.py#L728):
1: Add MacOS `gtar` dependency to install `gnu tar` for Mac users, and change `tar` to `gtar` if os is MacOS in code.
2: Remove `--auto-compress` if os is MacOS. Caveat: this can result in files compressed in different ways across linux and MacOS.

**Comment by ryanjulian** [comment]
Rather than using `--auto-compress`, can we just force `xz` compression in all cases? I think this just chooses based on the file extension for convenience.

**Comment by AiRuiChen** [comment]
> Rather than using `--auto-compress`, can we just force `xz` compression in all cases? I think this just chooses based on the file extension for convenience.
> 
> Alternatively, calling subprocess is kind of hacky and exposes us to underlying OS deps (as this shows). Can we use zipfile or shutil? @krzentner is there a reason you didn't use the stdlib versions here?
> 
> See:
> https://docs.python.org/3.5/library/shutil.html#shutil.make_archive
> https://docs.python.org/3.5/library/archiving.html

I agree that avoiding subprocess call is a good practice. If we decide to switch I can take over and create a PR.

**Comment by ryanjulian** [comment]
Do what you think is best! The big risk of using stdlib is avoiding loading all the files into memory (they could be huge). Otherwise, it would be better not to be calling out to subprocess.
