### ISSUE TITLE
Recurrent policies should accept multiple layers for hidden sizes

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#1457]
Currently, it only supports single layer. Example: https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/models/gaussian_gru_model.py#L63

**Comment by ryanjulian** [comment]
Somebody already filed this #709 :P

**Comment by ahtsan** [comment]
How did you find it out lol

**Comment by ahtsan** [comment]
I filed it a year ago, and I forgot about it
