### ISSUE TITLE
 No module named 'garage.logger'

### ISSUE THREAD

**Issue by jy-cds** [rlworkgroup/garage#1506]
Hello，

After installing garage and also cloning the repository, I opened up the "trpo_gym_tf_cartpole" Jupyter notebook from the example folder but when I execute the first cell, it gives an error that says: No module named 'garage.logger'. I am not sure why this is happening as the garage seemed to be installed correctly. 

Thanks in advance!

**Comment by ryanjulian** [comment]
Hi @jy-cds 

Thanks for trying garage! This appears to be a bug. The `garage.logger` modules were moved to the `dowel` pip package. You should be able to work around the problem by installing `dowel` and changing imports to `dowel` instead of `garage.logger`
