### ISSUE TITLE
A bug in Dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [rlworkgroup/garage#1507]
https://github.com/rlworkgroup/garage/blob/968bb199ef1d0d44f5105cdc5202cecec79d60b9/docker/Dockerfile.base.16.04#L56
Hi, we are developing a tool to detect typos/bugs in dockerfiles automatically. Our tool finds a potential bug above. Is it a bug? The "-v" option is for displaying the apt-get command version and the "-V" option is for the package verbose-versions. We believe you want to use the latter one. Our tool is currently available here https://wangluochao902.github.io/clcheck/

**Comment by ryanjulian** [comment]
@gitanshu since you are rewriting anyway, can you fix this?

**Comment by gitanshu** [comment]
Yes. I haven't tried with the 16.04 image but turns out 18.04 docker image doesn't ship with libglfw*. So I'll just remove that line in #1424.

**Comment by gitanshu** [comment]
closed by #1424
