### ISSUE TITLE
Kernels restarting on specific environments

### ISSUE THREAD

**Issue by cversteeg** [rlworkgroup/garage#1508]
Thanks for updating this package; very useful!
I am encountering an issue where many of the environments cause my kernel to crash. I am able to run mountain-car and cartpole without issues, but the inverted pendulums and any mujoco models cause my kernel to crash without any indication of the cause. 

Specifically, this line causes it to crash
        env = TfEnv(gym.make('InvertedDoublePendulum-v2'))
while this does not.
        env = TfEnv(env_name='MountainCarContinuous-v0')

Any advice would be appreciated.
Thanks!

**Comment by cversteeg** [comment]
Ok, update; running the script inside of the terminal gives some more information. 

 ERROR: Invalid text in activation key

I assume that the mujoco activation key is incorrect, which is causing it to fail silently. I followed the installation instructions and included the path to my key in the installation step. Any way to check to see why this is failing?

Thanks!

**Comment by ryanjulian** [comment]
@cversteeg I should note that Jupyter/colab are not officially-supported environments (i.e. we don't test them in the CI) so any support for those will be best-effort.

in this case it's likely that you're missing a license key for MuJoCo, which is required to run those environments.

**Comment by ryanjulian** [comment]
You can start by verifying that your mujoco key is present and uncorrupted at `~/.mujoco/mjkey.txt` after the installation but before you try to run an experiment

**Comment by cversteeg** [comment]
Yep! 

The issue was that I made a placeholder mujoco key to just get the basics working while I waited for the license file from Mujoco. The setup apparently didn't overwrite that file when I went back to reinstall the mujoco portion.

Thanks so much for the prompt response!

**Comment by ryanjulian** [comment]
You're welcome!
