### ISSUE TITLE
log_std in agent info is wrong

### ISSUE THREAD

**Issue by naeioi** [rlworkgroup/garage#1509]
After the tfp patch, log_std in agent info is actually standard deviation, but not the logarithm of it.

**Comment by ryanjulian** [comment]
You're saying it's std, not log_std?

**Comment by naeioi** [comment]
@ryanjulian Yes.

**Comment by ahtsan** [comment]
agent_info is probably not needed as we moved towards TFP?

**Comment by naeioi** [comment]
https://github.com/rlworkgroup/garage/blob/a75ce18aabee2f97c65973dbbdf6ee3047f1f97a/src/garage/tf/policies/gaussian_mlp_policy.py#L192

The `log_std` is returned by `self._f_dist`, which is 
https://github.com/rlworkgroup/garage/blob/a75ce18aabee2f97c65973dbbdf6ee3047f1f97a/src/garage/tf/policies/gaussian_mlp_policy.py#L155-L158

**Comment by naeioi** [comment]
@ahtsan I agree. The only use case of agent info should be debugging. I am using it in TE to visualize embedding distribution.

**Comment by ahtsan** [comment]
Before introducing TFP, agent_info basically represents a distribution and garage.distribution uses these dicts when calculating things like log likelihood. However, with TFP, agent_infos are no longer needed.
