### ISSUE TITLE
Remove agent_info

### ISSUE THREAD

**Issue by naeioi** [rlworkgroup/garage#1512]
See https://github.com/rlworkgroup/garage/issues/1509#issuecomment-638504144

**Comment by ryanjulian** [comment]
I am not convinced by this until I see performance numbers for image-based environments.

A convenient (but unapplied, right now) optimization for RL is to store the log_std of your actions during sampling, then use those saved log_stds for backprop during optimization.

This allows you to avoid a forward-pass through a potentially-large network to calculate the loss on your actions.

**Comment by naeioi** [comment]
The strategy you mentioned can be implemented in the algorithm that uses it. 

`agent_info` as a universally available data provided by `policy.get_action()` adds overhead but is no longer used anywhere.

**Comment by ryanjulian** [comment]
...but how could the algorithm use it unless `policy.get_action()` returns log_std?
