### ISSUE TITLE
Possible Bug in garage/envs/base.py, unexpected attribute is_image

### ISSUE THREAD

**Issue by JeremyAlain** [rlworkgroup/garage#1525]
I am using version 2020.4rc1
I follow more or lesse this tutorial https://github.com/rlworkgroup/garage/blob/master/examples/tf/vpg_cartpole.py

When I execute
```environment = GarageEnv(env_name="CartPole-v1")```  I get the following error:

TypeError: from_gym() got an unexpected keyword argument 'is_image'

I am not sure If I am doing something wrong or if this is an issue. When I track down the stacktrace 
i get to the file /garage/envs/base.py and on line 62 I replace 
```
self.observation_space = akro.from_gym(self.env.observation_space,
                                               is_image=is_image)
```

with
 ```
self.observation_space = akro.from_gym(self.env.observation_space)
```
and this at least SEEMS to fix the issue, as the function from_gym has no attribute is_image. But I am not sure if it changes anything in the logic.

**Comment by maliesa96** [comment]
Hi,

This error usually comes up when the version of akro you have is outdated. You can update akro using `pip install akro -U` from within your virtual/conda environment.

**Comment by JeremyAlain** [comment]
Yes this fixed it thanks so much.
