### ISSUE TITLE
Docs page "Train a policy to solve an environment"

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1530]
See #1426

**Comment by yeukfu** [comment]
@ryanjulian I find [experiments doc](https://garage.readthedocs.io/en/latest/user/experiments.html) is a good example to show how to train a policy to solve an environment. So this doc should be a more detailed version?

**Comment by ryanjulian** [comment]
I think it's good to have a separate doc with the title, even if a lot of the content is similar, because sometimes people just want a single link they can click to understand how to solve their exact issue (training a pollicy).

It is okay if some content is repetitive.

Over time, the experiments doc will get more complex as more features are added to `@wrap_experiment`, whereas your doc will (hopefully) remain simple.
