### ISSUE TITLE
Tensorboard integration

### ISSUE THREAD

**Issue by JeremyAlain** [rlworkgroup/garage#1551]
Hi, I was not able to find anything in the documentations about how to plot metrics for example with tensorboard. By going to the dowel repository I was ab le to figure out to add 
```
logger.add_output(dowel.TensorBoardOutput('tensorboard_logdir'))
```

But still, if I start my tensorboard, now different runs will be plotted in the same plot. Not sure if there is a recommended way to do it. 

Thanks

**Comment by ryanjulian** [comment]
Hi @JeremyAlain 

Thanks for trying garage! Sorry for the sparse docs -- are working on a documentation page about this.

Anything you log using `dowel.tabular` will appear in TensorBoard.

If you use the `wrap_experiment` helper function (see examples in `examples/`), the setup you describe is performed for you, and each experiment will automatically log TensorBoard summaries to `data/local`. You can then run `tensorboard --logdir=data/local` to see a TensorBoard entry for each of your experiments.

> But still, if I start my tensorboard, now different runs will be plotted in the same plot. Not sure if there is a recommended way to do it.

This is default behavior in TensorBoard. If you would like to see only one experiment, you can deselect experiments you don't want to see using the checkboxes on the left of the web interface.
