### ISSUE TITLE
render(mode="rgb_array") broken in MujocoEnv

### ISSUE THREAD

**Issue by eric-heiden** [rlworkgroup/garage#156]
Rendering a MujocoEnv to an RGB array doesn't work:
```
File "test.py", line 123, in main
    env.render(mode='rgb_array')
  File ".../garage/envs/mujoco/mujoco_env.py", line 197, in render
    data, width, height = viewer.get_image()
AttributeError: 'MjViewer' object has no attribute 'get_image'
```

**Comment by jonashen** [comment]
https://github.com/openai/gym/commit/c5b624c6a6334137e7ae7bcc73b134725956c4ea

This should work

**Comment by eric-heiden** [comment]
Thanks, this works! I will make a PR soon to fix it for garage.

**Comment by ryanjulian** [comment]
Please include a test replicating the bug!

**Comment by ryanjulian** [comment]
I think you could replicate this by testing MujocoEnvs with render_mode="rgb_array" in tests/envs/test_envs.py (in addition to the default, which is render_mode="human")
