### ISSUE TITLE
Need Some Help with `runner` Interface

### ISSUE THREAD

**Issue by DarrenRuan** [rlworkgroup/garage#1573]
Hi,

I notice that there is a big change from `2019.02.2` to `2019.10.0` about the Runner API for executing experiments and LocalRunner implementations. I tried to understand how to use the `runner` in DDPG without `env` parameter. I have tried to learn this idea from the document here [https://garage.readthedocs.io/en/v2019.10.1/user/implement_algo_advanced.html](url). But it seems that there is not anything related to the `runner`.

Could you share some ideas about how to replace `env` in the original `BatchPolopt` with `runner`? And how could I initialize the `env` in it? I really appreciate it if you could give more help on `runner` and `LocalRunner`.

**Comment by ryanjulian** [comment]
Hi @DarrenRuan 

Thanks for using garage!

We've recently added much better documentation on this to ReadTheDocs, which you can find here: https://garage.readthedocs.io/en/latest/user/implement_algo.html

Almost everything here should apply to `v2019.02`, though I recommend you start working off the the latest release candidate to prepare for `v2020.06` (which we will release very soon, see the TODO list here: https://github.com/rlworkgroup/garage/milestone/15)
