### ISSUE TITLE
Remove garage.envs.Step

### ISSUE THREAD

**Issue by eric-heiden** [rlworkgroup/garage#163]
In order to fully comply with `gym.Env`, the [`step` function](https://github.com/openai/gym/blob/master/gym/core.py#L46) of all our environments needs to return the tuple `(observation, reward, done, info)` and not a `garage.envs.Step` object.

**Comment by ryanjulian** [comment]
```sh
In [1]: from garage.envs import Step

In [2]: from garage.envs.base import _Step

In [3]: type(_Step)
Out[3]: type

In [4]: issubclass(_Step, tuple)
Out[4]: True

In [5]: s = Step(1,2,3)

In [6]: isinstance(s, _Step)
Out[6]: True

In [7]: s[0]
Out[7]: 1

In [8]: s.observation
Out[8]: 1

In [9]: s[1]
Out[9]: 2

In [10]: s.reward
Out[10]: 2

In [11]: s[2]
Out[11]: 3

In [12]: s.done
Out[12]: 3

In [13]: s[3]
Out[13]: {}

In [14]: s.info
Out[14]: {}

In [15]: tuple(s)
Out[15]: (1, 2, 3, {})
```

**Comment by ryanjulian** [comment]
I don't see the bug.

`garage.envs.Step` returns an object which implements the tuple interface, and whose shape is `(observation, reward, done, info)`

**Comment by eric-heiden** [comment]
I see, then it behaves as specified by `gym.Env`.
