### ISSUE TITLE
import baselines does not exist

### ISSUE THREAD

**Issue by jonashen** [rlworkgroup/garage#166]
Not sure what the `baselines` package in `tests/regression_tests/test_benchmark_ddpg.py` is referencing.

**Comment by ryanjulian** [comment]
https://github.com/openai/baselines

**Comment by ryanjulian** [comment]
I'm not sure how this got missed by check_imports.sh

**Comment by jonashen** [comment]
We should append this to environment.yml

**Comment by zhanpenghe** [comment]
I think baselines is already in the yml file. #18

**Comment by ryanjulian** [comment]
But is the error gone?

**Comment by zhanpenghe** [comment]
This is not an error on CI because baselines can be successfully installed. However, setup_linux could not install baselines because of the missing package `libopenmpi-dev`. I opened another issue for add this dependency to the setup script. #169
