### ISSUE TITLE
Docs page "Tutorials > Implement a custom Algorithm (TF and Numpy sections)"

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1671]

**Comment by yeukfu** [comment]
@ryanjulian This seems duplicated with [Implement a New Algorithm](https://garage.readthedocs.io/en/latest/user/implement_algo.html).

**Comment by ryanjulian** [comment]
That document is missing sections for Numpy and TensorFlow, hence the title of this issue.

**Comment by yeukfu** [comment]
@ryanjulian For the Numpy and TensorFlow sections, is it expected to implement the same algorithm as PyTorch's?

**Comment by ryanjulian** [comment]
Some parts will be different.
