### ISSUE TITLE
Release GPS soon?

### ISSUE THREAD

**Issue by Yufei-Kang** [rlworkgroup/garage#1685]
Recently, I noticed that the title **Guided Policy Search Pytorch** had been changed to **torch/Guided Policy Search**. However, I cannot find the file **“torch/Guided Policy Search.”** Will it be released soon? Thank you for your help!

**Comment by Yufei-Kang** [comment]
**Reply from Ryan :**

In short, a student has committed to working on this algorithm, but it may be the end of the summer before they are finished (and there's no guarantee they will finish, or on what timeline). If you'd like to see the method in garage, we love pull requests :).

**Comment by ryanjulian** [comment]
@Yufei-Kang thank you for the issue.

Please track #461  for updates on GPS. It is currently in the v2020.09 release milestone, which means we intend to have it ready by September 2020. However, milestones are loose planning tools and not absolute promises.

If you really want this fast, we'd love to start reviewing PRs towards a GPS implementation :).
