### ISSUE TITLE
Add mpi dependency to setup scripts

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#169]
`libopenmpi-dev` is missing for openai baselines package.

**Comment by jonashen** [comment]
Is this related to the mpi4py error?

```
_configtest.c:2:10: fatal error: 'mpi.h' file not found
  #include <mpi.h>
           ^~~~~~~
  1 error generated.
  failure.
  removing: _configtest.c _configtest.o
  error: Cannot compile MPI programs. Check your configuration!!!

  ----------------------------------------
  Failed building wheel for mpi4py
```

**Comment by CatherineSue** [comment]
Yes, you can `sudo apt-get install libopenmpi-dev` then update the conda env

**Comment by jonashen** [comment]
How do we install it for macOS?

**Comment by zhanpenghe** [comment]
https://stackoverflow.com/questions/28440834/error-when-installing-mpi4py

**Comment by zhanpenghe** [comment]
Also please add a git hash to the environment.yml so that it is the latest version of baseline.
