### ISSUE TITLE
Failed to reproduce example her_ddpg_fetchreach

### ISSUE THREAD

**Issue by st2yang** [rlworkgroup/garage#1717]
Hi,

I was trying to run examples/tf/[her_ddpg_fetchreach.py](https://github.com/rlworkgroup/garage/blob/master/examples/tf/her_ddpg_fetchreach.py) but got a much worse performance. I attached the results as follows, and it seems that it's not working at all. Do you have any idea how to make it work? Though the default parameters look reasonable, should I try to tune some parameters?

Thank you in advance.

> AverageSuccessRate                       0
Epoch                                   49
Evaluation/AverageDiscountedReturn      -9.94112
Evaluation/AverageReturn              -999.93
Evaluation/CompletionRate                0
Evaluation/Iteration                   980
Evaluation/MaxReturn                  -998
Evaluation/MinReturn                 -1000
Evaluation/NumTrajs                    100
Evaluation/StdReturn                     0.324191
Policy/AveragePolicyLoss                 4.17451
QFunction/AverageAbsQ                    4.19709
QFunction/AverageAbsY                    4.19412
QFunction/AverageQ                      -4.16916
QFunction/AverageQFunctionLoss           0.0232313
QFunction/AverageY                      -4.16946
QFunction/MaxQ                           2.87869
QFunction/MaxY                           2.62668
TotalEnvSteps                       100000

**Comment by ryanjulian** [comment]
@st2yang thanks for the bug report! we will investigate in the next few weeks and get back to you.

in the meantime, if you find working parameters or the root cause, please let us know!

**Comment by st2yang** [comment]
@ryanjulian Sure, thanks for your help. I tried to change some parameters and might get a better result. But I'm not sure how good it is. Since I am new to garage, I am wondering if there is a way to evaluate the trained policy by rendering the environment?

**Comment by ryanjulian** [comment]
You can either set `plot=True` in `runner.train` or follow [this guide](https://garage--1642.org.readthedocs.build/en/1642/user/reuse_garage_policy.html) (it is in a pull request now, but will appear on garage.readthedocs.io in the next day or two)

**Comment by st2yang** [comment]
Thanks @ryanjulian , I'll try. BTW, when I tried the second option, it has some conflict error regarding tf

>    data = snapshotter.load('path/to/snapshot/dir')
  File "/homes/yangyang/.local/lib/python3.6/site-packages/garage/experiment/snapshotter.py", line 153, in load
    return joblib.load(file)
  File "/homes/yangyang/.local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 588, in load
    obj = _unpickle(fobj)
  File "/homes/yangyang/.local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/homes/yangyang/miniconda3/envs/mujoco-gym/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/homes/yangyang/.local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 339, in load_build
    Unpickler.load_build(self)
  File "/homes/yangyang/miniconda3/envs/mujoco-gym/lib/python3.6/pickle.py", line 1507, in load_build
    setstate(state)
  File "/homes/yangyang/.local/lib/python3.6/site-packages/garage/tf/policies/continuous_mlp_policy.py", line 209, in __setstate__
    self._initialize()
  File "/homes/yangyang/.local/lib/python3.6/site-packages/garage/tf/policies/continuous_mlp_policy.py", line 85, in _initialize
    shape=(None, self._obs_dim))
  File "/homes/yangyang/miniconda3/envs/mujoco-gym/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 3023, in placeholder
    raise RuntimeError("tf.placeholder() is not compatible with "

**Comment by ryanjulian** [comment]
@st2yang can you post the full error message? if it doesn't fit in github, you can use pastebin or similar.

**Comment by st2yang** [comment]
@ryanjulian Sorry I updated the error message. The error happens when loading tf policy in snapshotter.load('path/to/snapshot/dir').

**Comment by ryanjulian** [comment]
Can you post the full text of the script you're running? It looks like TF2 has been initialized in eager mode (rather than graph mode), which garage doesn't support.

**Comment by st2yang** [comment]
@ryanjulian I am using the exact example script as you mentioned. Disabling eager by disable_eager_execution() will throw another error. I think it's tf-related issue, I might use pytorch first?

> from garage.experiment import Snapshotter
snapshotter = Snapshotter()
data = snapshotter.load('path/to/snapshot/dir')

**Comment by ryanjulian** [comment]
@st2yang yeah -- if you want an immediate solution, try the PyTorch version. However, I don't think HER is currently implemented in the torch version. 

I don't think it's a difficult modification.

**Comment by st2yang** [comment]
@ryanjulian I thought HERBuffer is independent of the backend, and I can actually run pytorch code with HER. You mean HERBuffer wouldn't boost policy training in the torch vision? Like HERBuffer would be treated as a regular buffer?

**Comment by ryanjulian** [comment]
@st2yang you're right! we recently made HERReplayBuffer can be used independent of the algorithm.

the only caveat i'll add is that we haven't tested HERReplayBuffer+torch/DDPG -- let us know how it goes!

**Comment by ryanjulian** [comment]
@st2yang in your original attempt, did you replace `'path/to/snapshot/dir'` with the actual path to your algorithm's snapshot?

**Comment by st2yang** [comment]
@ryanjulian 

- snapshot loading
Yes, I replaced it. And the snapshot works in torch version. So there's some minor bug/conflict in tf version.

- HER
HERBuffer + torch/ddpg is at least runnable and give some reasonable results. Since FetchReach is a simple task, I am not sure how much HERBuffer contributes in this case.

**Comment by st2yang** [comment]
Some updates regarding example script her_ddpg_fetchreach:

After some experiments, I think there're two types of bugs or errors
(1) the original parameters are not working at all. After I change some parameters, the training is indeed much better and give reasonable performance.

(2) statistic calculation might be wrong. Under a reasonably good performance (in terms of other statistics and evaluation rendering), AverageSuccessRate and Evaluation/CompletionRate are always o, which doesn't make sense.

**Comment by ryanjulian** [comment]
@st2yang feel free to send us a PR with the updated params. We would love to have it!

As for (2), there might be a misunderstanding here around the definition of those metrics:
* `Evaluation/AverageSuccessRate` calculates the average number of trajectories which have `'success=True'` in their `env_info` field (see [here](https://github.com/rlworkgroup/garage/blob/master/src/garage/_functions.py#L143)). This applies only to metaworld environments, as far as I know. If you seeing this metrics in your log while using the fetch environment's, that's a bug. To compute this for the gym Fetch environments, you would need to look for the key `'is_success'` (see [here](https://github.com/openai/gym/blob/0.15.4/gym/envs/robotics/robot_env.py#L68)). Feel free to send us a PR for that.

* `Evaluation/CompletionRate` measures the average number of trajectories which end in a termination condition (i.e. `done==True` in the `gym.Env` interface). However, not all environments send termination signals, so it's quite common for this to be 0 for a working agent. As far as I can tell, the Fetch environments never send termination signals (see [here](https://github.com/openai/gym/blob/0.15.4/gym/envs/robotics/robot_env.py#L66)), so this always being 0 is normal.

**Comment by st2yang** [comment]
@ryanjulian I see. Thanks a lot for your detailed explanation! I'll try to look into these and do more experiments, then send a PR about the issues.

**Comment by ahtsan** [comment]
@st2yang Thanks for bringing this up. For now, could you try entering a `tf.Session()` and see if loading tf policy works?
```
from garage.experiment import Snapshotter
import tensorflow as tf //import tf

snapshotter = Snapshotter()
with tf.compat.v1.Session(): //enter a tf session
        data = snapshotter.load('path/to/snapshot/dir')
	policy = data['algo'].policy
	env = data['env']

	# See what the trained policy can accomplish
	from garage.sampler.utils import rollout
	path = rollout(env, policy, animated=True)
	print(path)
```

**Comment by st2yang** [comment]
@ahtsan Thanks it works!

**Comment by ryanjulian** [comment]
@ahtsan can you update the docs page accordingly?

**Comment by st2yang** [comment]
close this issue, related to PR #1739
