### ISSUE TITLE
her_ddpg_fetchreach in TensorFlow tree doesn't run

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#1742]
Observations returned from the environment `FetchReach` is a `dict` but not `np.ndarray`, we probably need a wrapper to work around that. This doesn't happen in `release-2020.06` and `release-2019.10`.

**Comment by ryanjulian** [comment]
Hmm I wonder how did test_examples not catch this?

**Comment by gitanshu** [comment]
We have always skipped example/her_ddpg_fetchreach because it was broken
https://github.com/rlworkgroup/garage/blob/master/tests/integration_tests/test_examples.py#L76

**Comment by gitanshu** [comment]
@irisliucy please enable the test [here](https://github.com/rlworkgroup/garage/blob/master/tests/integration_tests/test_examples.py#L76) when you fix this
