### ISSUE TITLE
Use worker_cls in LocalRunner.setup()

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1755]
`setup(self, algo, env, sampler_cls=None, sampler_args=None, n_workers=psutil.cpu_count(logical=False), worker_class=DefaultWorker, worker_args=None)`

...is surprising, because there's `sampler_cls` and `worker_class`

**Comment by ryanjulian** [comment]
@irisliucy does #1942 fix this?

**Comment by irisliucy** [comment]
I'll respond according to my understanding of the issue. #1942 fixes the case of `DefaultWorker` as the worker_class regardless of setting the `RLAlgorithm.worker_cls` attribute to other sampler worker classes. With #1942, by default, `DefaultWorker` is set to be the `worker_class` in `LocalRunner.setup()` so we don't need to pass `worker_class ` explicitly. Only when we want to set `worker_class` to other than `DefaultWorker`, we need this.

**Comment by ryanjulian** [comment]
I think the answer is "yes" then. I'll close it.
