### ISSUE TITLE
Paths are not added to replay buffer in DQN

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#1773]
Is it a bug? unlike DDPG (https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/algos/ddpg.py#L314), DQN doesn't add paths to replay buffer (https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/algos/dqn.py#L241).

**Comment by ahtsan** [comment]
I think we should probably figure out the average return for algorithms WITHOUT any training, and make sure the integration test has a threshold higher than that so as to catch this kind of bugs.

In this case, DQN without any training gets average return of ~24, which is higher than the threshold 15. It could only detect if something wrongs in the algorithm and it doesn't learn, but it won't be able to catch if the algorithm did not try to learn at all.

**Comment by ryanjulian** [comment]
It's probably the case for many algorithms that we can't run a test in the CI with enough samples to show learning.

In that case, we should run the algorithm for just 1  relevant epoch/cycle and verify simple things like:
* Can collect samples
* Can run a single optimization epoch (nonzero gradients too?)
* Amount of data in the replay buffer is what we expect
* Any expected metrics are reported to dowel
* Algorithm can be checkpointed and restored
etc.

**Comment by ahtsan** [comment]
Nonzero gradients is a good idea.

After I added paths into the buffer, I see that DQN is not learning. There could be a critical bug somewhere. We would want to address this before the next release.

**Comment by krzentner** [comment]
Wait, is this not fixed now?

**Comment by maliesa96** [comment]
Confirmed #1772 fixes this.
