### ISSUE TITLE
test_examples integration test is sending false positives

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1801]

**Comment by gitanshu** [comment]
@ryanjulian So 1 of example was being skipped ( fixed in #1812 ) and the other was erroring out after 3 epochs ( #1815 ) while we only run 1 epoch in test_examples. Is there anything we need to change in test_examples now? Or can we close this issue?

**Comment by ryanjulian** [comment]
We should be detecting the failures which happen after 3 epochs.

**Comment by gitanshu** [comment]
Nothing to be done here. @krzentner to open an issue about how https://github.com/rlworkgroup/garage/issues/1797 could have been caught in tests
