### ISSUE TITLE
max_and_skip wrapper does not work with the ray sampler

### ISSUE THREAD

**Issue by avnishn** [rlworkgroup/garage#1813]
Related to #1743. When using the max_and_skip wrapper with an env and the ray_sampler, the private field of the wrapper `self._obs_buffer` is not pickled properly. When ray workers go to write to this buffer, which is a numpy array, they get the error because `self._obs_buffer` is now read only. 

I don't believe that generally numpy arrays need to be pickled in special ways -- we do this all the time for policy weights. However, perhaps there is some special logic required to wrap environments that have an underlying numpy array inside of their wrappers.

@krzentner, @ryanjulian wdyt?

**Comment by ryanjulian** [comment]
The root cause of this bug is that max_and_skip wrapper doesn't pickle properly, which is a requirement of most garage components.

**Comment by avnishn** [comment]
I think that this actually may have been an issue with improperly installed dependencies. I ran the example `dqn_pong` using docker off of master with `RaySampler` and I had no issues. I'm going to close this for now.
