### ISSUE TITLE
`from garage import wrap_experiment` throws TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by JustoA** [rlworkgroup/garage#1866]
I recently installed a brand new Anaconda 3, python 3.8 environment and then installed `gym`, `garage`, and `gym-retro` using the following command:
`pip3 install gym garage gym-retro`
Installation went off without a hitch, and I double checked with `
pip3 check`:
> No broken requirements found.

However, when I try to run the "Run Experiments" example, I'm met with the following error:

```
Traceback (most recent call last):
  File "/home/jutin/PycharmProjects/newML/test-garage.py", line 1, in <module>
    from garage import wrap_experiment
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/garage/__init__.py", line 10, in <module>
    from garage.experiment.experiment import wrap_experiment
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/garage/experiment/__init__.py", line 4, in <module>
    from garage.experiment.local_runner import LocalRunner
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/garage/experiment/local_runner.py", line 11, in <module>
    from garage.experiment.snapshotter import Snapshotter
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/garage/experiment/snapshotter.py", line 8, in <module>
    import joblib
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/joblib/parallel.py", line 32, in <module>
    from .externals.cloudpickle import dumps, loads
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 151, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/jutin/anaconda3/envs/newML/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 132, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
 ```

Any ideas if this is something I can fix myself?

**Comment by ryanjulian** [comment]
@JustoA Thanks for trying garage! There are a lot of combinations of dev environments and it's really hard to test all of them, so please bear with us!

We haven't started testing Python 3.8 yet in our test suite. Can you try with a Python 3.7 environment?

pip (inside or outside conda) doesn't apply a very sophisticated dependency resolution algorithm, so it's very easy to end up with incompatible package versions in large projects. To solve this, you can use a different environment manager (e.g. Pipenv or poetry instead of conda) or you can install a list of frozen dependencies (from the garage CI, [here's one from last night](https://travis-ci.com/github/rlworkgroup/garage/jobs/369615382#L1640)) into your conda environment.

For convenience, here's one I just retrieved for `v2020.06.1` (the latest on PyPI):
```sh
absl-py==0.9.0
aiohttp==3.6.2
akro==0.0.8
astunparse==1.6.3
async-timeout==3.0.1
atari-py==0.2.6
attrs==19.3.0
beautifulsoup4==4.9.1
box2d-py==2.3.8
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
click==7.1.2
cloudpickle==1.2.2
cma==2.7.0
colorama==0.4.3
cycler==0.10.0
Cython==0.29.21
decorator==4.4.2
dm-control==0.0.300771433
dm-env==1.2
dm-tree==0.1.5
dowel==0.0.3
fasteners==0.15
filelock==3.0.12
future==0.18.2
garage==2020.06.1
gast==0.3.3
glfw==1.12.0
google==3.0.0
google-auth==1.20.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.31.0
gym==0.15.4
h5py==2.10.0
idna==2.10
imageio==2.9.0
importlib-metadata==1.7.0
joblib==0.12.5
jsonschema==3.2.0
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
lxml==4.5.2
Markdown==3.2.2
matplotlib==3.3.0
monotonic==1.5
msgpack==1.0.0
mujoco-py==2.0.2.11
multidict==4.7.6
networkx==2.4
numpy==1.18.5
oauthlib==3.1.0
opencv-python==4.3.0.36
opt-einsum==3.3.0
Pillow==7.2.0
protobuf==3.12.4
psutil==5.7.2
py-spy==0.3.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyglet==1.3.2
PyOpenGL==3.1.5
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
PyWavelets==1.1.1
PyYAML==5.3.1
ray==0.8.6
redis==3.4.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-image==0.17.2
scipy==1.4.1
setproctitle==1.1.10
six==1.15.0
soupsieve==2.0.1
tabulate==0.8.7
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorboardX==2.1
tensorflow==2.3.0
tensorflow-estimator==2.3.0
tensorflow-probability==0.10.0
termcolor==1.1.0
tifffile==2020.7.24
torch==1.4.0
torchvision==0.5.0
typing-extensions==3.7.4.2
urllib3==1.25.10
Werkzeug==1.0.1
wrapt==1.12.1
yarl==1.5.1
zipp==3.1.0
```

Long term, we're planning on adding a conda-forge package for garage soon (see #1042), so that conda will properly solve the dependency graph.

**Comment by ryanjulian** [comment]
It looks like this is an issue with non-latest versions of `cloudpickle` and Python 3.8: https://bugs.python.org/issue38775

Some garage dependencies constrain the cloudpickle version, so I think you may need to stay back at Python 3.7.

**Comment by JustoA** [comment]
Thank you so much for the speedy response! I’m AFK at the moment but as soon as I’m back I’ll roll back to Py 3.7 and let you know! While I’m at it I’ll use the frozen deps you gave me above.

**Comment by JustoA** [comment]
So I installed from that package list, and I'm running into a different error now inside of tensorflow: 
`ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core' `

This seems to be an issue with Tensorflow as seen [here](https://github.com/tensorflow/tensorflow/issues/40584). I've been unable to get this working with the nightly tf build, however. I'm going to poke more at it tomorrow.

**Comment by JustoA** [comment]
I resolved this by installing tfp-nightly and leaving everything else as-is.
