### ISSUE TITLE
max_episode_length seems to break CEM/DQN cartpole example

### ISSUE THREAD

**Issue by JustoA** [rlworkgroup/garage#1876]
Hi again,
I've tried to run the CEM-Cartpole and DQN-Cartpole examples provided, but it seems that max_episode_length is an unexpected argument for both the CEM and the DQN. Removing max_episode_length allows them to run.

**Comment by ryanjulian** [comment]
@JustoA thanks for the bug report! We're working on it.

**Comment by AiRuiChen** [comment]
Hi @JustoA ,

Thanks for reporting this. I couldn't reproduce this locally. I verified that `max_episode_length` is an expected argument for [CEM](https://github.com/rlworkgroup/garage/blob/master/src/garage/np/algos/cem.py#L46) and [DQN](https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/algos/dqn.py#L64). 

Are you running with the latest garage version? What's the error message? 

Thanks.

**Comment by ryanjulian** [comment]
Perhaps @JustoA is running v2020.06 (from `pip install garage`), but running an example from master?

In that case, take a look at the examples from the release branch for the most recent release to PyPI (`release-2020.06`): https://github.com/rlworkgroup/garage/tree/release-2020.06/examples

**Comment by JustoA** [comment]
So sorry! Yes, I am running the example from master... I'll look at those examples instead! Sorry for the inconvenience!
