### ISSUE TITLE
Test with new pip resolver

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1895]
See https://travis-ci.com/github/rlworkgroup/garage/jobs/371528756#L1019

http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html

**Comment by gitanshu** [comment]
(I know this is meant for an automated test)

I tried it last week, this seems to be the only problem.

```
ERROR: Cannot install garage[mujoco] 2020.9.0rc2.dev0 and gym[all] 0.17.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    garage[mujoco] 2020.9.0rc2.dev0 depends on mujoco-py<2.1 and >=2.0
    gym[all] 0.17.2 depends on mujoco-py<2.0 and >=1.50; extra == "all"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by krzentner** [comment]
How hard would it be for us to not require mujoco 2.0? I'm not too familiar with what's different between the versions, but it seems we don't have *that much* mujoco specific code (besides tests).

**Comment by gitanshu** [comment]
pip 20.2.4 was released couple days ago and `pip install --use-feature=2020-resolver garage[all]` is stuck in a loop now. Relevant issue on pip's issue tracker: https://github.com/pypa/pip/issues/9011

**Comment by ryanjulian** [comment]
Different versions of MuJoCo can lead to different benchmark results (e.g. friction behavior can change), so it's important to specify. 

Our main direct MuJoCo dependency is in garage.envs.mujoco, but it would be nice to remove those in the future in favor of some other standardized library of meta-RL environments.

**Comment by gitanshu** [comment]
Closing this. As far as I can tell, this is working fine now.
