### ISSUE TITLE
ImportError: cannot import name 'GymEnv'

### ISSUE THREAD

**Issue by sdfzz** [rlworkgroup/garage#1947]
Dear developers,

Hi, I'm having trouble installing garage on my system. My system is:

Ubuntu 18.04.4 LTS
Python 3.6.9
Tensorflow 1.15

Using virtualenv, I installed garage by (https://garage.readthedocs.io/en/latest/user/installation.html):

```
source env/bin/activate
pip install garage
```

But, when I try to run an example, I'm getting the following error (dqn_cartpole.py, for example):

`ImportError: cannot import name 'GymEnv'
`
Is this a known Issue? Is there any workaround on this?

Any help would be appreciated

Sincerely,

Steve

**Comment by ryanjulian** [comment]
@sdfzz Thanks for trying garage!

It seems that you're likely using documentation and/or examples from the branch `master`, while installing a garage release from PyPI (pip). The code in the release and the code on master differ, so the examples on `master` may no longer work with the PyPI release out-of-the-box.

For examples based on the [`v2020.06`](https://github.com/rlworkgroup/garage/releases/tag/v2020.06.0) release, see the [`release-2020.06` branch](https://github.com/rlworkgroup/garage/tree/release-2020.06), which is kept up-to-date with bug fixes as we find them and used to create the PyPI releases.

**More info:**
Garage development moves pretty quickly. To insulate you from unstable new code, the PyPI releases are created from more-stable "release branches." The most recent release is `v2020.06`, so the code you will find on PyPI lives in the [`release-2020.06` branch](https://github.com/rlworkgroup/garage/tree/release-2020.06). You can always find the exact code used to create the release you're using under the tag corresponding to that release number from PyPI (e.g. [`v2020.06.2`](https://github.com/rlworkgroup/garage/tree/v2020.06.2) is the latest stable release). We create a new release every few months with the latest features and APIs, and support old releases for 8-12 months with bug fixes and dependency fixes.
