### ISSUE TITLE
Ray tests are flaking on GH Actions

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1961]
See https://github.com/rlworkgroup/garage/pull/1959/checks?check_run_id=1016422383#step:6:111

**Comment by avnishn** [comment]
I think I might need more information, the checks on this don't reveal a bug, and I'm unsure how to view the logs from gH actions builds vs travis builds

**Comment by ryanjulian** [comment]
Here's another example https://github.com/rlworkgroup/garage/runs/1016409427?check_suite_focus=true#step:6:121
