### ISSUE TITLE
Implement some easy PyTorch optimizations

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1990]
See https://twitter.com/karpathy/status/1299921324333170689?s=03

**Comment by mugoh** [comment]
I'm about to start working on this. However, for some of the optimization measures mentioned in the [video](https://t.co/7CIDWfrI0J?amp=1) attached to @ryanjulian shared tweet above, it would be very helpful to hear your thoughts and know if I should go ahead and implement them here.

I list them below.


##### 1. Replacing `model.zero_grad()` and `optimizer.zero_grad()`
The video proposes to set `param.grad = None` in a loop instead. This option has been recently added to PyTorch as `optimizer.zero_grad(set_none=True)` but they give [this warning about using it](https://github.com/pytorch/pytorch/blob/76ee58e2ec48d6922c49d647b276c1575a96aa09/torch/optim/optimizer.py#L167-L186) about change in behaviour, and I'm not sure what that will do. Should this optimization measure be added here?

- - [apex seems to use it](https://github.com/NVIDIA/apex/blob/4a1fa2c411504af3330da1fa0a28c764dab774ed/apex/optimizers/fused_adam.py#L81) exactly as they suggest, without this warning. Which brings me to the next issue..


##### 2 Using APEX for acceleration
What's emphasized is to use of APEX's fused optimizers. Should this PyTorch extension be added here?
Most of apex implementations/utilies on [NVDIA's apex](https://github.com/NVIDIA/apex) are continuously added to PyTorch, though I can't tell if their fused optimizers will also be welcomed soon.
