### ISSUE TITLE
how to set number of episodes ?

### ISSUE THREAD

**Issue by kibamin** [rlworkgroup/garage#2134]
Is it possible to set the episode parameter in algorithms (for example in [trpo_cartpole.py](https://github.com/rlworkgroup/garage/blob/v2020.06.3/examples/tf/trpo_cartpole.py)) ?
if yes, how ?
if no, what is default number of episodes ?

**Comment by krzentner** [comment]
Hi kibamin,
We don't actually control the number of episodes directly in garage. Instead, we control the number of timesteps.
There are three important parameters for this:
 1. `max_episode_length`, which is usually passed to `GymEnv`, and determines the number of timesteps per episode.
 2. `batch_size`, which determines the number of timesteps per epoch.
 3. `n_epochs`, which determines the number of total batches to run.

To set the total number of episodes, we would usually do the following:
 1. Set `batch_size` as low as practical for the algorithm (usually around 4000 for TRPO or PPO).
 2. Choose `max_episode_length` based on the benchmark you're trying to solve.
 3. Set `n_epochs` to `number_of_desired_episodes * batch_size / max_episode_length`

**Comment by kibamin** [comment]
> Is it possible to set the episode parameter in algorithms (for example in [trpo_cartpole.py](https://github.com/rlworkgroup/garage/blob/v2020.06.3/examples/tf/trpo_cartpole.py)) ?
> if yes, how ?
> if no, what is default number of episodes ?

**Comment by kibamin** [comment]
@krzentner  Thanks for the clear and fast reply.
