### ISSUE TITLE
in maml of torch, stack vs. cat for batch trajectories?

### ISSUE THREAD

**Issue by JeongHyunho** [rlworkgroup/garage#2208]
when the number of trajectories in each sample, doesn't stack raise error because of different tensor size?

https://github.com/rlworkgroup/garage/blob/e395ba67ff00947b7fe2958481ce6e606d3e9d96/src/garage/torch/algos/maml.py#L329-L343

**Comment by ryanjulian** [comment]
Hi @JeongHyunho 

Thanks for filing an issue! If you have found an error, can you provide us with a minimal code snippet to reproduce the error?
