### ISSUE TITLE
Cannot import GymEnv

### ISSUE THREAD

**Issue by aswinnahrendra** [rlworkgroup/garage#2209]
I tried to run an example code from the documentation, e.g., DDPG. However, I got the following error 
`ImportError: cannot import name  'GymEnv' from 'garage.envs'`

Do you have any idea about this? The installation is done successfully, and i can import garage already. Thanks!

**Comment by ryanjulian** [comment]
`GymEnv` was introduced after the 2020.06 release (which is what is available on PyPI), whereas the documentation covers what is on the master branch in GitHub.

To use the example from the documentation, you can install from GitHub.

Alternatively, you can view the examples as-of the 2020.06 API here: https://github.com/rlworkgroup/garage/tree/v2020.06.3/examples

**Comment by jackwilkinson255** [comment]
I am having the same issue. I have cloned the master but am getting:
`ImportError: cannot import name 'GymEnv'
`
when I run the example **step_bullet_kuka_env.py**

I'd like to get this example working as I'm using pybullet in my application. 

Currently I have installed using setup.py and the extras for gym and bullet 

Thanks

**Comment by jackwilkinson255** [comment]
Doing `pip install .` inside the repo solved the issue as in  #[2187]
