### ISSUE TITLE
Setup Docker container using setup_linux.sh

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#222]
This will ensure consistency between container and non-container installs.

**Comment by ryanjulian** [comment]
In retrospect this might be a bad idea because it will mean the dockerfile has much fewer layers, so the cache won't work as well. In practice that might not matter--i'm not sure.

**Comment by gonzaiva** [comment]
Based on the latest comments, for the 2018.09 Release, it's sufficient to add a header comment in the setup scripts and the docker file that notifies developers to keep changes consistent across these files.
