### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by limaries30** [rlworkgroup/garage#2256]
Hi , I am using docker to test garage. I pulled the image as in the documentation

However  I get error when I run this code.
```python
from garage.sampler import LocalSampler
```
ImportError: cannot import name 'LocalSampler'

How to fix this?

**Comment by avnishn** [comment]
Hi @limaries30 thanks for bringing your issue to us. 

is this the documentation that you used?

Also @gitanshu brought it to my attention today that there may be a problem with our docker image on dockerhub, that he is fixing right now.

**Comment by limaries30** [comment]
I still get the same error. 

I pulled rlworkgroup/garage.

**Comment by gitanshu** [comment]
Hi @limaries30
We had an issue with our docker image because of some changes in pip's new dependency resolver. I have pushed an update that fixes the dependency tree. If you pull rlworkgroup/garage again, it should work fine.

Feel free to reopen the issue if it still isn't fixed for you.
