### ISSUE TITLE
How do I add a new meta environment?

### ISSUE THREAD

**Issue by tianyma** [rlworkgroup/garage#2291]
Dear author, 
thank you for your excellent work, could you tell me how do I add a new environment for meta learning, is there any necessary, can you post an example on the doc?

**Comment by krzentner** [comment]
Hi tianyma,

How to add a new meta environment depends on the API that environment uses. I recommend you look at the existing examples showing how to use the [meta HalfCheetah](https://github.com/rlworkgroup/garage/blob/master/src/garage/examples/torch/maml_ppo_half_cheetah_dir.py#L59) environments and [Meta-World benchmarks.](https://github.com/rlworkgroup/garage/blob/master/src/garage/examples/tf/rl2_ppo_metaworld_ml10.py#L47)

Generally speaking, you'll want to create a `TaskSampler` to use a meta environment, although existing `TaskSampler`s exist for [commonly used meta-RL APIs, like the `set_task` API.](https://github.com/rlworkgroup/garage/blob/master/src/garage/experiment/task_sampler.py#L118)

**Comment by tianyma** [comment]
Sorry, I am quite new here, I want to know If I use the 2d navigation environment`PointEnv`, should I add a wrapper such as `GymEnv` when calling the env, or I can directly construct the environment?

**Comment by ryanjulian** [comment]
Hi @tianyma -- [`PointEnv` inherits directly from `Environment`](https://github.com/rlworkgroup/garage/blob/master/src/garage/envs/point_env.py#L10), so no wrapper should be necessary.

**Comment by tianyma** [comment]
> Hi @tianyma -- [`PointEnv` inherits directly from `Environment`](https://github.com/rlworkgroup/garage/blob/master/src/garage/envs/point_env.py#L10), so no wrapper should be necessary.

Hi,  @ryanjulian. Thank you very much for your reply. I simply modify the file `maml_trpo_half_cheetah_dir.py` to adapt point environment.
So I simply modify the following code:
```python
env = normalize(GymEnv(HalfCheetahDirEnv(),
             max_episode_length=max_episode_length),
             expected_action_scale=10.)
```
to
```python
    goal = np.array([1., 1.])
    env = PointEnv(goal=goal, max_episode_length=max_episode_length)
```
and then I modify the `task_sampler` from 
```python
    task_sampler = SetTaskSampler(
        HalfCheetahDirEnv,
        wrapper=lambda env, _: normalize(GymEnv(
            env, max_episode_length=max_episode_length),
                                         expected_action_scale=10.)
```
to
```python
    task_sampler = SetTaskSampler(PointEnv)
```
then I directly run the code, but I seems cannot get any result, can you help me?
