### ISSUE TITLE
Use Simulink as environment in Garage 

### ISSUE THREAD

**Issue by mehrdad-moradi** [rlworkgroup/garage#2296]
Can we couple Simulink and Gym and use the Simulink model as an environment for Garage?

**Comment by krzentner** [comment]
You may be able to, if you can make it use the Gym API. One thing that is somewhat tricky is that Garage tends to make copies of the environment object, which can be difficult to implement. You may find it helpful to use only a single worker (set `n_workers=1` when constructing the sampler) to avoid difficulties with multiple environment objects connecting to the same simulink model.

Unfortunately I can't provide detailed instructions for how to set up Simulink with the Gym API.
