### ISSUE TITLE
Multiple gradient steps in Meta-RL evaluation adaptation

### ISSUE THREAD

**Issue by benedikt-schesch** [rlworkgroup/garage#2309]
Hello,

I am trying to run garage/examples/torch/maml_ppo_half_cheetah_dir.py and I would like to adapt the number of gradient steps that the algorithm takes for adaptation to a new task. Is there a proper way to do this because I haven't found anything?

Thank you very much

Benedikt

**Comment by krzentner** [comment]
Hi Benedikt.

Unfortunately there isn't currently any way of doing that with the `MetaEvaluator`. A pull request to implement it would be appreciated.

There is currently the `num_grad_updates` in MAML, but it's only used during training, not evaluation. Theoretically, the logged training results for MAML should be the same as meta-evaluating, assuming that your meta-task has no test / train split.
