### ISSUE TITLE
Observation array outside observation_space warning

### ISSUE THREAD

**Issue by mohakbhardwaj** [rlworkgroup/garage#2311]
Hello,

I have installed garage in a conda environment using 
```pip install --user garage```

However, when I run the ``sac_half_cheetah_batch.py`` example in the torch directory, I get the warnings of the following kind at every timestep
```
/home/mohak/workspace/garage/src/garage/_dtypes.py:1050: UserWarning: Observation array([  0.24466567,   0.23767851,   0.1249347 ,  -0.15034278,
        -0.1472353 ,  -0.74386681,   0.25570265,  -0.38139272,
        -1.51551128,   0.20242845,   0.86932396,  -4.74684808,
        10.17132903, -12.33844412,  -9.14002525,   3.97764134,
        -7.89268877]) is outside observation_space Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
 -inf -inf -inf], [inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf], (17,), float32)
```

I tried uninstall and reinstalling garage and numpy to see if it is a version issue, but that did not work. Any help would be appreciated!

System Specifications:
OS: Ubuntu 20.04, 64bit
Python version: 3.7.12

**Comment by braunjon** [comment]
I had the same problem for a different experiment. For me it worked to downgrade the gym environment to gym~=0.17.2.

I also had to downgrade cloudpickle that the saving and loading of checkpoints works.

Here are my requirements:
```
numpy~=1.19.5
scipy~=1.7.1
cloudpickle~=1.3.0
gym~=0.17.2
click~=8.0.3
six~=1.15.0
typing-extensions~=3.7.4
mujoco-py<2.1,>=2.0
garage~=2021.3.0
```

Maybe this helps you.

**Comment by mohakbhardwaj** [comment]
The above solution worked for me, thanks!
