### ISSUE TITLE
Update setup_linux.sh and setup_osx.sh

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#235]
The new canonical setup steps are in `docker/Dockerfile.ci`. Most of them can be ported into a setup script for a regular machine (omitting the CI-specific parts like the fake X server). Then we can use setup_linux.sh to mostly setup the docker as well.

* There should be a --gpu switch to setup a gpu-based garage. We can't support GPU on Mac.
* setup_osx.sh will be very similar to the CPU version of setup_linux.sh, but there are always complications. I think you can add a job in travis to run on OSX. It can at least run setup_osx.sh on a cron job to make sure it stays fairly stable.

**Comment by ryanjulian** [comment]
I'm not sure it's possible, but if we can get OpenGL support on Docker for OS X (host: OS X, guest: ubuntu) then we can eliminate specific OS X support entirely. GPU support is irrelevant because nobody uses CUDA on OS X

**Comment by gonzaiva** [comment]
Could we pass the path of mjkey.txt as an argument of the scripts?

**Comment by ryanjulian** [comment]
Yes please.

No need to ask for the zip file. We can also assume that users have internet access and use wget to retrieve mjpro150.zip.

**Comment by gonzaiva** [comment]
The setup for linux is fixed in #258 
For OS X is being worked at #279, however it does not consider using Docker.

**Comment by gonzaiva** [comment]
Closed with #279
