### ISSUE TITLE
Replace ProxyEnv with gym.Wrapper

### ISSUE THREAD

**Issue by jonashen** [rlworkgroup/garage#236]
Once GarageEnv is implemented in #231, ProxyEnv will be redundant and all implementations of it should be removed and replaced with GarageEnv.

**Comment by ryanjulian** [comment]
Uh I think the most logical replacement is gym.Wrapper, actually.

**Comment by jonashen** [comment]
GarageEnv will eventually inherit from gym.Wrapper though

**Comment by ryanjulian** [comment]
A gym.Wrapper can wrap a gym.Wrapper. We still have classes other than GarageEnv which need to wrap a gym.Env
