### ISSUE TITLE
Integrate MuJoCo setup script with setup_<platform>.sh

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#24]
We should get rid of this to make packaging easier, unless there's a very compelling reason why not to. `dm_control` makes it work fine.

Imported from https://github.com/ryanjulian/rllab/issues/96

**Comment by gonzaiva** [comment]
I will add an argument in the scripts to setup or not MuJoCo.

**Comment by ryanjulian** [comment]
Isn't this fixed in #258 ?

**Comment by gonzaiva** [comment]
I'm confused about:
>The system should only have 2 states: setup and not setup. 
The fix in #258 setups mujoco all the time, but I'm not sure if the two states you mentioned above translate to an argument in the script that setups or not mujoco, which is currently not implemented.
I will close this issue once that doubt is solve and also when the PR #279 for the script_osx is reviewed and approved.

**Comment by gonzaiva** [comment]
Closed with #279
