### ISSUE TITLE
CHANGELOG for 2018.09 Release

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#246]

**Comment by gonzaiva** [comment]
I will add the comment for zombie processes. But first some questions:
- Is this a new file named CHANGELOG?
-- Is it placed at the root of the garage working directory?
- Does it follow the format defined [here](https://keepachangelog.com/en/1.0.0/)?
-- Does the zombie processes go into the `Security` section?

**Comment by ryanjulian** [comment]
I like that format. Yes it's a new file in root.

zombie processes is not a security concern.

Feel free to start the PR yourself. I think you know most about what has changed. Note that it will be a big CHANGELOG, since it will be the difference between the latest rll/rllab and rlworkgroup/garage
