### ISSUE TITLE
setup_linux.sh fails while looking for mujoco 1.5.0 on a clean system

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#26]
This is probably related to https://github.com/ryanjulian/rllab/issues/89, since dm_control uses mujoco 1.5.0. We may need to combine setup_mujoco.sh and setup_<platform>.sh

Imported from https://github.com/ryanjulian/rllab/issues/90

**Comment by gonzaiva** [comment]
Solved at #125
