### ISSUE TITLE
Add GarageDict to garage.spaces

### ISSUE THREAD

**Issue by CatherineSue** [rlworkgroup/garage#271]
Tf/DDPG and HER use gym.GoalEnv. To wrap GoalEnv with TfEnv, we need to add a Dict space into garage. 

All the primitives relevant to DDPG should be changed to use TfEnv after adding GarageDict to garage.spaces.

Refer: #264 , #270

**Comment by CatherineSue** [comment]
The DeterministicMLPPolicy should be able to use once this is fixed, then add a unit test of DeterministicMLPPolicy.

**Comment by ryanjulian** [comment]
duplicates #243
