### ISSUE TITLE
Always copy actions if they are modified by the environment

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#273]
When using VectorizedSampler, the actions ndarrary (or a slice thereof) of passed directly to the environment. If the environment modifies the action (e.g. by re-scaling or clipping it), it will modify the action vector used by the optimizer. This is *not* the correct behavior--the actions used by the optimizer should be the ones produced by the policy, regardless of how the environment mangles the actions.

To close this issue, we need to audit each environment (including wrappers) and make sure that any environment which modifies actions in `step()` copies them first.

**Comment by ryanjulian** [comment]
@jonashen status update?

**Comment by jonashen** [comment]
I can work on this issue for the release sprint.
