### ISSUE TITLE
Asynchronous TensorFlow plotting doesn't work on Mac OSX

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#3]
Asynchronous plotting for TensorFlow works perfectly fine on Linux using `threading.Thread`, but Mac OS X will not display a window, even if `threading.Thread` is switched to `multiprocessing.Process`, which is how it was implemented using Theano.

Imported from https://github.com/ryanjulian/rllab/issues/127

**Comment by ryanjulian** [comment]
@jonashen is this fixed?

**Comment by jonashen** [comment]
This issue is waiting on the potential refactorization of tf policies from garage.Box to gym.Box

**Comment by ryanjulian** [comment]
Can you explain the dependency? It's not immediately obvious to me.
