### ISSUE TITLE
CMAES shouldn't globally import matplotlib

### ISSUE THREAD

**Issue by eric-heiden** [rlworkgroup/garage#309]
Since CMAES imports matplotlib right at in the beginning, and is included into all algorithms via `algos/__init__.py`, any other code that follows and makes changes to matplotlib rendering (e.g. via `matplotlib.use('Agg')`) will fail with the exception:
```
UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
```
So CMAES should only import matplotlib where it is needed.

**Comment by ryanjulian** [comment]
obseleted by #314
