### ISSUE TITLE
Make box2d fix consistent across scripts/setup_foo.sh

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#319]
https://github.com/rlworkgroup/garage/blob/0d373273116e97fb502ee5ecbff571fe0ed6f80b/scripts/setup_linux.sh#L220

`pip install Box2D-kengz --no-binary Box2D-kengz` is in setup_osx.sh

**Comment by ryanjulian** [comment]
https://github.com/rlworkgroup/garage/blob/master/docker/Dockerfile.ci#L91

**Comment by ryanjulian** [comment]
ref #319

**Comment by naeioi** [comment]
This issue is fixed by #335 . Closed.
