### ISSUE TITLE
Rewrite the logger

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#33]
The current logger interface is okay, but the implementation is a bit messy and the TensorBoard integration is kind of a bolt-on afterthought. It's also package-global which can induce bad implementation decisions.

I'd like to rewrite the logger to be properly encapsulated as a class(es). There can still be a global singleton instance for easy access.

Ideas:
* Eliminate global scope
* First-class TensorBoard support
* Multiprocess-aware logging
* Make the logger API appropriate for all aspects of rllab (e.g. bring-up, training algo, random debugging, etc.) to avoid code peppered with print statements
* Decouple logged datapoints from output formats
* Decouple checkpointing and logging
* Sophisticated checkpoint/log destinations (e.g. remote buckets?)
* Take advantage of a minimalist logging framework rather than hand-crafting logger formats?

Imported from https://github.com/ryanjulian/rllab/issues/80

**Comment by pelillian** [comment]
#464
