### ISSUE TITLE
Move Sawyer environments and contrib.ros to a different repository

### ISSUE THREAD

**Issue by gonzaiva** [rlworkgroup/garage#330]
The following Sawyer environments need to be updated to be compatible with their parent class SawyerEnv:
- garage/envs/mujoco/sawyer/bin_sorting_env.py
- garage/envs/mujoco/sawyer/block_stacking_env.py
- garage/envs/mujoco/sawyer/reacher_env.py
- garage/envs/mujoco/sawyer/sawyer_env.py

For example, now SawyerEnv requires an instance of the Configuration class as parameter for the start_goal_config, instead of the parameters initial_goal and intial_qpos.
Another more hidden issues need to be solved. For example, there seems to be an array size problem for BinSortingEnv when the method set_gripper_state in SawyerEnv gets called.
This issue also requires of tests to verify that the environments mentioned above can be instantiated and serialized (pickled).

**Comment by ryanjulian** [comment]
These aren't going to be stable for a release so let's just move them out. Reassigning to Keren and Utkarsh.
