### ISSUE TITLE
Express Installation does not work as described in the docs

### ISSUE THREAD

**Issue by pelillian** [rlworkgroup/garage#332]
Express installation does not work. This is very important if we want other groups to start using garage!

The scripts should just work without any user intervention.

Mujoco installation (& others?) should be disabled by default.

**Comment by zhanpenghe** [comment]
Can you please provide the error message on installation? Also is it for linux or mac?

**Comment by ryanjulian** [comment]
I look forward to a short PR updating the docs.

IMO MuJoCo should be included by default because it is required for many examples. Not requiring MuJoCo doubles the number of system configurations we need to support and test, unnecessarily. Half-initialized systems are incredibly difficult to write code for.

**Comment by pelillian** [comment]
> Can you please provide the error message on installation? Also is it for linux or mac?

I talked to Angel and the issue was that I had to comment out the line in the script importing mujoco:
```
# Build mujoco-py and check it's correctly installed
python -c 'import mujoco_py
```

It works now. Do you want me to update the docs explaining how to install without mujoco?

**Comment by pelillian** [comment]
@ryanjulian I understand! I was thinking that because mujoco is not freeware that not everyone can just install it. I think Keren mentioned that in the future there was going to be a lighter weight "mini-garage"??

Anyway thanks for explaining :)

**Comment by pelillian** [comment]
#336 will close
