### ISSUE TITLE
Installation should use miniconda 3 rather than miniconda 2

### ISSUE THREAD

**Issue by pelillian** [rlworkgroup/garage#333]
Miniconda 3 is better supported.

FYI: The install script just installed miniconda 2 over my miniconda 3, messing up my envs.

**Comment by ryanjulian** [comment]
Please explain why this is necessary? miniconda2 is known stable and we're hoping to kill conda this semester anyway.

**Comment by naeioi** [comment]
Is there plan for candidate successors of conda? Or it there other way to manage python environments.
