### ISSUE TITLE
Test fixtures import mujoco by default

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#343]
The line `from garage.envs.dm_control import DmControlEnv` import mujoco as well, which can be an issue for people not having mujoco.

**Comment by zhanpenghe** [comment]
I think mujoco is required for dm_control. The situation will be better after we explode garage and separate environments out. For now dm_control and mujoco are assumed set up properly when using garage.

**Comment by ryanjulian** [comment]
Can you make this issue more clear on what you think should be fixed, and then reopen?
