### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by eric-heiden** [rlworkgroup/garage#347]
Simple tests for most components (algos, policies, envs, etc.) that check if, for the same seed, we get the same numerical outputs (up to a certain limit, some GPU operations may not be deterministic/precise enough).

**Comment by ryanjulian** [comment]
To me this is just a unit test. We all want more unit tests, but I think an issue this generally is pretty vacuous.

Perhaps you would like to suggest an incremental test coverage standard (e.g. new code should have x% test coverage).

**Comment by ryanjulian** [comment]
See https://github.com/rlworkgroup/garage/issues/234 and https://github.com/rlworkgroup/garage/issues/233 which we just hired someone to support.
