### ISSUE TITLE
OS X setup script quotes known versions incorrectly

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#355]
https://github.com/rlworkgroup/garage/blob/master/scripts/setup_osx.sh#L13

Should read:
```sh
VERIFIED_OSX_VERSIONS=(
  "10.12",
  "10.13.6",
)

**Comment by gautams3** [comment]
I changed it but the CI build failed for a trpo test (theano/trpo_cartpole_instrumented.py). I don't think this is related to the OSX install script.

> FAIL: test_sigint:1
> 'tests/fixtures/theano/trpo_cartpole_instrumented.py', <ExpLifecycle.START: 1> (tests.integration_tests.test_sigint.TestSigInt)
> Interrupt the experiment in different stages of its lifecyle.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/root/code/garage/tests/integration_tests/test_sigint.py", line 98, in test_sigint
>     interrupt_experiment(experiment_script, exp_stage)
>   File "/root/code/garage/tests/integration_tests/test_sigint.py", line 88, in interrupt_experiment
>     assert clean_exit, colorize(error_msg, "red")
> AssertionError: These processes didn't die during ExpLifecycle.START:
> {'status': 'sleeping', 'name': 'python', 'pid': 543, 'cmdline': ['python', '/root/code/garage/scripts/run_experiment.py', '--n_parallel', '6', '--snapshot_mode', 'last', '--seed', '1', '--plot', 'True', '--exp_name', 'experiment_2018_10_24_03_20_40_0001', '--log_dir', '/root/code/garage/data/local/experiment/experiment_2018_10_24_03_20_40_0001', '--use_cloudpickle', 'True', '--args_data', 'gASV4gMAAAAAAACMF2Nsb3VkcGlja2xlLmNsb3VkcGlja2xllIwOX2ZpbGxfZnVuY3Rpb26Uk5QoaACMD19tYWtlX3NrZWxfZnVuY5STlGgAjA1fYnVpbHRpbl90eXBllJOUjAhDb2RlVHlwZZSFlFKUKEsASwBLBUsLS0dDTnQAdAF0AoMAgwGDAX0BdAN8AWoEZAtkAo0CfQJ0BXwBagRkA40BfQN0BnwBfAJ8A2QEZAVkBmQHZAhkCWQKjQl9BHwEageDAAEAZABTAJQoTksgjAhlbnZfc3BlY5SMDGhpZGRlbl9zaXplc5SGlGgLhZRNoA9LZEsERz/vrhR64UeuRz+EeuFHrhR7iCiMA2VudpSMBnBvbGljeZSMCGJhc2VsaW5llIwKYmF0Y2hfc2l6ZZSMD21heF9wYXRoX2xlbmd0aJSMBW5faXRylIwIZGlzY291bnSUjAlzdGVwX3NpemWUjARwbG90lHSUSyBLIIaUdJQojAlUaGVhbm9FbnaUjAlub3JtYWxpemWUjAtDYXJ0cG9sZUVudpSMEUdhdXNzaWFuTUxQUG9saWN5lIwEc3BlY5SMFUxpbmVhckZlYXR1cmVCYXNlbGluZZSMEEluc3RydW1lbnRlZFRSUE+UjAV0cmFpbpR0lCiMAV+UaA9oEGgRjARhbGdvlHSUjDN0ZXN0cy9maXh0dXJlcy90aGVhbm8vdHJwb19jYXJ0cG9sZV9pbnN0cnVtZW50ZWQucHmUjAhydW5fdGFza5RLCkMcAAEOAg4CDAECAQIBAgECAQIBAgECAQIBAgEIAZQpKXSUUpRK/////4wIX19tYWluX1+Uh5RSlH2UKIwHZ2xvYmFsc5R9lChoG4wXZ2FyYWdlLnRoZWFuby5lbnZzLmJhc2WUaBuTlGgdjB5nYXJhZ2UuZW52cy5ib3gyZC5jYXJ0cG9sZV9lbnaUaB2TlGghjCd0ZXN0cy5maXh0dXJlcy50aGVhbm8uaW5zdHJ1bWVudGVkX3RycG+UaCGTlGgejCpnYXJhZ2UudGhlYW5vLnBvbGljaWVzLmdhdXNzaWFuX21scF9wb2xpY3mUaB6TlGggjChnYXJhZ2UuYmFzZWxpbmVzLmxpbmVhcl9mZWF0dXJlX2Jhc2VsaW5llGggk5RoHIwaZ2FyYWdlLmVudnMubm9ybWFsaXplZF9lbnaUjA1Ob3JtYWxpemVkRW52lJOUdYwIZGVmYXVsdHOUTowEZGljdJR9lIwOY2xvc3VyZV92YWx1ZXOUTowGbW9kdWxllGgsjARuYW1llGgojANkb2OUTowIcXVhbG5hbWWUaCh1dFIu', '--variant_data', 'gAN9cQBYCAAAAGV4cF9uYW1lcQFYIwAAAGV4cGVyaW1lbnRfMjAxOF8xMF8yNF8wM18yMF80MF8wMDAxcQJzLg==']}

**Comment by ryanjulian** [comment]
This is a known-flaky test. It should clear up if you rerun the CI.

**Comment by gautams3** [comment]
Fixed in #357
