### ISSUE TITLE
Remove custom environments which duplicate openai/gym

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#359]

**Comment by ryanjulian** [comment]
Inventory of custom environments

Category    | Name (<>Env)           | openai/gym? | Meta- dep? | Notes |
----------- | ---------------------- | ----------- | ---------- | ----- |
Box2D       | CarParking             | No          | No         | |
Box2D       | Cartpole               | Yes         | No         | |
Box2D       | CartpoleSwingUp        | No          | No         | Pendulum-v0 is a radial joint rather than a cart-pole |
Box2D       | DoublePendulum         | Yes         | No         | Acrobot-v1 |
Box2D       | MountainCar            | Yes         | No         | |
MuJoCo      | Ant                    | Yes         | Yes        | |
MuJoCo      | HalfCheetah            | Yes         | Yes        | |
MuJoCo      | Hopper                 | Yes         | Yes        | |
MuJoCo      | Humanoid               | Yes         | No         | |
MuJoCo      | InvertedDoublePendulum | Yes         | No         | |
MuJoCo      | Point                  | No          | Yes        | |
MuJoCo      | SimpleHumanoid         | No          | No         | |
MuJoCo      | Swimmer3D              | No          | Yes        | Not clear this one is working |
MuJoCo      | Swimmer                | Yes         | Yes        | Not clear this one is working |
MuJoCo      | Walker2D               | Yes         | Yes        | |
Meta-MuJoCo | AntGather              | No          | -          | |
Meta-MuJoCo | PointGather            | No          | -          | |
Meta-MuJoCo | SwimmerGather          | No          | -          | |
Meta-MuJoCo | AntHill                | No          | -          | |
Meta-MuJoCo | HalfCheetahHill        | No          | -          | |
Meta-MuJoCo | HopperHill             | No          | -          | |
Meta-MuJoCo | Swimmer3DHill          | No          | -          | |
Meta-MuJoCo | Walker2DHill           | No          | -          | |
Meta-MuJoCo | AntMaze                | No          | -          | |
Meta-MuJoCo | PointMaze              | No          | -          | |
Meta-MuJoCo | SwimmerMaze            | No          | -          | |

**Comment by ryanjulian** [comment]
Based on above, the first candidates for deletion are:
* Box2D/Cartpole
* Box2D/DoublePendulum
* Box2D/MountainCar
* MuJoCo/Humanoid
* MuJoCo/InvertedDoublePendulum

**Comment by ryanjulian** [comment]
I will also remove MuJoCo/SimpleHumanoid, since I haven't seen anyone using this in papers or on the internet.

**Comment by jaekyeom** [comment]
@ryanjulian I think it would be nice to mention that many of the custom environments have been moved to [https://github.com/rlworkgroup/metaworlds](https://github.com/rlworkgroup/metaworlds) somewhere.

**Comment by ryanjulian** [comment]
@jaekyeom I'd be happy to review a pull request for this!
