### ISSUE TITLE
Parameterized.get_param_values fails with tensorflow.Variable

### ISSUE THREAD

**Issue by bohan-zhang** [rlworkgroup/garage#421]
When trying to call `logger.save_itr_params` on tensorflow `Variable`'s, I got the following error in   `Parameterized`'s `get_param_values` method:
```AttributeError: 'Variable' object has no attribute 'get_value'```

To get around this issue, I tried `read_value()` and `value()` methods, and both will yield error:
```TypeError: can't pickle _thread.RLock objects```

**Comment by ryanjulian** [comment]
Can you provide a short script reproducing your bug?

`logger.save_itr_params()` takes a dictionary of pickleable keys and values, not arbitrary TensorFlow objects. TensorFlow variables are not pickleable.

`Parameterized` classes inherit the pickling interface (`__get_state__()` and `__set_state__()`) from [`Parameterized`](https://github.com/rlworkgroup/garage/blob/d5b9e633295886d91a008c9280e555ff69e02c40/garage/tf/core/parameterized.py#L19) to help pickle Tensor objects.
