### ISSUE TITLE
Gym environments should not show a plot when plot=False

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#43]
Imported from https://github.com/ryanjulian/rllab/issues/31

**Comment by gonzaiva** [comment]
Currently there's two places where the parameter plot can be set. One is in the constructor of the algorithm, and the other is in the run_experiment method. However, only the plot parameter in the former controls the plotting, while the latter only creates a worker thread that remains idle.
Should the parameter in run_experiment override the one in the algorithm constructor?

**Comment by ryanjulian** [comment]
run_experiment should override the algorithm

**Comment by gonzaiva** [comment]
Solved in #119
