### ISSUE TITLE
Library status and rllab++ compatibility

### ISSUE THREAD

**Issue by giorgionicola** [rlworkgroup/garage#432]
Hi 
me and my colleagues are planning to move some code from rllab to garage, what is yhe status of garage? Is it in a stable version or is it under heavy development (since there are a hundred of open issues)?
Moreover we use some algorithms implemented in rllab++, do you know if there is a compatible version with garage? Do you plan to integrate it in future? Otherwise do you think that moving rllab++ to garage will be very time consuming?
Thx 
Giorgio

**Comment by ryanjulian** [comment]
Hi Giogio,

Can you provide a link to rllab++? That will help me answer your question.

We use the issue tracker for tracking flaws, feature requests, ideas for improvement, minor maintenance, etc. So the number of open issues should not be considered a sign of project health.

For instance, there are only [two minor issues](https://github.com/rlworkgroup/garage/labels/bug) marked `bug`, which represents a flaw in the software which actually creates a crash or incorrect behavior. The rest of the issues mostly track maintenance activities or work-in-progress improvements for future releases.

We consider the garage v2018.10 release stable, and use it for a lot of our own research. `master` should always be considered unstable. Please see the [release announcement](https://github.com/rlworkgroup/garage/releases/tag/v2018.10.0) for more information.

Let us know if you have trouble, we're happy to help.

**Comment by ryanjulian** [comment]
I looked up rllab++ and I think it will be an easy transition--no different than moving from rllab.

Moving over should not be too time-consuming. Most interfaces are unchanged from rllab, though we have reorganized several packages.

I think that most of the changes in your code necessary to move over will be changing import paths.

If you need one of the algorithms from rllab++ which garage doesn't have, we'd welcome a pull request adding it.

**Comment by ryanjulian** [comment]
I'm going to close this issue since I haven't heard from you. Please feel free to reopen it if you have more questions or concerns.
