### ISSUE TITLE
BatchPolopt move up the hierarchy

### ISSUE THREAD

**Issue by amolchanov86** [rlworkgroup/garage#439]
Hi guys,
so one issue with the current hierarchy is that the most often modified part, such as BatchPolopt is at the lowest level of the hierarchy. Meaning every time one has to add even small changes - the whole branch ppo > npo should be copied and re-defined. 
I believe, some re-thinking of the structure is necessary.

**Comment by ryanjulian** [comment]
I'm sure this is an issue but I'm not exactly sure I understand the details or your suggested remedy. 

Can you provide an example of what you want to change and how it took a lot of work?

**Comment by amolchanov86** [comment]
Let me think about what we can do for a solution.

**Comment by ryanjulian** [comment]
okay great! it's also cool if you just point us to some code so we can see how the current system created nastiness.

**Comment by ryanjulian** [comment]
i think Keren is addressing this with his new experiment runner
