### ISSUE TITLE
Turn off special entropy features by default for NPO

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#442]
We introduced softplus entropy, negative log likelihood (btw, this feature offends an important property of entropy) as entropy into NPO. I think sometimes these features mess up the whole training at least through my observation on training sawyer environments (discovered when training sawyer reacher env with PPO). I suggest that we should turn them off by default.

**Comment by gautams3** [comment]
This was discovered when we tried to train the sawyer reacher env with vanilla PPO

**Comment by CatherineSue** [comment]
If we use `stop_gradient(entropy)`, it won't affect the training in theory, right?

**Comment by zhanpenghe** [comment]
it will.. in theory

**Comment by CatherineSue** [comment]
Could you be more specific here? After you turn off the entropy features, does the training work?

**Comment by zhanpenghe** [comment]
Training did not work without turning them off.

**Comment by ryanjulian** [comment]
Negative log likelihood is by far the most common entropy estimator from the literature, so I'm not sure how it offends anything?

softplus entropy is a hack/tuning knob which I agree should be off by default.

**Comment by ryanjulian** [comment]
The reason we have things like softplus is that PPO is much less stable with entropy than TRPO.

**Comment by CatherineSue** [comment]
This issue is addressed.
