### ISSUE TITLE
Garage Installation

### ISSUE THREAD

**Issue by TaoChenOSU** [rlworkgroup/garage#459]
When trying to install garage, these errors occurs and caused the installation process stop:
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  Release' does not have a Release file.`

Running `nvcc --version` gives me 
`nvcc: NVIDIA (R) Cuda compiler driver`
`Copyright (c) 2005-2015 NVIDIA Corporation`
`Built on Tue_Aug_11_14:27:32_CDT_2015`
`Cuda compilation tools, release 7.5, V7.5.17`

Running `nvidia-smi` says my cuda version was 10.0

**Comment by naeioi** [comment]
Could you also post preceding messages ? so we can have a better guess on the problematic line in installation script.

**Comment by TaoChenOSU** [comment]
Here are all the error messages:
`Get:1 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  InRelease`
`Ign:1 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  InRelease`
`Get:2 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  InRelease`
`Ign:2 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  InRelease`
`Get:3 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  InRelease`
`Ign:3 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  InRelease`
`Get:4 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  InRelease`
`Ign:4 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  InRelease`
`Get:5 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release`
`Err:5 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release
  File not found - /var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0/Release (2: No such file or directory)`
`Get:6 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release`
`Err:6 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release
  File not found - /var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0/Release (2: No such file or directory)`
`Get:7 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release`
`Err:7 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release
  File not found - /var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0/Release (2: No such file or directory)`
`Get:8 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  Release`
`Err:8 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  Release
  File not found - /var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0/Release (2: No such file or directory)`
`Hit:9 http://us.archive.ubuntu.com/ubuntu xenial InRelease`
`Ign:10 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease`
`Ign:11 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease`
`Hit:12 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release`
`Hit:13 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release`
`Get:14 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]`
`Get:15 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]`
`Hit:17 https://packaGet:1 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  InRelease`
`Ign:1 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  InRelease`
`Get:2 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  InRelease`
`Ign:2 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  InRelease`
`Get:3 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  InRelease`
`Ign:3 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  InRelease`
`Get:4 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  InRelease`
`Ign:4 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  InRelease`
`Get:5 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release`
`Err:5 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release
  File not found - /var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0/Release (2: No such file or directory)`
`Get:6 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release`
`Err:6 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release
  File not found - /var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0/Release (2: No such file or directory)`
`Get:7 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release`
`Err:7 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release
  File not found - /var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0/Release (2: No such file or directory)`
`Get:8 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  Release`
`Err:8 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  Release
  File not found - /var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0/Release (2: No such file or directory)`
`Hit:9 http://us.archive.ubuntu.com/ubuntu xenial InRelease`
`Ign:10 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease`
`Ign:11 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease`
`Hit:12 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release`
`Hit:13 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release`
`Get:14 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]`
`Get:15 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]`
`Hit:17 https://packages.microsoft.com/repos/vscode stable InRelease`
`Hit:19 https://download.sublimetext.com apt/stable/ InRelease`
`Hit:20 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu xenial InRelease`
`Get:21 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]`
`Reading package lists...`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  Release' does not have a Release file.`
`ges.microsoft.com/repos/vscode stable InRelease`
`Hit:19 https://download.sublimetext.com apt/stable/ InRelease`
`Hit:20 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu xenial InRelease`
`Get:21 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]`
`Reading package lists...`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release' does not have a Release file.`
`E: The repository 'file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda9.0  Release' does not have a Release file.`
 
The platform is ubuntu 16.04, python version: 2.7.12

Running `nvidia-smi` tells me the cuda version is 10.0 and driver version is 415.25.

**Comment by TaoChenOSU** [comment]
I think that solved the issue, thanks!
