### ISSUE TITLE
Bullet support

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#46]
We would like to add support for the [Bullet physics engine](https://github.com/bulletphysics/bullet3) to rllab. Thankfully, the Bullet team have recently provided Python bindings in the form of pybullet, and even provides [examples](https://github.com/bulletphysics/bullet3/tree/2.87/examples/pybullet/gym/pybullet_envs) of how to implement the `gym.Env` interface (from OpenAI Gym) using pyBullet.

This task is to add `pybullet` to the rllab `conda` environment, and implement a class (similar to `GymEnv`, e.g. `BulletEnv`) which allows any rllab algorithm to learn against pybullet environments. You will also need to implement the plot interface, if pybullet does not already, which shows the user a 3D animation of the environment. Essentially, you should duplicate the experience of running one of the MuJoCo-based examples (e.g. [trpo_swimmer.py](https://github.com/ryanjulian/rllab/blob/integration/examples/trpo_swimmer.py)), but using a Bullet environment instead. You should include examples (in `examples/` and `sandbox/rocky/tf/launchers/`) of launcher scripts which use an algorithms (suggestion: TRPO) to train the `KukaGymEnv` environment.

This is conceptually the same as [GymEnv](https://github.com/ryanjulian/rllab/blob/integration/rllab/envs/gym_env.py), which allows rllab users to import any OpenAI Gym environment and learn against them. In fact, pybullet environments implement the Gym interface, so in theory we should be done as soon as we can import pybullet. In practice, our constructor for Gym environments only takes the string name (e.g. "Humanoid-v1") of a Gym environment, not the class of a Gym environment. The pybullet environments do not have string shortcuts because they are not part of the official Gym repository. Furthermore, we'd like to use other unofficial Gym environments in rllab, but it is currently difficult for the same reason.

So you might structure this task as two pull requests (1) adding pybullet to the conda environment and (2) Modifying `GymEnv` to support arbitrary environments which implement the `gym.Env` interface (attempted in https://github.com/ryanjulian/rllab/pull/12).

Consider this a professional software engineering task, and provide a high-quality solution which does not break existing users, minimizes change, and is stable. Please always use [PEP8](https://www.python.org/dev/peps/pep-0008/) style in your code, and format it using [YAPF](https://github.com/google/yapf) (with the PEP8 setting). Submit your pull request against the `integration` branch of this repository.

Some notes:
* You can find examples of how to launch rllab in [examples](https://github.com/ryanjulian/rllab/tree/integration/examples) and [sandbox/rocky/tf/launchers](https://github.com/ryanjulian/rllab/tree/integration/sandbox/rocky/tf/launchers). Note that everything must run using the `run_experiment_lite` wrapper.
* rllab currently has two parallel implementation of the neural network portions of the library. The original is written in Theano and is found in `rllab/`. The tree `sandbox/rocky/tf` re-implements classes from the original tree using TensorFlow, and is backwards-compatible with the Theano tree. We are working towards using only one NN library soon, but for now your implementation needs to work in both trees.
* rllab is an upstream dependency to many projects, so it is important we do not break the existing APIs. Adding to APIs is fine as long as there is a good reason.

Imported from https://github.com/ryanjulian/rllab/issues/5

**Comment by ryanjulian** [comment]
See https://github.com/ryanjulian/rllab/issues/5

**Comment by naeioi** [comment]
PyBullet documentation https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.btdfuxtf2f72

**Comment by AiRuiChen** [comment]
With [#1766](https://github.com/rlworkgroup/garage/pull/1766) merged into master, now we supports all pybullet gym environments. @ryanjulian Should we close this issue?
