### ISSUE TITLE
Possible doc description error in ConvNetwork

### ISSUE THREAD

**Issue by flyers** [rlworkgroup/garage#462]
Here I think the input shape should be (height, width, channel) since the observation is flattened according to the (row, col) conventions.
https://github.com/rlworkgroup/garage/blob/77714c38d5b575a5cfd6d1e42f0a045eebbe3484/garage/tf/core/network.py#L111

**Comment by naeioi** [comment]
Hi flyers. Thanks for your report and sorry for late reply!

We don't restrict to and it is not necessarily the case that ConvNetwork input is row-wise flatted. For example, most display systems have a horizontal x axis and it's legit to define pixel storage in (x_col, y_row) convention.
