### ISSUE TITLE
Pylint complaints of bad import

### ISSUE THREAD

**Issue by naeioi** [rlworkgroup/garage#465]
Pylint wrongly complaints of bad imports as seen in https://travis-ci.com/rlworkgroup/garage/builds/97882648.

**tl;dr** Pylint get confused by the coexistence of `baselines` in deps and `garage.tf.baselines` in garage. Add an empty `__init__.py` under `garage/tf` to circumvents the problem _(As a workaround)_.

I might later add details on how pylints goes wrong under the hood.

**Comment by CatherineSue** [comment]
And for the same reason, it is confused by `theano` in deps and `garage.theano`?

**Comment by ryanjulian** [comment]
Any ideas for a fix?

**Comment by ryanjulian** [comment]
Oh is the root cause a pylint bug? What is it?

**Comment by naeioi** [comment]
Yes. I debugged Pylint and found that it will modify `sys.path` before it runs the actual checks. For each ancestor directory of a file to be checked, pylint prepends it to `sys.path` if there's no `__init__.py`. And somehow pylint messes up with duplicates names between our codebase and dependencies.

For example: before checking `garage/tf/algos/trpo.py`, `garage/tf` will be added to `sys.path` because there's no `__init__.py` under `garage/tf`. Later when pylint tests a line like `from baselines.bench import ...`, it will detect `bench` under `garage.tf.baselines` rather than the `baselines` in dependency. And that results in an import error.

**Comment by ryanjulian** [comment]
Let's just add empty `__init__.py` around the whole codebase for each package.

This requirement was removed in Python 3, but it seems that a lot of tooling doesn't respect it.

**Comment by naeioi** [comment]
Cool. I will file a PR for it.
