### ISSUE TITLE
How to use garage in a jupyter notebook?

### ISSUE THREAD

**Issue by shadiakiki1986** [rlworkgroup/garage#470]
As documented, the `run_experiment` function, which is featured in the documentation examples, launches a separate child process running a python worker for the training, and all data is saved to local files. I'm trying out `garage` in a jupyter notebook hosted on `colab.research.google.com`. Is this method also the recommended way to train a network in the jupyter notebook?

Also, I can't find any documentation on how to load the trained network and make predictions with it. Am I missing any obvious documentation?

PS: I couldn't find any stackoverflow category for `garage` to post my questions there instead of opening an issue here.

**Comment by shadiakiki1986** [comment]
Never mind. I was having unrelated usage problems that clouded my perception. The documentation is very clear already. Thanks for the great job and sorry about this :man_facepalming:

**Comment by shadiakiki1986** [comment]
For future-comers, I published a jupyter notebook gist [here](https://gist.github.com/shadiakiki1986/d2adc9c432f1d78e867b44ba7a89c80f) demonstrating how to train a policy and then see it in action

**Comment by ryanjulian** [comment]
I'd love it if you could send us a PR with your notebook (to `examples/jupyter`)

**Comment by shadiakiki1986** [comment]
Just submitted the PR. Thank you for the opportunity to contribute to your repository :smile: 

I noticed that you don't have any issues labeled with "help wanted", but please let me know if there is anything else I can contribute.
