### ISSUE TITLE
Add tf/HessianFreeOptimizer

### ISSUE THREAD

**Issue by CatherineSue** [rlworkgroup/garage#480]
Ref: 
[`garage.theano.optimizers.HessianFreeOptimizer`](https://github.com/rlworkgroup/garage/blob/3bad524a2cb80e73f4ba5f9682e519b8ab15380f/garage/theano/optimizers/hessian_free_optimizer.py)
[`garage.theano.optimizers.HfOptimizer`](https://github.com/rlworkgroup/garage/blob/3bad524a2cb80e73f4ba5f9682e519b8ab15380f/garage/theano/optimizers/hf.py)

See: #331, #477

**Comment by ryanjulian** [comment]
This doesn't seem to be used by anything. We can always revisit if it's used for some method.
