### ISSUE TITLE
Permanent fix for 'GLEW initalization error: Missing GL version' on Linux machines

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#5]
Right now the temporary solution to this issue is prepend `python examples/xxx.py` with `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so:/usr/lib/nvidia-384/libGL.so`; note that you must replace `nvidia-384` to the one installed on your machine (use `nvidia-smi` to determine the driver version currently in use). Relevant comments are [here](https://github.com/deepmind/dm_control/issues/3#issuecomment-355153027) and [here](https://github.com/openai/mujoco-py/pull/145#issuecomment-356938564), and this [link](https://github.com/lobachevzky/mujoco) is a wrapper written as a temporary fix.

However, the more permanent solution would require pre-loading without the use of `LD_PRELOAD` on the command line. See DeepMind's [implementation](https://github.com/deepmind/dm_control/commit/3b736812407d821ec5d48bdea08ac53e00d78d2e) as a starting point.

Imported from https://github.com/ryanjulian/rllab/issues/117

**Comment by cheng-kevin** [comment]
This a bit of a blocker for running continuous benchmarking.  We may want to escalate this issue when we run on multiple machines with various drivers.  I can hack around the issue with the temp solution for now.

**Comment by ryanjulian** [comment]
There is a well-known workaround. This bug is about not having to use it.
