### ISSUE TITLE
Relaxing Mujoco Key install requirement

### ISSUE THREAD

**Issue by ancorso** [rlworkgroup/garage#509]
I am currently using garage for an RL project where I am running Travis-CI. Currently, garage requires a MuJoCo key to install, so I am having to include a key with my repo so that Travis-CI has access to it for the fresh install on each build. My project doesn't use MuJoCo so it would be great if the MuJoCo key requirement could be relaxed for installation.

Thanks!

**Comment by ryanjulian** [comment]
Hi Anthony -- thanks for the FR!

Previously mujoco_py required a key for installation, but that was recently relaxed to only checking that a key is present.

If you take a look at our most recent [Dockerfiles](https://github.com/rlworkgroup/garage/tree/master/docker) (which we use in our own TravisCI), we recently edited them to use an empty `mjkey.txt` for building the file. I think you should be able to do the same with the setup script (just pass it an empty mjkey).

I'll keep this open as a housecleaning item to edit the setup scripts. We'd love it if you could send us a PR with the change you're suggesting.

For running garage in TravisCI, I highly recommend your checkout our [.travis.yml](https://github.com/rlworkgroup/garage/blob/master/.travis.yml) and [Dockerfiles](https://github.com/rlworkgroup/garage/tree/master/docker). Many hours have been sacrificed to get this whole suite running in CI. The installation script will probably burn a lot of your build minute quota, so I recommend running with Docker and retrieving the pre-built Dockerfile cache. You should be able to find our latest prebuilts on [Docker Hub](https://hub.docker.com/u/rlworkgroup).

**Comment by ancorso** [comment]
This is great, thanks! I will try out your suggestions and submit a PR if I can get it working.

**Comment by ancorso** [comment]
Hi Ryan, 

I've made the changes to the setup scripts but I'm new to using PRs and I'm not sure how to submit one. I read through the CONTRIBUTING.md explanation and here is what I did:

- Installed all of the pre-commit checks 
- Created a new branch called "features/setup-without-mjkey"
- Made the changes
- Committed the changes (all of the pre-commit checks passed)
- Tried to push the changes

But then I got a "permission denied" response from the server. Do I need permissions to submit a new branch or have I done something else wrong?

Thanks! (and sorry for my naivete on this!)

**Comment by ryanjulian** [comment]
Hi Anthony,

Generally PRs are submitted from one fork to another. What you need to do is create your own fork of garage (use the fork button on GitHub), then commit and push to your account, and then submit a PR from your fork to ours.

See: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Note that the options in that script are generated using https://argbash.io/. If you want to edit the options, you will have to regenerate part of the file (it's clearly marked with comments). Make sure to edit both setup_linux.sh and setup_macos.sh

**Comment by krzentner** [comment]
This is fixed by #858
