### ISSUE TITLE
GaussianMLPRegressor is not unpickled appropriately

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#511]
Sorry I can't come up with a good title for this but I will describe the problem in details here.

GaussianMLPRegressor has variables (e.g. [`y_mean`](https://github.com/rlworkgroup/garage/blob/f33a03ea4d71525eabadbe22f31ad0a91607b134/garage/tf/regressors/gaussian_mlp_regressor.py#L156)) that are created for normalizing the inputs and they are not saved during pickling. This will force user to run a variable initialization when they want to use an unpickled GaussianMLPBaseline. However, running initialization will re-initialize the model variables.

This will affect people who want to use a pickled baseline object to resume training or use them to do further learning.

**Comment by ryanjulian** [comment]
I think @gautams3 also saw this.

I think @ahtsan is addressing this in his models PR

**Comment by ryanjulian** [comment]
@zhanpenghe is this fixed?

**Comment by zhanpenghe** [comment]
I don't think this is fixed. `GaussianMLPRegressor` is not using garage model and I believe it is still using the same mechanism to serialize.

**Comment by ryanjulian** [comment]
@ahtsan will this be fixed if we use the model-based regressor?
