### ISSUE TITLE
Refactor DeterministicMLPPolicy to use garage.tf.model

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#521]
* [x] DeterministicMLPPolicy

**Comment by ahtsan** [comment]
I think you are referring to #526 and we need another separate issue for DiscreteMLPPolicy.

**Comment by ryanjulian** [comment]
DiscreteMLPQFunction already uses Model

**Comment by ahtsan** [comment]
Yes but we don't have `DeterministicMLPPolicy` anymore

**Comment by ryanjulian** [comment]
i'm not sure what you mean, but just go update/create issues as you see fit :)

**Comment by ahtsan** [comment]
I thought we have to rename `DeterministicMLPPolicy` to `ContinuousMLPPolicy`. It should be We won't have `DeterministicMLPPolicy` anymore, and I realized this issue is under `Parallel implementation complete` so everything is good.

**Comment by ahtsan** [comment]
based by #574

**Comment by ahtsan** [comment]
This is no longer needed since `DeterministicMLPPolicy` will no longer exist and be replaced by `ContinuousMLPPolicy`, which is already tracked by #526
