### ISSUE TITLE
How to use garage with ros?

### ISSUE THREAD

**Issue by PorkPy** [rlworkgroup/garage#536]
to whom it may concern, well done for keeping this project running, I think it's awesome.
The original rllab had ros utils but these seem to have been removed in garage. What is the best way to integrate garage with ros to work with real robots? 
I am trying to control a UR5 and test it using as many of the algorithms in garage as possible. I don't know if I should somehow have a ros node read/write to some part of garage or if I should try and recreate parts of garage within ros itself with rospy. ??? I'm really struggling to understand the communications. 
fyi: I'm using ros kinetic, ubuntu 16.04, ur_modern_driver/urscript + jog_arm.
Many thanks.

**Comment by zhanpenghe** [comment]
Hi @PorkPy, we have moved utilities and environments for real robots to other repositories. As an example, [rlworkgroup/gym-sawyer](https://github.com/rlworkgroup/gym-sawyer) has our implementations of environments that include a sawyer robot. It contains both mujoco environments and ros environments. [Block world](https://github.com/rlworkgroup/gym-sawyer/blob/77cb252c02c3c9c39d78d5050bc672273447f617/sawyer/ros/worlds/block_world.py#L84) has some examples how we integrate vicon system with our real robot environments.

**Comment by ryanjulian** [comment]
thanks @zhanpenghe, you beat me to it.

gym-sawyer contains a fairly-general set of ROS bindings for garage + some Sawyer-specific stuff. Please feel free to fork it and add UR5 support (which we would love to have). I think you'll find the Dockerfiles particularly helpful for getting everything to work together.

If we get a critical mass of code there we could eventually split the ROS parts into an independent garage-ros package.

**Comment by PorkPy** [comment]
Hi @zhanpenghe @ryanjulian 
Thanks for your support. We do have a vicon system but I've not thought of using it. I'm attempting to recreate the gym-sawyer installation but with the UR5 following this tutorial: 
https://github.com/rlworkgroup/gym-sawyer/blob/77cb252c02c3c9c39d78d5050bc672273447f617/sawyer/ros/envs/sawyer/README.md
However, the tutorial says to use the 'garage' python when using catkin_make which for me is located in 
/home/dom/miniconda2/envs/garage/bin/python and is python 3.6.
But my ros_ws won't compile using this python. It works fine with the 
/user/bin/python which is 2.7
Heres the output from catkin_make:
![image](https://user-images.githubusercontent.com/35999620/53423013-6f079d80-39d8-11e9-8d67-dde71124c482.png)
I've tried with system-wide catkin_make and inside conda-garage env with and without root. 
Any ideas?

**Comment by PorkPy** [comment]
I managed to get the ros_ws to compile, but I'm not sure why it did all of a sudern?? 
I kept altering $PYTHONPATH and exporting $GARAGE_PYTHON source .bashrc, source /opt/ros/kinetic/setup.bash. so I'm not sure which actions were ultimatly responsable for my success. 
Sparse reward fail!
My last two actions were:
~/ros_ws$ export GARAGE_PYTHON=/home/dom/miniconda2/envs/garage/bin/python
and
~/ros_ws$ catkin_make -DPYTHON_EXECUTABLE:FILEPATH=$GARAGE_PYTHON
which I have of course I did originally but it didn't work then.
I'll have another go in a different workspace to try and recreate it.

**Comment by ryanjulian** [comment]
@utkarshjp7 is the expert here

**Comment by ryanjulian** [comment]
@PorkPy please let us know if the Dockerfiles/gym-sawyer work out for you. if you have more questions, please feel free to reopen this issue.

**Comment by utkarshjp7** [comment]
@PorkPy  Apologies for the late response. You can find an example of compiling a python2 ros_ws with garage python at [here](https://github.com/rlworkgroup/gym-sawyer/blob/master/docker/Dockerfile.garage_ros_intera).

**Comment by PorkPy** [comment]
Hi @ryanjulian @utkarshjp7 ,
I had at combining Garage with ROS using this tutorial 
'https://github.com/rlworkgroup/gym-sawyer/blob/master/sawyer/ros/envs/sawyer/README.md'
But I got a bit lost once I got to the INTERA ROBOT SDK. I couldn't figure out what Universal Robots equivalent files I should use or if I needed to do any of that at all??
Because that wasn't working for me, I tried 'https://github.com/kindredresearch/SenseAct', which worked quite well but only for early universal robot software versions. I cant get it to work for UR1.5 which is a minimum for communicating with the Robotiq gripper. 
But anyway I thought it would provide a good base for integration into Garage and if you look through the code you'll see that it's designed to work with rllab! Weird!
I'll have a look at that link above next, thanks @utkarshjp7 . 
I'm starting to think that maybe I should have just had an entire reinforcement learning script plugged into a ROS node. Would that have been simpler, rather than all this convoluted systems integration? 
I also had the idea of running my RL script on MATLAB which can connect to ROS or my ur5/10 directly, but I've been told by other people that Matlab uses a lot of resources. It's driving me insane! 
I really need to get something working soon!

Thanks again guys!

**Comment by ryanjulian** [comment]
The pattern I recommend is to keep your robot on one node and the RL algorithm in a different node, and define a good message API between them. I recommend this because it might be very difficult to get all the dependencies for ROS + robot-specific API + RL to agree on a single machine.

Those nodes could be on the same machine (using Docker) if latency is a concern.

From there, you just need to define a Python API which will make your robot look like an openai/gym environment, e.g. implements the interface `gym.Env`.

**Comment by PorkPy** [comment]
hi @ryanjulian ,

Sorry to keep asking you but you've been so helpful so far. Maybe I should get off this issue page??
So I've recently been told that if I'm using some module like tensorflow, I can build a learning algorithm in a ros-node and the tensorflow and other libraries that my script calls don't need to be wrapped up in some ros-package in order to be found by ROS. Does this sound correct?
That would suggest I can just call garage the same way in my script and ROS should find it. 
Just import garage???
I have a feeling this is very wrong but I don't know why, but I suspect it will be due to ROS using python2.7 and garage using python3.6. 

What if the RL policy posed its output to a buffer and I then use ROS to source that buffer and convert the policy output into robot actions? Dose that sound fesable?  

Cheers, Dom.
