### ISSUE TITLE
Broken tests result in green CI

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#542]
See https://travis-ci.com/rlworkgroup/garage/builds/102405158

I suspect this has something to do with Docker and/or make

**Comment by gonzaiva** [comment]
The root cause is that the exit status when an command fails in [check_tests.sh](https://github.com/rlworkgroup/garage/blob/master/scripts/travisci/check_tests.sh#L3) is not passed to the parent process. This can be fixed by adding `set -e` to the script.

**Comment by ryanjulian** [comment]
Can you point me to before/after TravisCI links which show this fixes the problem?

**Comment by gonzaiva** [comment]
How can I re-run your build to see if it fails now that is merged? Since all the tests in nose2 are passing [right now](https://travis-ci.com/rlworkgroup/garage/builds/102543187), should I introduce an error in the tests to make sure is detected?

**Comment by ryanjulian** [comment]
thanks. please let me know when it finishes

**Comment by gonzaiva** [comment]
Logs are here. For both, I failed the test `test_output_shape` on purpose. The first one doesn't consider my fix and the CI still passes:
https://travis-ci.com/rlworkgroup/garage/builds/102551165
Second one considers my fix and fails the CI:
https://travis-ci.com/rlworkgroup/garage/builds/102553337
