### ISSUE TITLE
Finish continuous benchmarking

### ISSUE THREAD

**Issue by cheng-kevin** [rlworkgroup/garage#548]
Minimal:
- Set up job in RESL Server (NICE priority low)
- Run all benchmark files in tests/benchmarks with no intervention
- Fix TRPO
Additional Features:
-Decide/Design datastore
-Download policies
-Keep Timeline of progress.json to track regressions

**Comment by ryanjulian** [comment]
Can you split these into different issues and then add them to https://github.com/rlworkgroup/garage/projects/7?
