### ISSUE TITLE
commit #585 breaks setup scripts

### ISSUE THREAD

**Issue by singulaire** [rlworkgroup/garage#594]
5 days ago, commit e5dca58a7e3d9054a6afaa0c596774bbf24458af deleted `garage/config_personal_template.py`. However, the setup scripts `setup_linux.sh` and `setup_macos.sh` still reference it in the line
````cp garage/config_personal_template.py garage/config_personal.py````
which causes setup to error out.

**Comment by gonzaiva** [comment]
I have pushed PR #595 to solved this bug. Thanks a lot!
