### ISSUE TITLE
Model class unit test flaw

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#608]
The tests for pickling models, e.g. GaussianMLPModel, do not test the weights pickling correctly. If `pickle.dumps` is called in another session, rather than the session the model is built, it will not be able to get the weights.

TODO: Fix the test and state clearly in the documentation.

**Comment by ryanjulian** [comment]
I don't think it would ever be possible (under TF<2.0) to dump from outside the session the model was built in.

**Comment by ahtsan** [comment]
How about a nested session? The `tf.get_default_session()` will still get the wrong session and hence it cannot get the variables from the correct scope.
