### ISSUE TITLE
dist_info_sym has wrong shapes

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#610]
The reshape operations that are performed in `dist_info_sym` are not correct. I suggest just remove them now. For example: https://github.com/rlworkgroup/garage/blob/d8c279e1573ab16fa4c9ba7a89a0cc5012f0caac/garage/tf/policies/gaussian_mlp_policy_with_model.py#L104

**Comment by ahtsan** [comment]
Why is it not correct? If action space shape is (2, 2), since the output shape of the model will be `env_spec.action_space.flat_dim`, which is (1, 4), but we actually want it to be (2, 2).

**Comment by ryanjulian** [comment]
I think this is an API transition problem.

The API for the existing primitives/distributions assumes that all distributional operations happen in flattened space. Anson would like an API where all operations are assumed to be in dense space.

In the long term, we should probably choose the option that makes it easiest to interoperate with `tfp.distributions` and `torch.distributions`.

For now, I suggest we:
1. Make the model-based primitives use the existing flat API, so we can transition algorithms quickly
2. Move dense operations to the namespace `*_dense`, i.e. `Policy.dist_info_sym_dense()`

Hopefully all of these `dist_info` operations will disappear shortly anyway, so it's not worth it to spend time on a lengthy refactor.

**Comment by ahtsan** [comment]
Resolved by #615 
(https://github.com/rlworkgroup/garage/blob/050f278d77b1a4982c14285fdc2c780d57d31194/garage/tf/policies/gaussian_mlp_policy_with_model.py#L103)

**Comment by ryanjulian** [comment]
please close it if you both agree it's fixed

**Comment by zhanpenghe** [comment]
@ryanjulian As far as I understand so for now we just remove the reshape?

**Comment by ryanjulian** [comment]
The goal is that (eventually) all outputs respect the batch and value shapes specified by action_space, observation_space, etc.

These `_sym` methods flatten them all (they don't respect the shapes), but we are hoping to delete them as soon as Models are working anyway. So I don't think it's worth unflattening on principle.

**Comment by zhanpenghe** [comment]
Ok then I think this is good for me.
