### ISSUE TITLE
No advantage normalization for recurrent policy

### ISSUE THREAD

**Issue by jaekyeom** [rlworkgroup/garage#620]
In [garage/tf/algos/npo.py](https://github.com/rlworkgroup/garage/blob/master/garage/tf/algos/npo.py), it normalizes the advantages if `self.center_adv` is `True`, but only for non-recurrent policies.
Is this intentional?

**Comment by ryanjulian** [comment]
@jaekyeom I think this might be a bug. Thanks for pointing it out.

**Comment by ryanjulian** [comment]
@CatherineSue can  you take a look?

**Comment by CatherineSue** [comment]
Hi @jaekyeom, thanks for catching the bug! I've opened #626 to fix the problem. Feel free to review it if you'd like to.
