### ISSUE TITLE
Estimate entropy in NPO

### ISSUE THREAD

**Issue by maxiaoba** [rlworkgroup/garage#628]
In line 417 of npo.py, should 
policy_neg_log_likeli_valid = self.policy.distribution.log_likelihood_sym(...)
actually be
policy_neg_log_likeli_valid = -self.policy.distribution.log_likelihood_sym(...)?

The same for line 395.

**Comment by ryanjulian** [comment]
@CatherineSue can you take a look?

**Comment by ryanjulian** [comment]
@maxiaoba I think you're right and it might explain why we had to turn off entropy-regularization a few months ago. 

@CatherineSue PTAL

**Comment by CatherineSue** [comment]
Hi @maxiaoba , you are correct that there should be a negative sign. I've fixed this in #632 .

**Comment by maxiaoba** [comment]
Cool. Thanks!
