### ISSUE TITLE
Move process_samples() from sampler to algorithm

### ISSUE THREAD

**Issue by naeioi** [rlworkgroup/garage#646]
`process_samples()` takes raw batch data and generates fields that are useful in algorithm training. Currently, it resides in sampler and runner uses it to process batch data before piping to the algorithm. This is problematic for several reasons, 
- An algorithm may need a different preprocessing procedure but has not control of it.
- For off-policy sampler, the last path in one batch might not be complete. This will make the logging of return not accurate. (Only logging of **complete** path is accurate because it reflects the performance of an algorithm). 
Currently, the `process_samples()` of off-policy sampler wipes out the `done` from raw data. If we make the algorithm accepts raw data and do preprocessing itself, it can test if a path is complete and avoid logging it if not.

We can fix these issues by moving process_samples() from sampler to algorithm. Right now all on-policy algorithms share the same preprocessing procedure. We can make it at the base class, and only override it in a new algorithm implementation when necessary.

**Comment by zequnyu** [comment]
@naeioi One quick question: do all the tf/np algorithms need process_samples()? Then I suppose I should put the method to `garage.np.algos.RLAlgorithm`. Or just tf algorithms because I saw no samplers in the np folder.

**Comment by naeioi** [comment]
> do all the tf/np algorithms need process_samples()?

Yes. 

The fact is that currently, np algorithms use sampler under `garage.tf.samplers`. Check out https://github.com/rlworkgroup/garage/blob/master/examples/np/cem_cartpole.py

This is because even though np algorithms do not use a tensorflow optimizer, they still need a policy, and we have only polices implemented in tensorflow. 

> I should put the method to garage.np.algos.RLAlgorithm

I think an abstract `process_samples()` should be defined in `garage.np.algos.RLAlgorithm`. And `process_samples()` in `garage.tf.samplers.BatchSampler` should be moved to `BatchPolopt` in `gararge.np/tf.algos`, also `process_samples()` in `garage.tf.samplers.OffPolicyVectorizedSampler` should be moved to `garage.tf.algos.OffPolicyRLAlgorithm`.
