### ISSUE TITLE
Refactor experiment and experiment_wrapper

### ISSUE THREAD

**Issue by zequnyu** [rlworkgroup/garage#657]
> We have long been starting a experiment using garage/experiment/experiment_wrapper.py. It does a bunch of stuff to setup an experiment. Among the most important are logger configuring and support for experiment variant. Experiment variant means that you can start a number of experiment using a set of different parameters. We are using this feature in benchmark. There are other features in experiment wrapper, which are obsolete, not maintainable and not testable, that make us want to write it.

**Comment by ryanjulian** [comment]
This is very vague so I think we should break the project down further. I will close this.
