### ISSUE TITLE
ERWR positive_adv set to True?

### ISSUE THREAD

**Issue by zequnyu** [rlworkgroup/garage#673]
I'm trying to remove `kwargs` out of all the algorithms. In ERWR the default `positive_adv` is set to True. When it passing to VPG, then NPO, the `self.positive_adv` is never set, so [line 279](https://github.com/rlworkgroup/garage/blob/a5277f42912e654bc5f0cb541d4557ca3a2c0bb4/garage/tf/algos/npo.py#L279) in `npo.py` is never reached. Not sure if this is the intention. The test won't pass if `self.positive_adv` in NPO is set. Would you please check it? @ahtsan

**Comment by CatherineSue** [comment]
I think it is set in tf.algos.BatchPolopt [here](https://github.com/rlworkgroup/garage/blob/master/garage/tf/algos/batch_polopt.py#L52)?

**Comment by zequnyu** [comment]
Thank you @CatherineSue .
