### ISSUE TITLE
Merge or delete contrib.alexbeloi

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#685]
I can't find a citation for this method, so it's hard to know if it's implemented correctly. It's fairly basic and might be a useful baseline for on-policy algorithms, so it's worth having someone attempt to merge it.

If it proves too difficult, we should just remove it.

**Comment by zequnyu** [comment]
Is the `garage.sampler.BatchSampler` still useful?

@ryanjulian Do you want to merge it as a `tf` sampler?

**Comment by ryanjulian** [comment]
Yes, `garage.sampler.BatchSampler` is still useful.

The scope of this PR is to move https://github.com/rlworkgroup/garage/blob/master/src/garage/contrib/alexbeloi/is_sampler.py into the `garage.sampler` package (and add tests). If it is too hard, we will delete it instead.

**Comment by zequnyu** [comment]
Closed by merging #717.
