### ISSUE TITLE
Refactor Categorical primitives to use a distribution

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#694]
This would create Categorical* models in tf/models and use a tfp.distributions.Multinomial to model the distribution, rather than using action_space.weighted_sample().

**Comment by ahtsan** [comment]
Should it be `tfp.distributions.OneHotCategorical`?

**Comment by ryanjulian** [comment]
You are the expert here.

**Comment by ryanjulian** [comment]
@ahtsan is this done?

**Comment by ahtsan** [comment]
Not all primitives are covered, e.g. CategoricalMLPRegressor.

**Comment by ryanjulian** [comment]
Is that the only one missing?

**Comment by ahtsan** [comment]
I think so

**Comment by ahtsan** [comment]
I filed a separate issue for CategoricalMLPRegressor.
