### ISSUE TITLE
use_gpu and use_tf apparently have no effect

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#698]
```python
from garage.experiment import LocalRunner, run_experiment
from garage.np.baselines import LinearFeatureBaseline
from garage.tf.algos import TRPO
from garage.tf.envs import TfEnv
from garage.tf.policies import CategoricalMLPPolicy

def run_task(*_):
with LocalRunner() as runner:
env = TfEnv(env_name='CartPole-v1')

    policy = CategoricalMLPPolicy(
        name='policy', env_spec=env.spec, hidden_sizes=(32, 32))

    baseline = LinearFeatureBaseline(env_spec=env.spec)

    algo = TRPO(
        env_spec=env.spec,
        policy=policy,
        baseline=baseline,
        max_path_length=100,
        discount=0.99,
        max_kl_step=0.01)

    runner.setup(algo, env)
    runner.train(n_epochs=100, batch_size=4000,plot=True)
run_experiment(
run_task,
snapshot_mode='last',
seed=4,
n_parallel=4,
plot=True,
use_tf=False,
use_gpu=False

)
```
ref #697 

@xht033

**Comment by ryanjulian** [comment]
@xht033

* `use_tf` is outdated and should be removed. it has no effect on whether your experiment uses tensorflow.
*`use_gpu` should be working -- how did you conclude that the GPU is being used?

**Comment by xht033** [comment]
when I use nvidia-smi :
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   48C    P2    30W /  N/A |   5996MiB /  6069MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1097      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1132      G   /usr/bin/gnome-shell                          48MiB |
|    0      1586      G   /usr/lib/xorg/Xorg                           186MiB |
|    0      1699      G   /usr/bin/gnome-shell                         252MiB |
|    0      2111      G   ...quest-channel-token=3451797686862221713   110MiB |
|    0     10672      C   python                                      5373MiB |
|    0     32406      G   /home/haitao/anaconda3/bin/python              2MiB |
+-----------------------------------------------------------------------------+

**Comment by xht033** [comment]
when I use nvidia-smi, it shows my gpu is used:
|    0     10672      C   python                                      5373MiB |

but now **use_gpu = False**

**Comment by ryanjulian** [comment]
Do you have python package `tensorflow` or `tensorflow-gpu` installed? What is the output of `pip freeze` inside your garage conda environment?

**Comment by xht033** [comment]
pip freeze in conda environment:
`absl-py==0.7.1
akro==0.0.2
alabaster==0.7.12
aspy.yaml==1.3.0
astor==0.8.0
astroid==1.6.6
atari-py==0.1.15
Babel==2.7.0
baselines==0.1.5
boto3==1.9.157
botocore==1.12.157
box2d-py==2.3.8
cached-property==1.5.1
certifi==2019.3.9
cffi==1.12.3
cfgv==2.0.0
chardet==3.0.4
Click==7.0
cloudpickle==1.1.1
cma==1.1.6
coverage==4.5.3
cycler==0.10.0
Cython==0.29.9
decorator==4.4.0
dill==0.2.9
dm-control==0.0.0
docutils==0.14
dowel==0.0.2
editdistance==0.5.3
entrypoints==0.3
enum34==1.1.6
flake8==3.7.7
flake8-docstrings==1.3.0
flake8-import-order==0.18.1
flake8-polyfill==1.0.2
Flask==1.0.3
future==0.17.1
futures==3.1.1
-e git+https://github.com/rlworkgroup/garage.git@e0da81386510954eec5c6162cc9aa9d0cba8f199#egg=garage
gast==0.2.2
glfw==1.8.1
grpcio==1.21.1
gym==0.12.4
h5py==2.9.0
identify==1.4.3
idna==2.8
imageio==2.5.0
imagesize==1.1.0
importlib-metadata==0.0.0
importlib-resources==1.0.2
isort==4.3.20
itsdangerous==1.1.0
Jinja2==2.10.1
jmespath==0.9.4
joblib==0.12.5
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
lockfile==0.12.2
lxml==4.3.3
Mako==1.0.10
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
metaworlds==0.0.2.dev0
mkl-fft==1.0.6
mkl-random==1.0.1
mock==3.0.5
mpi4py==3.0.1
mujoco-py==2.0.2.2
networkx==2.3
nodeenv==1.3.3
nose2==0.9.1
numpy==1.14.5
opencv-python==4.1.0.25
packaging==19.0
pandas==0.24.2
pep8-naming==0.7.0
Pillow==6.0.0
plotly==1.9.6
pre-commit==1.16.1
progressbar2==3.39.3
protobuf==3.8.0
psutil==5.6.2
pycodestyle==2.5.0
pycparser==2.19
pydocstyle==3.0.0
pyflakes==2.1.1
pygame==1.9.6
pyglet==1.3.2
Pygments==2.4.2
pylint==1.9.2
PyOpenGL==3.1.0
pyparsing==2.4.0
PyPrind==2.11.2
python-dateutil==2.8.0
python-utils==2.3.0
pytz==2019.1
PyWavelets==1.0.3
PyYAML==5.1
pyzmq==18.0.1
requests==2.22.0
s3transfer==0.2.0
scikit-image==0.15.0
scipy==1.3.0
six==1.12.0
snowballstemmer==1.2.1
Sphinx==2.0.1
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
tabulate==0.8.3
tensorboard==1.13.1
tensorboardX==1.7
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tensorflow-probability==0.6.0
termcolor==1.1.0
toml==0.10.0
tqdm==4.32.1
urllib3==1.25.3
virtualenv==16.0.0
viskit==0.0.4.dev0
Werkzeug==0.15.4
wrapt==1.11.1
yapf==0.27.0
zipp==0.5.0
zmq==0.0.0
`

**Comment by xht033** [comment]
conda list tensorflow:
`# Name                    Version                   Build  Channel
tensorflow                1.13.1          gpu_py36h3991807_0  
tensorflow-base           1.13.1          gpu_py36h8d69cac_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0  
tensorflow-probability    0.6.0                    pypi_0    pypi
`
