### ISSUE TITLE
Nightly gym tests are failing

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#706]
This appears to be an out-of-memory bug related to MuJoCo viewer windows not closing. We probably need to update the custom code for closing environments

Sample failure: https://travis-ci.com/rlworkgroup/garage/jobs/204138951#L1052
mujoco_py bug: https://github.com/openai/mujoco-py/issues/357

**Comment by ryanjulian** [comment]
Please prioritize this. A red build badge every day makes the project look bad.

**Comment by gitanshu** [comment]
#724 fixes the MjViewer windows not closing. However, I noticed that the windows for envs gym.envs.box2d, gym.envs.classic_control and gym.envs.atari don't close their windows either. Maybe i should manually close them too. What do you think?
Also how can i trigger nightly tests on CI manually?

**Comment by ryanjulian** [comment]
yes -- the regression might have spread to other gym suites. whenever you detect that the window closing is not working, please update the test suite to close them manually.

**Comment by ryanjulian** [comment]
new failures https://travis-ci.com/rlworkgroup/garage/jobs/211907313#L1310
