### ISSUE TITLE
Exception has occurred: ImportError cannot import name 'broadcast_to'

### ISSUE THREAD

**Issue by yongqianxiao** [rlworkgroup/garage#712]
**from tensorflow.python.ops.gen_array_ops import broadcast_to** arose a Exception:
**Exception has occurred: ImportError cannot import name 'broadcast_to'**

my TensorFlow version is **1.8**, and my python version is **3.6**. I can't find a class or a method named **broadcast_to** in the **gen_array_ops.py**

Can anyone tell me what's wrong?

**Comment by ryanjulian** [comment]
the current `setup.py` lists TF1.12 as the dependency.

Nothing is guaranteed to work unless you have installed dependencies exactly as specified.

I'm going to close this issue. If you still have this problem when using the specific dependencies, please reopen.

**Comment by yongqianxiao** [comment]
@ryanjulian OK， thanks
