### ISSUE TITLE
test_trpo_gru_cartpole is flaky

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#720]
https://travis-ci.com/rlworkgroup/garage/jobs/205552438#L730

**Comment by ryanjulian** [comment]
@ahtsan is this fixed by #785?

**Comment by ahtsan** [comment]
will be fixed by #786

**Comment by zequnyu** [comment]
Tested in my laptop 5 times and got mostly 74.XX < 80 (current threshold)

**Comment by ahtsan** [comment]
it's a matter of random seed -- if I set `seed=2`, it converges to 100 within 10 epochs. We can also let it run 15 epochs so it can converge with the default seed. @ryanjulian What do you think?

**Comment by ryanjulian** [comment]
If it's a matter of seed, please send a PR to update the seed used by the test. This is failing all of our builds every night, so we don't want to wait for a more stable implementation. The point of the test is to detect obvious regressions, it's sufficient to verify a `(seed, performance)` tuple.
