### ISSUE TITLE
Pin akro version and resolve bugs

### ISSUE THREAD

**Issue by lywong92** [rlworkgroup/garage#731]
- pin arko version
- resolve a bug in pytorch mlp module: module is not constructed correctly when hidden_nonlinearity is defined as None

**Comment by ryanjulian** [comment]
Can you describe the bug? i.e. how to reproduce it, expected output, actual output?

**Comment by zhanpenghe** [comment]
@ryanjulian Last night `akro` was refactored but garage never pins the version number of akro so I asked @lywong92 to pin the version number to `0.0.2` for a quick fix so that others' tests won't fail. 

Of course, `garage`'s `akro` should be bumped to `0.0.3` soon.

**Comment by ryanjulian** [comment]
Ah. Seems like there should be 2 issues filed then. one for akro, one for the MLPModule
