### ISSUE TITLE
Refactor CEM and CMA_ES to use new train method in Algorithm

### ISSUE THREAD

**Issue by zequnyu** [rlworkgroup/garage#736]
To refactor CEM and CMA_ES to conform to new interface introduced by #728, so that they don't depend on itr to determine the stage.

**Comment by zequnyu** [comment]
> CEM and CMA still need refactoring to conform to this new interface, so that they don't depend on itr to determine the stage, and n_samples should be gone after refactoring.

After some attempts I feel our current code is probably ok. `train_once()` and `process_samples()` need `itr`, and I think `train_once()` is a good place to determine the stage.
For `n_epoch_cycles`, it's hard to remove from `LocalRunner`. We can, however, remove it from the algorithms, which will result in more integration between our runner and algos. Is this what you are looking for? @naeioi

**Comment by ryanjulian** [comment]
@zequnyu will this be covered by your new PR to remove n_epoch_cycles?

**Comment by zequnyu** [comment]
Closed by #1093.
