### ISSUE TITLE
Difference between GaussianMLPPolicy and GaussianMLPPolicyWithModel

### ISSUE THREAD

**Issue by ilinojkovic** [rlworkgroup/garage#746]
What is the difference between GaussianMLPPolicy and GaussianMLPPolicyWithModel? I couldn't find much documentation on this, and from the code, it seems that they provide the same functionality but implemented in different ways.

**Comment by ryanjulian** [comment]
We are currently working on removing an [old, custom neural network layers library](https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/core/layers.py) and replacing it with vanilla TensorFlow and a new abstraction called Models.

We are implementing the new versions of each primitive in parallel, and the new version of each primitive has the name "WithModel." 

In the near future (2-3 weeks), we will refactor the "WithModel" versions to replace the originals, and delete the original implementations. e.g. "GaussianMLPPolicyWithModel" will just become "GaussianMLPPolicy."
