### ISSUE TITLE
Docs builds are failing

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#755]
This is both on `master` and the `fix_docs_gen` branch. It appears to be a TensorFlow install error in the rtfd environment.

See:
https://readthedocs.org/projects/garage/builds/9260419/
https://readthedocs.org/projects/garage/builds/9260420/

**Comment by gitanshu** [comment]
Looks like changing the python interpreter from 2.x to 3.x in rtfd advanced settings broke master.
[This commit](https://github.com/rlworkgroup/garage/commit/44fb818d9dadbf85cb63c1a7ebcaae735e1fa8e4) fixes it by forcing python 3.6 since tf doesn't support 3.7, but then rtfd tries to fetch dm_control from pypi instead of github and [fails there](https://readthedocs.org/projects/garage/builds/9284984/)

**Comment by ryanjulian** [comment]
ReadTheDocs appears to be trying to use easy_install to attempt to install the package, which is a really old way of installing python packages.

easy_install fails to properly parse the [PEP508](https://www.python.org/dev/peps/pep-0508/) string used to declare the git-based dependency for dm_control in setup.py

I attempted to force it to use pip to install with [this commit](https://github.com/rlworkgroup/garage/commit/e6119bd1e5235f970ef6dd3c75789c9feedc5f04) -- we will see what the results are.

**Comment by gitanshu** [comment]
Still the same :|

**Comment by ryanjulian** [comment]
My attempt got a little farther, but is still hanging up on dm_control and mpi4py installs, because we can't get some C-based libraries (e.g. mujoco) on ReadTheDocs.

Is install required to generate the apidoc?

If so, I think we will have to create a special requirements file which omits the offending packages, then mock them out using autodoc_mock_imports. There is a guide [here](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules). 

TODO:
* Determine if install is required to generate the API doc
* Create docs/requirements.txt which lists the install dependencies only for documentation and omits the offending packages
* Add appropriate autodoc_mock_imports config
* File a bug to investigate pbr, pyproject.toml, and other ways of unifying requirements lists separate from setup.py
