### ISSUE TITLE
Remove check_flake8.sh

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#758]
This was created to help us check new code for flake8 compliance, even though the codebase at the time was really bad.

We now have brought the codebase up-to-date, and check_flake8 is no longer needed.

This can be done as soon as #409 is closed.

It will require:
* Switching .pre-commit-config.yaml to use the default flake8 check
* Verifying that flake8 still catches problems in the CI (in test, examples, src, and root)
* Verifying that flake8 still catches missing documentation in the CI for new code

**Comment by gitanshu** [comment]
Closed by #844
