### ISSUE TITLE
Remove cloudpickle

### ISSUE THREAD

**Issue by zequnyu** [rlworkgroup/garage#778]
It seems `cloudpickle` is no longer needed in garage and therefore should be removed and replaced by `pickle`.

**Comment by ryanjulian** [comment]
Should be a fast one, right?

**Comment by zequnyu** [comment]
Yes, sorry I'm away and my network is not good. I'll do it ASAP.

**Comment by zequnyu** [comment]
Close via #791.

**Comment by ryanjulian** [comment]
great work!
