### ISSUE TITLE
pytest flag --strict-markers requires version 4.5.0

### ISSUE THREAD

**Issue by naeioi** [rlworkgroup/garage#784]
pytest flag `--strict-markers` in https://github.com/rlworkgroup/garage/blob/master/setup.cfg#L79 requires version >= 4.5.0. 

See https://docs.pytest.org/en/latest/changelog.html#pytest-4-5-0-2019-05-11

**Comment by ryanjulian** [comment]
is there a CI failure happening somewhere we can reference?

**Comment by naeioi** [comment]
No. This issue is minor as it only affects old users trying to integration latest changes (like me). The stipulated minimum version of pytest is 3.6, which does not support `--strict-markers`.
https://github.com/rlworkgroup/garage/blob/master/setup.py#L59
