### ISSUE TITLE
VectorizedSamplers should have a higher default n_envs

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#790]
Currently, the default n_envs for VectorizedSamplers is 1. I think it should be at least `max_cpus` as passed to LocalRunner. With VectorizedSampler, CPU load does not appear to scale linearly with number of envs, so this could perhaps be even higher (until we reach marginal returns).

**Comment by zequnyu** [comment]
Emmm would you tell more about how can we find the number of envs for marginal returns?

**Comment by zequnyu** [comment]
@ryanjulian  would you tell more about how can we find the number of envs for marginal returns?

**Comment by ryanjulian** [comment]
@zequnyu I'm not sure I understand how marginal returns are related. Can you explain?

**Comment by zequnyu** [comment]
> With VectorizedSampler, CPU load does not appear to scale linearly with number of envs, so this could perhaps be even higher (until we reach marginal returns).

I'm not sure how to find the maximum number of `n_envs` so that it maximize CPU load. Did I understand your comment correct?

**Comment by ryanjulian** [comment]
Oh, sorry. By "marginal returns" i actually meant "diminishing marginal returns" -- i.e. until it stops making it faster to add environments.

how to determine the ratio? basically, just run some tests. you want to find a multiplier `c` such that when you set `n_envs = c * max_cpus` maxes out the machine (i.e. load average = 1.3-1.5x the number of logical CPUs on a hyperthreaded machine).

essentially, we want to find `c` such that `n_envs = c` consumes ~1 CPU.

**Comment by zequnyu** [comment]
Closed by #825.
