### ISSUE TITLE
OnPolicyVectorizedSampler should not flatten pixel observations

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#794]
Currently OnPolicyVectorizedSampler always flattens the observations, even for pixel observations. Spatial information in the observations will be lost.

**Comment by ryanjulian** [comment]
Perhaps the solution here is for the observations to carry some type information, so we know what to do with them?

**Comment by ahtsan** [comment]
Like paying a bool when constructing the TfEnv?

**Comment by ryanjulian** [comment]
no. peppering your API with bools about what types are being processed is classic terrible software engineering.

I was suggesting that the akro.spaces object would know it was an image, or even better, i would just have some tag on a couple of the dims which instructs the algorithm not to flatten those dimensions.

alternatively, we could introduce an Image space.

**Comment by ahtsan** [comment]
Wrap the environment with an Image space so that `OnPolicyVectorizedSampler` will not flatten the observations?

**Comment by ryanjulian** [comment]
Yes, something like that.

**Comment by ryanjulian** [comment]
closed by #906
