### ISSUE TITLE
OnPolicyVectorizedSampler should normalize pixel observations

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#795]
Currently OffPolicyVectorizedSampler normalizes pixel observations and feed to policies.
OnPolicyVectorizedSampler should also do that.

Policies shouldn't be responsible to normalize pixel inputs since it's more efficient to normalize as a batch when sampling.

**Comment by ryanjulian** [comment]
Don't you think this should be in a wrapper or the algorithm? Why should it be that the sampler *always* normalized pixels? How do we even know when an observation is pixels?

**Comment by ahtsan** [comment]
Can we assume that Box and len(observation_space) == 3?

**Comment by ryanjulian** [comment]
no. we need to deal with arbitrary spaces.

**Comment by ahtsan** [comment]
Actually maybe policy should be responsible to normalize, since policy is the source of knowledge. In the case of DQN, the sampler is required to return unnormalized observations and store into replay buffer. At the time observations are sampled and fed to the policy, that's the time when it is normalized. 

At the time we construct a policy, we should have already known whether input observations should be normalized.
