### ISSUE TITLE
Install tensorflow out of the box

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#80]
We can install tensorflow-cpu in all envs so that garage works out of the box. Those seeking GPU support can easily `pip uninstall -y tensorflow` and `pip install tensorflow_gpu`

**Comment by gonzaiva** [comment]
I think this one will be solved by passing (or not) --tf-gpu to setup_linux.sh

**Comment by ryanjulian** [comment]
The goal here is to install it without using any setup script, only the packaging tool (conda/environment.yml now, pip/setup.py later).

**Comment by gonzaiva** [comment]
I can add vanilla tensorflow to environment.yml. As we mentioned in #251, the setup script removes both flavors of TF to make sure the desired flavor is correctly installed, so it won't be a problem to add TF to the environment file.
If we remove the script in the future, we can follow the procedure you describe in the body of the issue.

**Comment by ryanjulian** [comment]
Yeah please add `tensorflow==1.9.0` to environment.yml, because it can be installed on all machines. For specializations (i.e. GPU), we can remove it and reinstall the special version.

**Comment by gonzaiva** [comment]
Closed with #279
