### ISSUE TITLE
TestOffPolicyVectorizedSampler Should be marked as flaky

### ISSUE THREAD

**Issue by avnishn** [rlworkgroup/garage#808]

**Comment by avnishn** [comment]
test_no_reset, a test function in TestOffPolicyVectorizedSampler has failed and passed after being rerun. Should be marked as flaky

**Comment by ahtsan** [comment]
Reference: https://travis-ci.com/rlworkgroup/garage/jobs/215962492#L2034

**Comment by ryanjulian** [comment]
I'd prefer we just fix it.
