### ISSUE TITLE
Prevent Travis CI from ending build early

### ISSUE THREAD

**Issue by krzentner** [rlworkgroup/garage#822]
It looks like running pytest with multiple processes on Travis CI causes the hung build detector to trip, since pytest doesn't output anything when a test passes until all of the tests have passed.

If no warning is thrown by any test code for 10 minutes, then Travis CI ends the build while the tests are still running.

One easy solution to this is to not run the tests in parallel. Alternatively, we could modify the build scripts to print out a "Still running..." message every five minutes.

**Comment by krzentner** [comment]
I first noticed this while debugging why #821 was failing.

**Comment by avnishn** [comment]
As we discussed, the pytest outputs PASSED as tests pass, and so we shouldn’t need add any print statements to the Travis CI ouput. Can we go ahead and close this for now @krzentner

**Comment by ryanjulian** [comment]
Is this still a problem?

**Comment by krzentner** [comment]
It doesn't seem to be. I definitely observed this happening on a few builds when we switched things over, but I haven't seen it since. It might just have been an older version of pytest or something.
