### ISSUE TITLE
Fix ReplayBuffer / HER for variable lengths paths

### ISSUE THREAD

**Issue by krzentner** [rlworkgroup/garage#837]
The current ReplayBuffer stores transitions in fixed length blocks called "episodes". One would expect each of those transitions to be a path. However, the implementations of `ReplayBuffer` and `OffPolicyVectorizedSampler` do not ensure that is the case, and instead merely collect samples from many separate paths, splitting them into episodes after a fixed number of time steps across all paths. This means if any paths are not exactly `time_horizon` transitions long, then episodes will actually contain transitions from multiple paths. Then, when HerReplayBuffer samples random episodes and post-processes them it produces invalid results since the episode can contain transitions from multiple paths.

**Comment by ryanjulian** [comment]
I second this. Modern off-policy RL algorithms really need 2 types of buffer: an episode buffer and a sample buffer.
