### ISSUE TITLE
Add agent_info to PyTorch policies

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#843]
Currently, some policies are following the tf tree and `get_actions` returns actions and agent_infos while some of them don't. I think we should just unify this and just follow the tf tree. Can one of you take over this? @lywong92 @yonghyuc

**Comment by lywong92** [comment]
Sure, I can work on it.

**Comment by zhanpenghe** [comment]
Great, thank you! @lywong92
