### ISSUE TITLE
Refactor the Sawyer mujoco envs to GoalEnv

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#85]

**Comment by zhanpenghe** [comment]
I am thinking about using inplementation like this:
MujocoEnv->GoalEnv->SawyerEnv->AnySpecificSawyerEnv

**Comment by ryanjulian** [comment]
I suppose that's fine as long as all SawyerEnvs are always GoalEnvs. Is the definition of a GoalEnv that task completion can be represented by a sparse {0, 1} reward?

**Comment by zhanpenghe** [comment]
I don't think it is part of the definition. According to gym's documentation, the reward should depend on a desiredGoal. But for our case it is true that our SawyerEnvs are all GoalEnvs.

**Comment by ryanjulian** [comment]
This sounds fine to me as long as it simplifies the code. If someone gets more creative with Sawyer in the future, they will have to possibly undo this.
