### ISSUE TITLE
cannot install garage via pip

### ISSUE THREAD

**Issue by Chunpai** [rlworkgroup/garage#856]
cannot find garage via pip

**Comment by ryanjulian** [comment]
Our apologies -- garage is not continuously-deployed to PyPI yet. We are working on some changes (even today) to make that possible.

Until then, you should be able to install garage using pip directly from the github repo, rather than from PyPI.

**Comment by krzentner** [comment]
Hello Chunpai. Thanks for your interest in garage. We do not yet have a release of garage on PyPI, so `pip install garage` is not yet possible (although we intend it to be soon). However, garage can be installed by cloning this repo, and then running `pip install numpy==1.14.5 && pip install .` in it.

In the near future, we would like it be possible to install garage with `pip install garage`.
