### ISSUE TITLE
follow the instruction to install garage, but failed

### ISSUE THREAD

**Issue by Chunpai** [rlworkgroup/garage#857]
1. I cannot find the garage via pip
2. if python setup.py install, then I cannot import garage.tf.policies, the **Illegal instruction (core dumped)** occurs, which seems the problem of tensorflow. 
3. I tried to downgrade the tensorflow version, but still did not work

Could anyone help here ?

**Comment by Chunpai** [comment]
I think it is problem of my cpu.

**Comment by Hamza-101** [comment]
@Chunpai how did you solve it?
