### ISSUE TITLE
Average Return per each step

### ISSUE THREAD

**Issue by ilinojkovic** [rlworkgroup/garage#863]
Currently, in several (if not all) algorithms, `AverageReturn` seen in progress file is the sum of undiscounted rewards averaged by number of rollouts per policy update/iteration. However, this metric is dependent on the number of steps per each of the rollouts, and I cannot seem to find a way to average over those as well during training, without changing the `garage` code itself. Meaning, I'm looking for the average reward at each step, across all rollouts in one iteration.

Can you please point me in direction on how to achieve this? If this is not currently supported, can you please add this as another column in the progress table?

**Comment by ryanjulian** [comment]
@ilinojkovic In RL literature, "return" is defined as the cumulative sum of undiscounted rewards. AverageReturn is the average of these across rollouts in a batch.

If you would like to add an AverageRewards field, I suggest you do it in the `process_samples` method of the algorithm(s) of your choice. We'd happily accept a PR for this if it were applied uniformly across all algorithms.

https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/algos/batch_polopt.py#L247
