### ISSUE TITLE
Eliminate unnecessary worker startup

### ISSUE THREAD

**Issue by krzentner** [rlworkgroup/garage#865]
There's a bunch of places where `stateful_pool`'s workers get initialized. They should actually only get initialized when `BatchSampler` (or `ParallelVecEnvExecutor`) need them.

**Comment by naeioi** [comment]
To be more specific, `stateful_pool` is only used in parallel samplers, so the `singleton_pool` created whenever `stateful_pool` is imported is not necessary. The instance should be managed by the sampler.

Also, I think the name of `BatchSampler` is misleading. The name suggests it works by sampling batches serially while it is actually a parallel sampler.

**Comment by zequnyu** [comment]
Closed by #1006.
