### ISSUE TITLE
Eliminate pickled vs non-pickled mode if possible

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#87]
Having pickled and non-pickled modes makes `garage` behave quite differently under the hood, adding a dimension to the testing matrix. Primitives in non-pickled mode are simple python objects, but the serialization implied by pickled mode actually changes the semantics of `garage` quite a bit, in unexpected ways.

Worse still, currently pickling behavior is actually just a side effect of `n_parallel > 1`, so it's a hidden testing dimension. It should at least be an explicit configuration parameter, or the only mode offered by `run_experiment`.

Ideally, parallel and non-parallel modes should operate using the same code, just a different number of workers. Pickling adds non-zero overhead (just how much is not clear), so it's understandable that some people would want to turn it off.

**Comment by naeioi** [comment]
It is worth noting that when `n_parallel > 1` garage will setup parallel samplers, with each sampler worker having its own copy of the policy, but the policy optimization is still on a single process. Ideally, this semantic should have no impact on performance (not in terms of execution but reward)

**Comment by ryanjulian** [comment]
I think it's okay to skip pickling as an optimization if `n_parallel == 1`, but we can still catch pickling bugs in this configuration by insisting on pickling/unpickling the primitives before using them. This optimization can also be internal to the sampler, rather than implemented at the runner level.

@naeioi is this what you do right now?

**Comment by zequnyu** [comment]
I'm confused why we initialise `singleton_pool` in `LocalRunner`. Could you explain to me what's the difference between `n_parallel` in `run_experiment()` and `max_cpus` in `LocalRunner`?

**Comment by naeioi** [comment]
@zequnyu There is no difference. Both `n_parallel` and `max_cpus` do the same job - Initialize `singleton_pool` so that `BatchSampler` works properly. So this is redundancy and one of them should be deprecated. I will argue to remove `n_parallel` from `run_experiment()` because we are likely to remove `run_experiment()` anyway.

**Comment by naeioi** [comment]
Regarding this issue. @ryanjulian Is there a problematic reproducer? Otherwise, as you have pointed out, some people will want to run in the non-pickled mode for performance.

**Comment by ryanjulian** [comment]
The problem is structural. Some bugs appear when pickling which do not appear if you don't pickle. We don't want to have to create a test for both configurations for every test.

My suggested fix is to pickle/unpickle (and use only the pickled version) everything which would be transmitted to a remote process, even if you are in single-process mode. This could be done once at the beginning of training.

Does that make sense?

**Comment by naeioi** [comment]
After some investigation, I can conclude that there's actually no non-pickled mode in garage. Whenever `run_experiment()` is used, it will always pickle the experiment and spawn a new process, regardless of `n_parallel`.

**Comment by ryanjulian** [comment]
okay, i will close this bug then.

**Comment by zequnyu** [comment]
Actually the resume function call in `experiment_wrapper.py` is non-pickled. I think we need some refactoring for that.

**Comment by ryanjulian** [comment]
Doesn't resume imply pickling, though? How could you resume without pickling/unpickling first?

**Comment by zequnyu** [comment]
For the data yes it was loaded. But I think when we refer to pickled mode, we are talking about function call. Concretely:

- define a `run_task()`, pass it to `run_experiment()` in `experiment.py` (as all our examples in `/examples` do)
- in `experiment.py` the `run_task()` is [dumped](https://github.com/rlworkgroup/garage/blob/96342cdc1e3384c06e4decdb1c5cdb23f7976a31/src/garage/experiment/experiment.py#L326)
- then in `experiment_wrapper.py` the function call is [loaded](https://github.com/rlworkgroup/garage/blob/96342cdc1e3384c06e4decdb1c5cdb23f7976a31/src/garage/experiment/experiment_wrapper.py#L200)

But resume doesn't do this. Instead, it [runs](https://github.com/rlworkgroup/garage/blob/96342cdc1e3384c06e4decdb1c5cdb23f7976a31/examples/resume_training.py#L33) the script and [calls](https://github.com/rlworkgroup/garage/blob/96342cdc1e3384c06e4decdb1c5cdb23f7976a31/src/garage/experiment/experiment_wrapper.py#L193) the `LocalRunner` directly.

**Comment by ryanjulian** [comment]
I see. I think this is a slightly different issue than the one this was originally mentioning, but I agree we should unify those approaches. Is there a reason we can't use the same approach as in LocalRunner in both cases?

**Comment by zequnyu** [comment]
I don’t see any. Will try it later.
