### ISSUE TITLE
Inconsistent flattening for dict observation between on- and off-policy samplers

### ISSUE THREAD

**Issue by naeioi** [rlworkgroup/garage#886]
`OffPolicyVectorizedSampler` flattens a dict observation while other samplers do not. This breaks `ContinuousMLPPolicyWithModel` who assumes observation is provided as it is, at this line https://github.com/rlworkgroup/garage/blob/7bb784efdefc7fd8f160718c1d989144ba91e07f/src/garage/tf/policies/continuous_mlp_policy_with_model.py#L150

This issue can be reproduce by running `examples/her_ddpg_fetchreach.py`.

There are also inconsistences in polices' assumption on observation shape. For example, contradicting to `ContinuousMLPPolicyWithModel`, `CategoricalConvPolicyWithModel` assumes observation to be a ndarray. 
https://github.com/rlworkgroup/garage/blob/7bb784efdefc7fd8f160718c1d989144ba91e07f/src/garage/tf/policies/categorical_conv_policy_with_model.py#L146-L147

**Comment by krzentner** [comment]
Fixing this is probably closely related to my current effort to refactor the sampler API, since I'm attempting to make all samplers us the same rollout (and hopefully, same post-processing) functions.

It's also worth mentioning that I'm trying to replace use of the current replay buffer with `PathBuffer`, which is simpler, but more capable and fixes a few difficult to fix bugs in the current replay buffer.

**Comment by ryanjulian** [comment]
@ahtsan did you fix this?

**Comment by ahtsan** [comment]
No I didn't. Currently in `get_actions()`, different policies have slightly different ways to handle. I don't have an exact answer for the following question -- Should we make policies flatten observations, except images? 

Also we are unflattening the actions output inside policies.
https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/policies/continuous_mlp_policy.py#L129
Why do we do that?

**Comment by ryanjulian** [comment]
I don't think there are many logical answers for why we do some of these things.

We are still working on getting the data API consistent among all the algos and primitives.

@krzentner do you think it would be helpful or overkill to define some types like `Episode` or `EpisodeBatch`?

**Comment by irisliucy** [comment]
The issue cannot be reproduced by running `her_ddpg_fetchreach.py`. I've run a couple of tests on the master branch in my local machine and all tests run successfully.
