### ISSUE TITLE
tests.garage.torch.algos.TestVPG is flaky

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#985]
```
______________________________________________________________ TestVPG.test_vpg_regularized ______________________________________________________________
[gw3] linux -- Python 3.6.8 /root/venv/bin/python3

self = <tests.garage.torch.algos.test_vpg.TestVPG object at 0x7fc00c55c6a0>

    def test_vpg_regularized(self):
        """Test VPG with entropy_regularized."""
        self._params['entropy_method'] = 'regularized'
    
        algo = VPG(**self._params)
        self._runner.setup(algo, self._env)
        last_avg_ret = self._runner.train(n_epochs=10, batch_size=100)
>       assert last_avg_ret > 30
E       assert 28.703008538902083 > 30

tests/garage/torch/algos/test_vpg.py:86: AssertionError
```

**Comment by yonghyuc** [comment]
fixed this issue by changing the code " > 0 "

**Comment by ryanjulian** [comment]
Can you please make the bound much tighter than this? Also, don't close the issue without submitting the fix to the repository.

**Comment by yonghyuc** [comment]
Maybe I can put 30 or 35 instead of 0, but I am not sure what is the tighter bound which is not failed regardless of the seed or any other (not related to implementation of the algorithm) reasons.
Do you have any good idea for the number?

**Comment by yonghyuc** [comment]
And I already changed the line in other PR (#924)

**Comment by ryanjulian** [comment]
you need to find a stable number. perhaps run your test 10 times and see what the minimum you get is?
