### ISSUE TITLE
error occured while executing trpo_swimmer.py

### ISSUE THREAD

**Issue by kishanpb** [rlworkgroup/garage#997]
<img width="602" alt="Screen Shot 2019-11-05 at 3 12 06 AM" src="https://user-images.githubusercontent.com/9605238/68194179-30b87a00-ff7a-11e9-8022-f00d4b7fdc2a.png">

<img width="610" alt="Screen Shot 2019-11-05 at 3 08 18 AM" src="https://user-images.githubusercontent.com/9605238/68194035-db7c6880-ff79-11e9-9fd4-0a8d9a664fc5.png">

Does anyone know how to fix this issue? FYI, trpo_cartpole.py works, and I have a mujoco license established properly for swimmer environment.

**Comment by ryanjulian** [comment]
@zequnyu can you take a look?

**Comment by zequnyu** [comment]
I can’t reproduce the issue from running the example. vec_env is initialised in start_worker() and it seems to me that you environment is not properly set. Maybe try to update to the latest version to see if it works?

**Comment by ryanjulian** [comment]
@kishanpb I was also unable to reproduce this locally. Can you provide us with steps to reproduce your error?

Needed:
* Python version
* Environment manager (e.g. system-wide install, virtualenv, pipenv, conda, poetry, etc.)
* Steps to reproduce

**Comment by kishanpb** [comment]
I am using 
- Python 3.7.0, 
- conda, 
- tensorflow 1.13.0.rc1 (the newer version 1.16 threw an error regarding "compat.v1.")

Here is my terminal output when I ran trpo_swimmer as it is without changing the code in it.
![Screen Shot 2019-11-05 at 1 58 36 PM](https://user-images.githubusercontent.com/9605238/68242128-8ec67b00-ffd5-11e9-970b-a06955b0f656.png)

![Screen Shot 2019-11-05 at 1 59 04 PM](https://user-images.githubusercontent.com/9605238/68242134-938b2f00-ffd5-11e9-9273-a255e5ebff44.png)

![Screen Shot 2019-11-05 at 1 59 18 PM](https://user-images.githubusercontent.com/9605238/68242142-9a19a680-ffd5-11e9-916d-955f94ddfa40.png)

Is this a logging issue, as I have shown via arrows above? If so, how to fix this?

**Comment by ryanjulian** [comment]
Which version of garage are you using? What is the output of `conda list`?

**Comment by kishanpb** [comment]
garage is the latest version, I pulled the source before showing this output.

`conda list` is not proper I think 

`(base) ece-Kalathil-MacBook-Pro:tf kishanpb$ conda list

EnvironmentLocationNotFound: Not a conda environment: /Users/kishanpb/anaconda3`

 I think I have not set the conda environment properly. Is there a documentation which I can follow to set it up?

**Comment by ryanjulian** [comment]
You can install garage in your conda environment using `pip install garage` (from the internet) or `pip install -e .[mujoco]` from within the garage repository directory.

Of course, your conda environment must be active for this to work.

If `conda list` is not working, you environment may not be activated.

**Comment by utkarshjp7** [comment]
I would suggest doing a fresh installation of garage in a new conda environment.
`
conda create env -n your_env_name python=3.7
conda activate your_env_name
git clone https://github.com/rlworkgroup/garage
cd garage
pip install -e .[mujoco]
`

**Comment by kishanpb** [comment]
@utkarshjp7 `conda env create -f environment.yml` was easier.

**Comment by ryanjulian** [comment]
@kishanpb that will fail if you already have an environment named `garage`, which is why utkarsh suggested the alternative.
