### ISSUE TITLE
Re-orient all logging and setup around total samples collected

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#998]
Today:
* Logged scalars (e.g. to TensorBoard) all use `Itr` as their x-axis. This makes comparing algorithms with different training procedures and batch sizes difficult.

After this issue is fixed:
* All logged scalars use the total environment samples collected so far as their x-axis
* We could also (optionally) include logs using Itr or the total number of gradient steps (under a different prefix)
* Runner accepts total environment samples as main training argument, either in-addition-to or instead-of `(batch_size, num_itrs)`

**Comment by ryanjulian** [comment]
Steps to achieve this:
1. Ensure all algos (or the runner, or the sampler) are logging the total number of environments steps taken so far.
1. Allow `dowel.TensorBoardOutput` to accept one or more tabular keys as the x-axis, instead of assuming it's "number of times tabular.log has been called"
1. Configure our `TensorBoardOutput` to use the new option

**Comment by naeioi** [comment]
This is closed by #1069 .
